# Generated by Django 6.0.2 on 2026-03-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agentdefinition',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='ingestionrun',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='plugin',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='referencedoc',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sourcechunk',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='template',
            managers=[
            ],
        ),
        migrations.RenameIndex(
            model_name='agentdefinition',
            new_name='plugins_age_plugin__fcdceb_idx',
            old_name='plugins_age_plugin__7f3b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='referencedoc',
            new_name='plugins_ref_plugin__0183af_idx',
            old_name='plugins_ref_plugin__4d8e1f_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcechunk',
            new_name='plugins_sou_plugin__6f82e5_idx',
            old_name='plugins_sou_plugin__b39ce0_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcechunk',
            new_name='plugins_sou_plugin__aa9246_idx',
            old_name='plugins_sou_plugin__e5f4a7_idx',
        ),
        migrations.RenameIndex(
            model_name='sourcechunk',
            new_name='plugins_sou_ref_lib_380c00_idx',
            old_name='plugins_sou_ref_lib_a1c3d2_idx',
        ),
    ]
