export {
  TheoremContextClient,
  type TheoremContextClientOptions,
} from './client.js';
export {
  detectRepoMetadata,
  prepareCodexBundle,
  writeCodexBundle,
} from './adapters/codex.js';
export type {
  CodexBundleResult,
  CodexBundleWriteOptions,
  CodexPrepareOptions,
  CodexRepoMetadata,
} from './adapters/codex.js';
export {
  AuthError,
  CompileError,
  HarnessError,
  RequestTimeoutError,
  ServerUnavailableError,
  StubSurfaceError,
  TheoremContextError,
  UnsupportedSurfaceError,
} from './errors.js';
export {
  TheoremHotGraphClient,
  type TheoremHotGraphClientOptions,
  type THGProductResult,
} from './product.js';
export type {
  Action,
  ActionRailBundle,
  ActionRailGenerateRequest,
  ActionRailPreview,
  ActionRailPreviewRequest,
  ActionRailAction,
  ActionSelectedRequest,
  Atom,
  AtomKind,
  ArtifactAttachResponse,
  ArtifactExport,
  ArtifactExportFormat,
  ArtifactForkResponse,
  ArtifactStatus,
  Capsule,
  CapsuleChannel,
  CompileEvent,
  CompileRequest,
  CompileStageName,
  ContextCommandPayload,
  ContextCommandPreview,
  ContextCommandResolveResponse,
  ContextCommandState,
  ContextArtifact,
  GraphFocusEdge,
  GraphFocusNode,
  GraphFocusResponse,
  GraphHealth,
  GraphPatchesListResponse,
  HarnessBeginRequest,
  HarnessCompareRequest,
  HarnessContextRequest,
  HarnessEvent,
  HarnessForkRequest,
  HarnessGuardViolation,
  HarnessPatchRequest,
  HarnessRun,
  HarnessSearchRequest,
  HarnessSearchRun,
  HarnessStateHashResponse,
  HarnessStep,
  HarnessTransitionRequest,
  HarnessTransitionResult,
  LearningContextSpendPlan,
  LearningContextSpendPlanRequest,
  LearningContextSpendPlanResponse,
  LearningProfileInstallRequest,
  LearningProfileInstallResponse,
  LearningProfileToolkitRequest,
  LearningProfileToolkitResponse,
  LearningStructuralSignalRequest,
  LearningStructuralSignalResponse,
  OutcomeRequest,
  OrchestrateMode,
  OrchestrateRequest,
  OrchestrateResult,
  SavingsBreakdown,
  StressTest,
  StressTestFinding,
  THGCommandRequest,
  THGCypherRequest,
  THGEdge,
  THGNode,
  THGResult,
  TaskType,
  TokenLedger,
} from './types.js';
