export {
  TheoremContextClient,
  type TheoremContextClientOptions,
} from './client.js';
export {
  detectRepoMetadata,
  prepareCodexBundle,
  writeCodexBundle,
} from './adapters/codex.js';
export type {
  CodexBundleResult,
  CodexBundleWriteOptions,
  CodexPrepareOptions,
  CodexRepoMetadata,
} from './adapters/codex.js';
export {
  AuthError,
  CompileError,
  HarnessError,
  RequestTimeoutError,
  ServerUnavailableError,
  StubSurfaceError,
  TheoremContextError,
  UnsupportedSurfaceError,
} from './errors.js';
export {
  TheoremHotGraphClient,
  type TheoremHotGraphClientOptions,
  type THGProductResult,
} from './product.js';
export type {
  Action,
  ActionRailBundle,
  ActionRailGenerateRequest,
  ActionRailPreview,
  ActionRailPreviewRequest,
  ActionRailAction,
  ActionSelectedRequest,
  Atom,
  AtomKind,
  ArtifactAttachResponse,
  ArtifactExport,
  ArtifactExportFormat,
  ArtifactForkResponse,
  ArtifactStatus,
  Capsule,
  CapsuleChannel,
  CompileEvent,
  CompileRequest,
  CompileStageName,
  ContextCommandPayload,
  ContextCommandPreview,
  ContextCommandResolveResponse,
  ContextCommandState,
  ContextWebAtom,
  ContextWebBudget,
  ContextWebCitation,
  ContextWebEdge,
  ContextWebEvaluation,
  ContextWebExplainResponse,
  ContextWebIndex,
  ContextWebIndexUpdateRequest,
  ContextWebPack,
  ContextWebPath,
  ContextWebSpendPlan,
  ContextWebSpendPlanResponse,
  ContextWebTokenLedger,
  ContextWebValidationSummary,
  ContextWebValidatorFinding,
  ContextArtifact,
  DiscoveryCandidate,
  DiscoveryEvent,
  DiscoveryOutcome,
  DiscoveryPreviewRequest,
  DiscoveryRunPreview,
  DiscoveryWritebackProposal,
  ExpressionRenderRequest,
  ExpressionRenderResult,
  GraphFocusEdge,
  GraphFocusNode,
  GraphFocusResponse,
  GraphHealth,
  GraphPatchesListResponse,
  InferenceKernelContract,
  InferenceRegistryReport,
  HarnessBeginRequest,
  HarnessCompareRequest,
  HarnessContextRequest,
  HarnessContextWebRequest,
  HarnessEvent,
  HarnessForkRequest,
  HarnessGuardViolation,
  HarnessPatchRequest,
  HarnessRun,
  HarnessSearchRequest,
  HarnessSearchRun,
  HarnessStateHashResponse,
  HarnessStep,
  HarnessTransitionRequest,
  HarnessTransitionResult,
  LearningContextSpendPlan,
  LearningContextSpendPlanRequest,
  LearningContextSpendPlanResponse,
  LearningProfileInstallRequest,
  LearningProfileInstallResponse,
  LearningProfileToolkitRequest,
  LearningProfileToolkitResponse,
  LearningStructuralSignalRequest,
  LearningStructuralSignalResponse,
  OutcomeRequest,
  OrchestrateContextPlan,
  OrchestrateDecision,
  OrchestrateMode,
  OrchestrateMemoryPolicyProposal,
  OrchestrateMemoryPolicyProposalIntent,
  OrchestrateMemoryRecallTrace,
  OrchestratePrepareHydrationHandle,
  OrchestratePrepareMemoryBank,
  OrchestratePrepareMemoryContract,
  OrchestratePrepareMemoryEvidence,
  OrchestratePrepareMemoryPolicy,
  OrchestratePrepareRecallPolicy,
  OrchestratePrepareRecallPreview,
  OrchestratePrepareResult,
  OrchestratePreviewResult,
  OrchestrateRejectedCandidate,
  OrchestrateReport,
  OrchestrateRequest,
  OrchestrateRiskSummary,
  OrchestrateResult,
  SavingsBreakdown,
  SolverContextCapsuleRequest,
  SolverResult,
  StressTest,
  StressTestFinding,
  THGCommandRequest,
  THGCypherRequest,
  THGEdge,
  THGNode,
  THGResult,
  TaskType,
  TokenLedger,
  ValidatorReceipt,
} from './types.js';
