"""Theorem Context Python SDK.

Mirrors the TypeScript package surface with Pythonic async generators::

    from theorem_context import TheoremContextClient

    cc = TheoremContextClient(api_key='...')
    artifact = await cc.context.compile(task='review the auth module')
    async for event in cc.context.compile_stream(task='...'):
        print(event)
"""

from .adapters.codex import (  # noqa: F401
    begin_harness_bundle,
    compile_run_context_bundle,
    detect_repo_metadata,
    prepare_codex_bundle,
    record_run_outcome,
    write_codex_bundle,
)
from .client import TheoremContextClient  # noqa: F401
from .errors import (  # noqa: F401
    AuthError,
    CompileError,
    HarnessError,
    RequestTimeoutError,
    ServerUnavailableError,
    StubSurfaceError,
    TheoremContextError,
    UnsupportedSurfaceError,
)
from .product import TheoremHotGraphClient  # noqa: F401
from .types import (  # noqa: F401
    Action,
    ActionRailGenerateRequest,
    ActionRailPreviewRequest,
    ActionSelectedRequest,
    Atom,
    ArtifactExport,
    ArtifactExportFormat,
    ArtifactMarkdownExport,
    ArtifactPdfExport,
    ArtifactSignedExport,
    Capsule,
    CapsuleChannel,
    CompileRequest,
    ContextCommandRequest,
    ContextArtifact,
    GraphHealth,
    HarnessBeginRequest,
    HarnessCompareRequest,
    HarnessContextRequest,
    HarnessEvent,
    HarnessForkRequest,
    HarnessGuardViolation,
    HarnessPatchRequest,
    HarnessRun,
    HarnessSearchRequest,
    HarnessSearchRun,
    HarnessStateHashResponse,
    HarnessStep,
    HarnessTransitionRequest,
    HarnessTransitionResult,
    LearningContextSpendPlanRequest,
    LearningProfileInstallRequest,
    LearningProfileToolkitRequest,
    LearningStructuralSignalRequest,
    OutcomeRequest,
    SavingsBreakdown,
    StressTest,
    THGCommandRequest,
    THGCypherRequest,
    THGEdge,
    THGNode,
    THGResult,
    TokenLedger,
)


__all__ = [
    'TheoremContextClient',
    'TheoremContextError',
    'TheoremHotGraphClient',
    'Action',
    'ActionRailGenerateRequest',
    'ActionRailPreviewRequest',
    'ActionSelectedRequest',
    'Atom',
    'AuthError',
    'ArtifactExport',
    'ArtifactExportFormat',
    'ArtifactMarkdownExport',
    'ArtifactPdfExport',
    'ArtifactSignedExport',
    'Capsule',
    'CapsuleChannel',
    'CompileRequest',
    'CompileError',
    'ContextCommandRequest',
    'ContextArtifact',
    'GraphHealth',
    'HarnessError',
    'HarnessBeginRequest',
    'HarnessCompareRequest',
    'HarnessContextRequest',
    'HarnessEvent',
    'HarnessForkRequest',
    'HarnessGuardViolation',
    'HarnessPatchRequest',
    'HarnessRun',
    'HarnessSearchRequest',
    'HarnessSearchRun',
    'HarnessStateHashResponse',
    'HarnessStep',
    'HarnessTransitionRequest',
    'HarnessTransitionResult',
    'LearningContextSpendPlanRequest',
    'LearningProfileInstallRequest',
    'LearningProfileToolkitRequest',
    'LearningStructuralSignalRequest',
    'OutcomeRequest',
    'SavingsBreakdown',
    'StressTest',
    'RequestTimeoutError',
    'ServerUnavailableError',
    'StubSurfaceError',
    'THGCommandRequest',
    'THGCypherRequest',
    'THGEdge',
    'THGNode',
    'THGResult',
    'TokenLedger',
    'UnsupportedSurfaceError',
    'begin_harness_bundle',
    'compile_run_context_bundle',
    'detect_repo_metadata',
    'prepare_codex_bundle',
    'record_run_outcome',
    'write_codex_bundle',
]
