//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:194d6e9c0e4777372491d369
//! Content hash:   sha256:194d6e9c0e4777372491d3699c7d7400f3891abb3b2befc842b3361797aab094
//! Source atom:    atom:code_test_body:2bac99d2f37041dff16f6c3d
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `kind_filter_rejects_unrequested_kinds`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_kind_filter_rejects_unrequested_kinds(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "kind_filter_rejects_unrequested_kinds";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_kind_filter_rejects_unrequested_kinds",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:194d6e9c0e4777372491d3699c7d7400f3891abb3b2befc842b3361797aab094",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4b153355a0f20ec3efa2052db88524e7422fec4061f1c7ab4e85e5588a19dbec", "sha256:f4ef88100d3703d1e6a3bd9d1cc06711706f61dbd397cc4e4bc03f404323f6df"],
        });
    }
    let expected_body_hash = "sha256:f4ef88100d3703d1e6a3bd9d1cc06711706f61dbd397cc4e4bc03f404323f6df";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_kind_filter_rejects_unrequested_kinds",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:194d6e9c0e4777372491d3699c7d7400f3891abb3b2befc842b3361797aab094",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4b153355a0f20ec3efa2052db88524e7422fec4061f1c7ab4e85e5588a19dbec", "sha256:f4ef88100d3703d1e6a3bd9d1cc06711706f61dbd397cc4e4bc03f404323f6df"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_kind_filter_rejects_unrequested_kinds",
        "sha256:194d6e9c0e4777372491d3699c7d7400f3891abb3b2befc842b3361797aab094",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4b153355a0f20ec3efa2052db88524e7422fec4061f1c7ab4e85e5588a19dbec", "sha256:f4ef88100d3703d1e6a3bd9d1cc06711706f61dbd397cc4e4bc03f404323f6df"],
    )
}
