//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:ce07f4d1ccd9269c269a2bb3
//! Content hash:   sha256:ce07f4d1ccd9269c269a2bb30c1a9ece21d12eaf591a169354fe50b53b7d6d83
//! Source atom:    atom:code_test_body:b5aa789ffd0b82ccc11c4721
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `append_rejects_conflicting_event_at_same_sequence`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_append_rejects_conflicting_event_at_same_sequence(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "append_rejects_conflicting_event_at_same_sequence";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_append_rejects_conflicting_event_at_same_sequence",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:ce07f4d1ccd9269c269a2bb30c1a9ece21d12eaf591a169354fe50b53b7d6d83",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:34a1172aed4a07e982db89abc4c48ff0e3572d5c15b26e91bb70e2ff32077886", "sha256:5a02cfabd0ebc494cf90450cb8c905faad1a20e107d46ddba378c6e1c1149f04"],
        });
    }
    let expected_body_hash = "sha256:5a02cfabd0ebc494cf90450cb8c905faad1a20e107d46ddba378c6e1c1149f04";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_append_rejects_conflicting_event_at_same_sequence",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:ce07f4d1ccd9269c269a2bb30c1a9ece21d12eaf591a169354fe50b53b7d6d83",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:34a1172aed4a07e982db89abc4c48ff0e3572d5c15b26e91bb70e2ff32077886", "sha256:5a02cfabd0ebc494cf90450cb8c905faad1a20e107d46ddba378c6e1c1149f04"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_append_rejects_conflicting_event_at_same_sequence",
        "sha256:ce07f4d1ccd9269c269a2bb30c1a9ece21d12eaf591a169354fe50b53b7d6d83",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:34a1172aed4a07e982db89abc4c48ff0e3572d5c15b26e91bb70e2ff32077886", "sha256:5a02cfabd0ebc494cf90450cb8c905faad1a20e107d46ddba378c6e1c1149f04"],
    )
}
