//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:a5db787925a64174b966597f
//! Content hash:   sha256:a5db787925a64174b966597f8169903242e7b43fcc50e4494d93d1a53aaa5a2b
//! Source atom:    atom:code_member:6576b78a5e4e90f0a49bd072
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `claim_has_no_independent_support`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_claim_has_no_independent_support(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "claim_has_no_independent_support";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_claim_has_no_independent_support",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:a5db787925a64174b966597f8169903242e7b43fcc50e4494d93d1a53aaa5a2b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:a1d7dd75a929551b17bb81c596acec02c9ec83844a60bf016c5550a8268bedd6"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_claim_has_no_independent_support",
        "sha256:a5db787925a64174b966597f8169903242e7b43fcc50e4494d93d1a53aaa5a2b",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:a1d7dd75a929551b17bb81c596acec02c9ec83844a60bf016c5550a8268bedd6"],
    )
}
