//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:81bfcc821cd709ad8d764113
//! Content hash:   sha256:81bfcc821cd709ad8d76411356d54c29b6550f1f1aaf3f81e2ce7dc818dfce2e
//! Source atom:    atom:code_test_body:7938b484ad58342d69253944
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_alloc_bitmap_32_middle_1`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_alloc_bitmap_32_middle_1(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_alloc_bitmap_32_middle_1";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_alloc_bitmap_32_middle_1",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:81bfcc821cd709ad8d76411356d54c29b6550f1f1aaf3f81e2ce7dc818dfce2e",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:96cf12640ee0a1ca49b173d462b8bcd0ce3efc848f5bef1cecfdaa7b5eb29324", "sha256:9debed0f9a92752d8302f21425f3fa2031fc83006f97169bdcdaba11abb5f772"],
        });
    }
    let expected_body_hash = "sha256:9debed0f9a92752d8302f21425f3fa2031fc83006f97169bdcdaba11abb5f772";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_alloc_bitmap_32_middle_1",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:81bfcc821cd709ad8d76411356d54c29b6550f1f1aaf3f81e2ce7dc818dfce2e",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:96cf12640ee0a1ca49b173d462b8bcd0ce3efc848f5bef1cecfdaa7b5eb29324", "sha256:9debed0f9a92752d8302f21425f3fa2031fc83006f97169bdcdaba11abb5f772"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_alloc_bitmap_32_middle_1",
        "sha256:81bfcc821cd709ad8d76411356d54c29b6550f1f1aaf3f81e2ce7dc818dfce2e",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:96cf12640ee0a1ca49b173d462b8bcd0ce3efc848f5bef1cecfdaa7b5eb29324", "sha256:9debed0f9a92752d8302f21425f3fa2031fc83006f97169bdcdaba11abb5f772"],
    )
}
