//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:a22029efc48a9b50ce56c1c3
//! Content hash:   sha256:a22029efc48a9b50ce56c1c3ad3c69dbba782df21ac0b6f5803ad78d6fed9c99
//! Source atom:    atom:code_member:5568091fdd45e6750de8d43c
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `conflict_set`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_conflict_set(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "conflict_set";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_conflict_set",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:a22029efc48a9b50ce56c1c3ad3c69dbba782df21ac0b6f5803ad78d6fed9c99",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:a1d7dd75a929551b17bb81c596acec02c9ec83844a60bf016c5550a8268bedd6"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_conflict_set",
        "sha256:a22029efc48a9b50ce56c1c3ad3c69dbba782df21ac0b6f5803ad78d6fed9c99",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:a1d7dd75a929551b17bb81c596acec02c9ec83844a60bf016c5550a8268bedd6"],
    )
}
