//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:5af8cc185d3fb2a013c595b6
//! Content hash:   sha256:5af8cc185d3fb2a013c595b6348a370e7b2a9706a39acaab36a9ece0b848fc84
//! Source atom:    atom:code_member:0944c3f0fda959351feae592
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `skill_pack_get_node`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_skill_pack_get_node_5af8cc18(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "skill_pack_get_node";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_skill_pack_get_node_5af8cc18",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:5af8cc185d3fb2a013c595b6348a370e7b2a9706a39acaab36a9ece0b848fc84",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_skill_pack_get_node_5af8cc18",
        "sha256:5af8cc185d3fb2a013c595b6348a370e7b2a9706a39acaab36a9ece0b848fc84",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a"],
    )
}
