//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:497cfb3921219db30fbe205e
//! Content hash:   sha256:497cfb3921219db30fbe205e92cc2d9e4ebf14876ee03efe4aa71be1a4e78226
//! Source atom:    atom:code_member:21078956891da842147a0bff
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `for_agent`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_for_agent(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "for_agent";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_for_agent",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:497cfb3921219db30fbe205e92cc2d9e4ebf14876ee03efe4aa71be1a4e78226",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_for_agent",
        "sha256:497cfb3921219db30fbe205e92cc2d9e4ebf14876ee03efe4aa71be1a4e78226",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
    )
}
