//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:db4d0e4b4f6c7da65a6f8be5
//! Content hash:   sha256:db4d0e4b4f6c7da65a6f8be535d1d5682abab9eeb12a002ce4c72e5d75d2869f
//! Source atom:    atom:code_test_body:afcbee76fd7a29ecfdbe7945
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `backend_components_returns_partition`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_backend_components_returns_partition(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "backend_components_returns_partition";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_backend_components_returns_partition",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:db4d0e4b4f6c7da65a6f8be535d1d5682abab9eeb12a002ce4c72e5d75d2869f",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba", "sha256:2d055f39964330c335370348fd8cad187571503707021dc536cd0c80dd60bac7"],
        });
    }
    let expected_body_hash = "sha256:2d055f39964330c335370348fd8cad187571503707021dc536cd0c80dd60bac7";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_backend_components_returns_partition",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:db4d0e4b4f6c7da65a6f8be535d1d5682abab9eeb12a002ce4c72e5d75d2869f",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba", "sha256:2d055f39964330c335370348fd8cad187571503707021dc536cd0c80dd60bac7"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_backend_components_returns_partition",
        "sha256:db4d0e4b4f6c7da65a6f8be535d1d5682abab9eeb12a002ce4c72e5d75d2869f",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba", "sha256:2d055f39964330c335370348fd8cad187571503707021dc536cd0c80dd60bac7"],
    )
}
