//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:27b385f3e6e213e6dbd93227
//! Content hash:   sha256:27b385f3e6e213e6dbd93227680dd9d1d05e34411340d940c00e608c15d7a5d5
//! Source atom:    atom:code_test_body:65a81df6729fc4a8a45b8d87
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_oauth_client_uses_fresh_config`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_oauth_client_uses_fresh_config(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_oauth_client_uses_fresh_config";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_oauth_client_uses_fresh_config",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:27b385f3e6e213e6dbd93227680dd9d1d05e34411340d940c00e608c15d7a5d5",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:d9382edc90d9a577874d3ef8b7881d0eae916b4c2426eead68f131699b203693", "sha256:56a9ed54775f2840facf64f11c30aa94ce5e2a3a493584b2d5a52e0fc5c1fbe7"],
        });
    }
    let expected_body_hash = "sha256:56a9ed54775f2840facf64f11c30aa94ce5e2a3a493584b2d5a52e0fc5c1fbe7";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_oauth_client_uses_fresh_config",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:27b385f3e6e213e6dbd93227680dd9d1d05e34411340d940c00e608c15d7a5d5",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:d9382edc90d9a577874d3ef8b7881d0eae916b4c2426eead68f131699b203693", "sha256:56a9ed54775f2840facf64f11c30aa94ce5e2a3a493584b2d5a52e0fc5c1fbe7"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_oauth_client_uses_fresh_config",
        "sha256:27b385f3e6e213e6dbd93227680dd9d1d05e34411340d940c00e608c15d7a5d5",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:d9382edc90d9a577874d3ef8b7881d0eae916b4c2426eead68f131699b203693", "sha256:56a9ed54775f2840facf64f11c30aa94ce5e2a3a493584b2d5a52e0fc5c1fbe7"],
    )
}
