//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:928979bf05c2f6d66834e020
//! Content hash:   sha256:928979bf05c2f6d66834e02025fadbdab4912c80b38d7bdd2a913954c21a724d
//! Source atom:    atom:code_test_body:e6614893f57a07827ce7e7b9
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `capability_scope_limits_the_charter_surface`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_capability_scope_limits_the_charter_surface(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "capability_scope_limits_the_charter_surface";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_capability_scope_limits_the_charter_surface",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:928979bf05c2f6d66834e02025fadbdab4912c80b38d7bdd2a913954c21a724d",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:4617d80776d50b49a4b9fa94b5970e7c808b10bda3c2a319c282afabc31eea12", "sha256:3a49c24355a21c6e09d7aad317aea51305ce8846cf230e96f546556866e03e16"],
        });
    }
    let expected_body_hash = "sha256:3a49c24355a21c6e09d7aad317aea51305ce8846cf230e96f546556866e03e16";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_capability_scope_limits_the_charter_surface",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:928979bf05c2f6d66834e02025fadbdab4912c80b38d7bdd2a913954c21a724d",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:4617d80776d50b49a4b9fa94b5970e7c808b10bda3c2a319c282afabc31eea12", "sha256:3a49c24355a21c6e09d7aad317aea51305ce8846cf230e96f546556866e03e16"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_capability_scope_limits_the_charter_surface",
        "sha256:928979bf05c2f6d66834e02025fadbdab4912c80b38d7bdd2a913954c21a724d",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:4617d80776d50b49a4b9fa94b5970e7c808b10bda3c2a319c282afabc31eea12", "sha256:3a49c24355a21c6e09d7aad317aea51305ce8846cf230e96f546556866e03e16"],
    )
}
