//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:6362eb2f477d54851d64dd03
//! Content hash:   sha256:6362eb2f477d54851d64dd033b915ee40cea05678f2982f50d17c322be5b69d1
//! Source atom:    atom:code_member:7285ba81e39c4a90c19c315f
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `upsert_edge`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_upsert_edge_6362eb2f(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "upsert_edge";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_upsert_edge_6362eb2f",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:6362eb2f477d54851d64dd033b915ee40cea05678f2982f50d17c322be5b69d1",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:f3b00b3df4d2595831b3b2ee2ac79d62ad2d76ffdabbfe5e9f32aa1ced12c951"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_upsert_edge_6362eb2f",
        "sha256:6362eb2f477d54851d64dd033b915ee40cea05678f2982f50d17c322be5b69d1",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:f3b00b3df4d2595831b3b2ee2ac79d62ad2d76ffdabbfe5e9f32aa1ced12c951"],
    )
}
