//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:412831bf981b5eee98183e1c
//! Content hash:   sha256:412831bf981b5eee98183e1cc520a8f5667f23068f9c7f33efc86f8ce6f8ffd3
//! Source atom:    atom:code_member:b759246b5d3ff97fc2b4f65a
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `pack_get_node`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_pack_get_node(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "pack_get_node";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_pack_get_node",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:412831bf981b5eee98183e1cc520a8f5667f23068f9c7f33efc86f8ce6f8ffd3",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:9f33c8610ea0c34d1a54b80962b245e07519271de4dd663a1b1823e69c4a1d6f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_pack_get_node",
        "sha256:412831bf981b5eee98183e1cc520a8f5667f23068f9c7f33efc86f8ce6f8ffd3",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:9f33c8610ea0c34d1a54b80962b245e07519271de4dd663a1b1823e69c4a1d6f"],
    )
}
