//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:4ad975fd92155aeef234fb21
//! Content hash:   sha256:4ad975fd92155aeef234fb21d5542737f15d4f5b2f06294fc0145c94a4c15367
//! Source atom:    atom:code_member:2ed882de79f4ba405f072c4e
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `get_node`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_get_node_4ad975fd(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "get_node";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_get_node_4ad975fd",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:4ad975fd92155aeef234fb21d5542737f15d4f5b2f06294fc0145c94a4c15367",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_get_node_4ad975fd",
        "sha256:4ad975fd92155aeef234fb21d5542737f15d4f5b2f06294fc0145c94a4c15367",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
    )
}
