//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:ac8fa9601f64c588b4110fc1
//! Content hash:   sha256:ac8fa9601f64c588b4110fc19e83aefafb53c93958dde804e540e03ae7d7f9f3
//! Source atom:    atom:code_member:93763fc44d39aeaf0167c318
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `canonical_json`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_canonical_json(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "canonical_json";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_canonical_json",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:ac8fa9601f64c588b4110fc19e83aefafb53c93958dde804e540e03ae7d7f9f3",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:a1d7dd75a929551b17bb81c596acec02c9ec83844a60bf016c5550a8268bedd6"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_canonical_json",
        "sha256:ac8fa9601f64c588b4110fc19e83aefafb53c93958dde804e540e03ae7d7f9f3",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:a1d7dd75a929551b17bb81c596acec02c9ec83844a60bf016c5550a8268bedd6"],
    )
}
