//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:12d0507dc5ff0ca6017a65eb
//! Content hash:   sha256:12d0507dc5ff0ca6017a65eb71b9d689118b1aa53c4ac3ac6fd89477d26e5d5b
//! Source atom:    atom:code_test_body:813928c5ece965779a57950d
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_js_in_html`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_js_in_html(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_js_in_html";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_js_in_html",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:12d0507dc5ff0ca6017a65eb71b9d689118b1aa53c4ac3ac6fd89477d26e5d5b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:520fa2c8c6ba5ab888283d307e90be058dcb963581483eadfa565e3923f8ab71", "sha256:6f60f57e87940fe0d5d1b47f20188aebd6e223f32f0a66401aa636f77beb960f"],
        });
    }
    let expected_body_hash = "sha256:6f60f57e87940fe0d5d1b47f20188aebd6e223f32f0a66401aa636f77beb960f";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_js_in_html",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:12d0507dc5ff0ca6017a65eb71b9d689118b1aa53c4ac3ac6fd89477d26e5d5b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:520fa2c8c6ba5ab888283d307e90be058dcb963581483eadfa565e3923f8ab71", "sha256:6f60f57e87940fe0d5d1b47f20188aebd6e223f32f0a66401aa636f77beb960f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_js_in_html",
        "sha256:12d0507dc5ff0ca6017a65eb71b9d689118b1aa53c4ac3ac6fd89477d26e5d5b",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:520fa2c8c6ba5ab888283d307e90be058dcb963581483eadfa565e3923f8ab71", "sha256:6f60f57e87940fe0d5d1b47f20188aebd6e223f32f0a66401aa636f77beb960f"],
    )
}
