//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:7a6c73415f880edc4909aadc
//! Content hash:   sha256:7a6c73415f880edc4909aadc8fe5d767bc1c3a1cafc86d80a0cf29e5496caea0
//! Source atom:    atom:code_member:5f902b8b1569a0b5dbd4e49c
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `candidate_code_member_name`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_candidate_code_member_name(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "candidate_code_member_name";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_candidate_code_member_name",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:7a6c73415f880edc4909aadc8fe5d767bc1c3a1cafc86d80a0cf29e5496caea0",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_candidate_code_member_name",
        "sha256:7a6c73415f880edc4909aadc8fe5d767bc1c3a1cafc86d80a0cf29e5496caea0",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a"],
    )
}
