//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:20433550856aabe3a14fc272
//! Content hash:   sha256:20433550856aabe3a14fc2726e1216e1bba886122513fd45c552fe8110632698
//! Source atom:    atom:code_member:c15c7e6211c42c33495a39a2
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `pack_upsert_edge`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_pack_upsert_edge_20433550(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "pack_upsert_edge";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_pack_upsert_edge_20433550",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:20433550856aabe3a14fc2726e1216e1bba886122513fd45c552fe8110632698",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:9f33c8610ea0c34d1a54b80962b245e07519271de4dd663a1b1823e69c4a1d6f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_pack_upsert_edge_20433550",
        "sha256:20433550856aabe3a14fc2726e1216e1bba886122513fd45c552fe8110632698",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:9f33c8610ea0c34d1a54b80962b245e07519271de4dd663a1b1823e69c4a1d6f"],
    )
}
