//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:996c0b1977838e7e89b250e5
//! Content hash:   sha256:996c0b1977838e7e89b250e58152ba79230d1436965a88bfa2a4fddc7f407d80
//! Source atom:    atom:code_member:9d783e9dd68ffbd0fa3cf061
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `get_edge`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_get_edge_996c0b19(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "get_edge";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_get_edge_996c0b19",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:996c0b1977838e7e89b250e58152ba79230d1436965a88bfa2a4fddc7f407d80",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_get_edge_996c0b19",
        "sha256:996c0b1977838e7e89b250e58152ba79230d1436965a88bfa2a4fddc7f407d80",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
