//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:add7923ec8c5dda2881d42a8
//! Content hash:   sha256:add7923ec8c5dda2881d42a8873632c124e0517a29ac9bf2cbebdeb99bc917e3
//! Source atom:    atom:code_member:3480d2db25beed77369037b2
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `neighbors`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_neighbors_add7923e(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "neighbors";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_neighbors_add7923e",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:add7923ec8c5dda2881d42a8873632c124e0517a29ac9bf2cbebdeb99bc917e3",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_neighbors_add7923e",
        "sha256:add7923ec8c5dda2881d42a8873632c124e0517a29ac9bf2cbebdeb99bc917e3",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
