//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:f8409c7b3942136507689f0e
//! Content hash:   sha256:f8409c7b3942136507689f0e4a1f1ed4055aef2223556de798572ef90e8afc8c
//! Source atom:    atom:code_test_body:8fce5f68954cb54ac765c5b3
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `validation_gate_wraps_compare_modes`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_validation_gate_wraps_compare_modes(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "validation_gate_wraps_compare_modes";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_validation_gate_wraps_compare_modes",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:f8409c7b3942136507689f0e4a1f1ed4055aef2223556de798572ef90e8afc8c",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:069f86bbe089a3c420254caa64629b0cc112966d3ac44b00434d63ad2607be38", "sha256:1fe3cb454b7bcfa1739888087d04070f4c0cdc471d4c1337579a9cdbb7940f4c"],
        });
    }
    let expected_body_hash = "sha256:1fe3cb454b7bcfa1739888087d04070f4c0cdc471d4c1337579a9cdbb7940f4c";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_validation_gate_wraps_compare_modes",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:f8409c7b3942136507689f0e4a1f1ed4055aef2223556de798572ef90e8afc8c",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:069f86bbe089a3c420254caa64629b0cc112966d3ac44b00434d63ad2607be38", "sha256:1fe3cb454b7bcfa1739888087d04070f4c0cdc471d4c1337579a9cdbb7940f4c"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_validation_gate_wraps_compare_modes",
        "sha256:f8409c7b3942136507689f0e4a1f1ed4055aef2223556de798572ef90e8afc8c",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:069f86bbe089a3c420254caa64629b0cc112966d3ac44b00434d63ad2607be38", "sha256:1fe3cb454b7bcfa1739888087d04070f4c0cdc471d4c1337579a9cdbb7940f4c"],
    )
}
