//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:7e9604e1432728109352900f
//! Content hash:   sha256:7e9604e1432728109352900f82ddc416b588524440eaaf1f3a98e5ee0b8d5cc5
//! Source atom:    atom:code_member:e04d6efa8524ba9c9c2e5a09
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `robots_policy_id`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_robots_policy_id(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "robots_policy_id";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_robots_policy_id",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:7e9604e1432728109352900f82ddc416b588524440eaaf1f3a98e5ee0b8d5cc5",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:322f31931b4c2312910c384bd46c422e866dea03bb6024f98fa90fb68ef58cd0"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_robots_policy_id",
        "sha256:7e9604e1432728109352900f82ddc416b588524440eaaf1f3a98e5ee0b8d5cc5",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:322f31931b4c2312910c384bd46c422e866dea03bb6024f98fa90fb68ef58cd0"],
    )
}
