//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:853b2f9d2f6e51a28829504d
//! Content hash:   sha256:853b2f9d2f6e51a28829504d7a66ef8a1842f82c116ef151f5f8b9e79f668d9b
//! Source atom:    atom:code_test_body:daf4948927cbf20c1d82e139
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `redcore_reopens_memory_documents_nodes_and_edges`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_redcore_reopens_memory_documents_nodes_and_edges(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "redcore_reopens_memory_documents_nodes_and_edges";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_redcore_reopens_memory_documents_nodes_and_edges",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:853b2f9d2f6e51a28829504d7a66ef8a1842f82c116ef151f5f8b9e79f668d9b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c068a3ad3c6eeb3bcb8521ab44bc0cdbb9c7a770c6011a4079a4d3aab8f025fa", "sha256:eb6135a27ee08b7e974705d71d1fee160eece0574b57b68cd3f76502d51b804d"],
        });
    }
    let expected_body_hash = "sha256:eb6135a27ee08b7e974705d71d1fee160eece0574b57b68cd3f76502d51b804d";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_redcore_reopens_memory_documents_nodes_and_edges",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:853b2f9d2f6e51a28829504d7a66ef8a1842f82c116ef151f5f8b9e79f668d9b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c068a3ad3c6eeb3bcb8521ab44bc0cdbb9c7a770c6011a4079a4d3aab8f025fa", "sha256:eb6135a27ee08b7e974705d71d1fee160eece0574b57b68cd3f76502d51b804d"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_redcore_reopens_memory_documents_nodes_and_edges",
        "sha256:853b2f9d2f6e51a28829504d7a66ef8a1842f82c116ef151f5f8b9e79f668d9b",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c068a3ad3c6eeb3bcb8521ab44bc0cdbb9c7a770c6011a4079a4d3aab8f025fa", "sha256:eb6135a27ee08b7e974705d71d1fee160eece0574b57b68cd3f76502d51b804d"],
    )
}
