//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:019ec84513e36140451556ea
//! Content hash:   sha256:019ec84513e36140451556ea41f1e17c201b3bb7b4e22204b1a66a66a9d94fc7
//! Source atom:    atom:code_test_body:0041771a5ff8d705c39865c4
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `passport_extraction`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_passport_extraction(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "passport_extraction";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_passport_extraction",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:019ec84513e36140451556ea41f1e17c201b3bb7b4e22204b1a66a66a9d94fc7",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:b0c9795e01fd34a14f50d143b46f8e1019781e5999686a47db641ba814ea3288", "sha256:51bfbbc505c6b6f1c0a6c829dc5aa605e323676eb4b7c7436b0193702c105b6a"],
        });
    }
    let expected_body_hash = "sha256:51bfbbc505c6b6f1c0a6c829dc5aa605e323676eb4b7c7436b0193702c105b6a";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_passport_extraction",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:019ec84513e36140451556ea41f1e17c201b3bb7b4e22204b1a66a66a9d94fc7",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:b0c9795e01fd34a14f50d143b46f8e1019781e5999686a47db641ba814ea3288", "sha256:51bfbbc505c6b6f1c0a6c829dc5aa605e323676eb4b7c7436b0193702c105b6a"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_passport_extraction",
        "sha256:019ec84513e36140451556ea41f1e17c201b3bb7b4e22204b1a66a66a9d94fc7",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:b0c9795e01fd34a14f50d143b46f8e1019781e5999686a47db641ba814ea3288", "sha256:51bfbbc505c6b6f1c0a6c829dc5aa605e323676eb4b7c7436b0193702c105b6a"],
    )
}
