//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:467088b622916c0e1317a969
//! Content hash:   sha256:467088b622916c0e1317a9690013474e90201a5cfcf542e8dd2eb3270aee850f
//! Source atom:    atom:code_member:23354981aff158723aef6c84
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `binding_transition_requirements`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_binding_transition_requirements(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "binding_transition_requirements";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_binding_transition_requirements",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:467088b622916c0e1317a9690013474e90201a5cfcf542e8dd2eb3270aee850f",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_binding_transition_requirements",
        "sha256:467088b622916c0e1317a9690013474e90201a5cfcf542e8dd2eb3270aee850f",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
    )
}
