//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:52bf391445eaca4616971277
//! Content hash:   sha256:52bf391445eaca4616971277302c668220df8a28e1681181dc913100ffaf6ddf
//! Source atom:    atom:code_test_body:48cf38b2f9aaa42442ba1e0e
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `browser_affordances_expose_rustyred_and_rustyweb`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_browser_affordances_expose_rustyred_and_rustyweb(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "browser_affordances_expose_rustyred_and_rustyweb";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_browser_affordances_expose_rustyred_and_rustyweb",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:52bf391445eaca4616971277302c668220df8a28e1681181dc913100ffaf6ddf",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de", "sha256:d58b2471799c96b91bb4270c0aa95305fd63fc47ecd63360eb3c6ab74ff35dab"],
        });
    }
    let expected_body_hash = "sha256:d58b2471799c96b91bb4270c0aa95305fd63fc47ecd63360eb3c6ab74ff35dab";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_browser_affordances_expose_rustyred_and_rustyweb",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:52bf391445eaca4616971277302c668220df8a28e1681181dc913100ffaf6ddf",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de", "sha256:d58b2471799c96b91bb4270c0aa95305fd63fc47ecd63360eb3c6ab74ff35dab"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_browser_affordances_expose_rustyred_and_rustyweb",
        "sha256:52bf391445eaca4616971277302c668220df8a28e1681181dc913100ffaf6ddf",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de", "sha256:d58b2471799c96b91bb4270c0aa95305fd63fc47ecd63360eb3c6ab74ff35dab"],
    )
}
