//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:d1d403389c1c12a0e65b1ccd
//! Content hash:   sha256:d1d403389c1c12a0e65b1ccd86f59e870fb659133cfdc26489734e2f866f86e8
//! Source atom:    atom:code_member:953308fdf11d6bd399c5e249
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `parse_edge_record`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_parse_edge_record(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "parse_edge_record";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_parse_edge_record",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:d1d403389c1c12a0e65b1ccd86f59e870fb659133cfdc26489734e2f866f86e8",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_parse_edge_record",
        "sha256:d1d403389c1c12a0e65b1ccd86f59e870fb659133cfdc26489734e2f866f86e8",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
