//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:a18b5d8620f033e397c01d62
//! Content hash:   sha256:a18b5d8620f033e397c01d6203739312f8f5cb705084458b8a01c1025d6f56af
//! Source atom:    atom:code_test_body:b14e8280451b178e5568e998
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_sg_scan_py_empty_text`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_sg_scan_py_empty_text(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_sg_scan_py_empty_text";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_sg_scan_py_empty_text",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:a18b5d8620f033e397c01d6203739312f8f5cb705084458b8a01c1025d6f56af",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:4fbc8626241cea6b3bb59d6468dc888bb790a77e63094cb17f77ffe24be801b1"],
        });
    }
    let expected_body_hash = "sha256:4fbc8626241cea6b3bb59d6468dc888bb790a77e63094cb17f77ffe24be801b1";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_sg_scan_py_empty_text",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:a18b5d8620f033e397c01d6203739312f8f5cb705084458b8a01c1025d6f56af",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:4fbc8626241cea6b3bb59d6468dc888bb790a77e63094cb17f77ffe24be801b1"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_sg_scan_py_empty_text",
        "sha256:a18b5d8620f033e397c01d6203739312f8f5cb705084458b8a01c1025d6f56af",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:4fbc8626241cea6b3bb59d6468dc888bb790a77e63094cb17f77ffe24be801b1"],
    )
}
