//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:bfe7cf76a7c5292778165313
//! Content hash:   sha256:bfe7cf76a7c5292778165313df843444ac5ad1f7e10a1dd9490028dc609fe9a6
//! Source atom:    atom:code_member:23c1f94b44e880e7aa609771
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `plain_node`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_plain_node(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "plain_node";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_plain_node",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:bfe7cf76a7c5292778165313df843444ac5ad1f7e10a1dd9490028dc609fe9a6",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_plain_node",
        "sha256:bfe7cf76a7c5292778165313df843444ac5ad1f7e10a1dd9490028dc609fe9a6",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
