//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:bca921be28319e20f8d80907
//! Content hash:   sha256:bca921be28319e20f8d8090775eec8b9e04fd1caca4fa3ecb50c3f480ef041f9
//! Source atom:    atom:code_test_body:f95e5dc5068edc20d6fd709a
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `tools_list_exposes_read_only_graph_tools`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_tools_list_exposes_read_only_graph_tools(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "tools_list_exposes_read_only_graph_tools";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_tools_list_exposes_read_only_graph_tools",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:bca921be28319e20f8d8090775eec8b9e04fd1caca4fa3ecb50c3f480ef041f9",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba", "sha256:83313c7ee4aa59095cc31a590e1f681bc11e0daba1c536caa5d499bb5a49a13e"],
        });
    }
    let expected_body_hash = "sha256:83313c7ee4aa59095cc31a590e1f681bc11e0daba1c536caa5d499bb5a49a13e";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_tools_list_exposes_read_only_graph_tools",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:bca921be28319e20f8d8090775eec8b9e04fd1caca4fa3ecb50c3f480ef041f9",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba", "sha256:83313c7ee4aa59095cc31a590e1f681bc11e0daba1c536caa5d499bb5a49a13e"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_tools_list_exposes_read_only_graph_tools",
        "sha256:bca921be28319e20f8d8090775eec8b9e04fd1caca4fa3ecb50c3f480ef041f9",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba", "sha256:83313c7ee4aa59095cc31a590e1f681bc11e0daba1c536caa5d499bb5a49a13e"],
    )
}
