//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:0e404fca3128c9328094d46f
//! Content hash:   sha256:0e404fca3128c9328094d46f90f1f4fe69ab1832f9d8e3303eeb07fc87d9b2a1
//! Source atom:    atom:code_member:2813fdc175495eb5a2d45ac9
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `fmt`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_fmt_0e404fca(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "fmt";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_fmt_0e404fca",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:0e404fca3128c9328094d46f90f1f4fe69ab1832f9d8e3303eeb07fc87d9b2a1",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_fmt_0e404fca",
        "sha256:0e404fca3128c9328094d46f90f1f4fe69ab1832f9d8e3303eeb07fc87d9b2a1",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
    )
}
