//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:e6802b1156317be2cf15372e
//! Content hash:   sha256:e6802b1156317be2cf15372e19f9b8b40ca0d5fad4e01dc2a6db03b103c0f64b
//! Source atom:    atom:code_test_body:14a5ab84f837460b6e5fc60c
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `list_packs_reads_beyond_default_graph_query_limit`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_list_packs_reads_beyond_default_graph_query_limit(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "list_packs_reads_beyond_default_graph_query_limit";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_list_packs_reads_beyond_default_graph_query_limit",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:e6802b1156317be2cf15372e19f9b8b40ca0d5fad4e01dc2a6db03b103c0f64b",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:9f33c8610ea0c34d1a54b80962b245e07519271de4dd663a1b1823e69c4a1d6f", "sha256:65112674f74612dee9e6045fca81df5e8df43380b6633bab477cdcc415203e8d"],
        });
    }
    let expected_body_hash = "sha256:65112674f74612dee9e6045fca81df5e8df43380b6633bab477cdcc415203e8d";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_list_packs_reads_beyond_default_graph_query_limit",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:e6802b1156317be2cf15372e19f9b8b40ca0d5fad4e01dc2a6db03b103c0f64b",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:9f33c8610ea0c34d1a54b80962b245e07519271de4dd663a1b1823e69c4a1d6f", "sha256:65112674f74612dee9e6045fca81df5e8df43380b6633bab477cdcc415203e8d"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_list_packs_reads_beyond_default_graph_query_limit",
        "sha256:e6802b1156317be2cf15372e19f9b8b40ca0d5fad4e01dc2a6db03b103c0f64b",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:9f33c8610ea0c34d1a54b80962b245e07519271de4dd663a1b1823e69c4a1d6f", "sha256:65112674f74612dee9e6045fca81df5e8df43380b6633bab477cdcc415203e8d"],
    )
}
