//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:dcfb54604a4508bf0c55f9cb
//! Content hash:   sha256:dcfb54604a4508bf0c55f9cbb432d41608e90fab32cbd9b62dfaf01a09aa7484
//! Source atom:    atom:code_member:30fa4cdeff20a8363d327fc3
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `bounded_text`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_bounded_text(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "bounded_text";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_bounded_text",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:dcfb54604a4508bf0c55f9cbb432d41608e90fab32cbd9b62dfaf01a09aa7484",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:322f31931b4c2312910c384bd46c422e866dea03bb6024f98fa90fb68ef58cd0"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_bounded_text",
        "sha256:dcfb54604a4508bf0c55f9cbb432d41608e90fab32cbd9b62dfaf01a09aa7484",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:322f31931b4c2312910c384bd46c422e866dea03bb6024f98fa90fb68ef58cd0"],
    )
}
