//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:8b6e3807c8e3c19d3980cd51
//! Content hash:   sha256:8b6e3807c8e3c19d3980cd51d9bc7ec5026ef3b1ad779aaae8653387f6d5f4dc
//! Source atom:    atom:code_test_body:f2511678c060e938c812377e
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `read_write_tools_list_exposes_bulk_and_designation_tools`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_read_write_tools_list_exposes_bulk_and_designation_tools(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "read_write_tools_list_exposes_bulk_and_designation_tools";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_read_write_tools_list_exposes_bulk_and_designation_tools",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:8b6e3807c8e3c19d3980cd51d9bc7ec5026ef3b1ad779aaae8653387f6d5f4dc",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f", "sha256:1e0e22390d67fd3d397372bb5a6d87d08cb37242aad8337ee8d1480aaa541916"],
        });
    }
    let expected_body_hash = "sha256:1e0e22390d67fd3d397372bb5a6d87d08cb37242aad8337ee8d1480aaa541916";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_read_write_tools_list_exposes_bulk_and_designation_tools",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:8b6e3807c8e3c19d3980cd51d9bc7ec5026ef3b1ad779aaae8653387f6d5f4dc",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f", "sha256:1e0e22390d67fd3d397372bb5a6d87d08cb37242aad8337ee8d1480aaa541916"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_read_write_tools_list_exposes_bulk_and_designation_tools",
        "sha256:8b6e3807c8e3c19d3980cd51d9bc7ec5026ef3b1ad779aaae8653387f6d5f4dc",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f", "sha256:1e0e22390d67fd3d397372bb5a6d87d08cb37242aad8337ee8d1480aaa541916"],
    )
}
