//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:5d2703781af76fe20f842342
//! Content hash:   sha256:5d2703781af76fe20f842342d0932fa24726f5b501905f3bf1d10b51d38fe24c
//! Source atom:    atom:code_test_body:48ddb0d5a9c66be7485436fc
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `crawl_delay_maps_to_duration`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_crawl_delay_maps_to_duration(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "crawl_delay_maps_to_duration";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_crawl_delay_maps_to_duration",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:5d2703781af76fe20f842342d0932fa24726f5b501905f3bf1d10b51d38fe24c",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1111634e70e5d7add3a22ca956e258a1342e0e66e4863f305847042665e81e74", "sha256:97679d609acacde03eef508babfb7cc1904f1ef2dad3c08f92db9efc6c937ce8"],
        });
    }
    let expected_body_hash = "sha256:97679d609acacde03eef508babfb7cc1904f1ef2dad3c08f92db9efc6c937ce8";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_crawl_delay_maps_to_duration",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:5d2703781af76fe20f842342d0932fa24726f5b501905f3bf1d10b51d38fe24c",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1111634e70e5d7add3a22ca956e258a1342e0e66e4863f305847042665e81e74", "sha256:97679d609acacde03eef508babfb7cc1904f1ef2dad3c08f92db9efc6c937ce8"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_crawl_delay_maps_to_duration",
        "sha256:5d2703781af76fe20f842342d0932fa24726f5b501905f3bf1d10b51d38fe24c",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1111634e70e5d7add3a22ca956e258a1342e0e66e4863f305847042665e81e74", "sha256:97679d609acacde03eef508babfb7cc1904f1ef2dad3c08f92db9efc6c937ce8"],
    )
}
