//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:8dd80b19284e004954831f2e
//! Content hash:   sha256:8dd80b19284e004954831f2e2b4d88ebd29bdf183c9bded5e8db79e69b4ca142
//! Source atom:    atom:code_member:94365d67239b60d555970a19
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `browser_session_store_receipts_increment_run_ids`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_browser_session_store_receipts_increment_run_ids(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "browser_session_store_receipts_increment_run_ids";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_browser_session_store_receipts_increment_run_ids",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:8dd80b19284e004954831f2e2b4d88ebd29bdf183c9bded5e8db79e69b4ca142",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_browser_session_store_receipts_increment_run_ids",
        "sha256:8dd80b19284e004954831f2e2b4d88ebd29bdf183c9bded5e8db79e69b4ca142",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
    )
}
