//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:b410fa5bbc28c61dc1961e8d
//! Content hash:   sha256:b410fa5bbc28c61dc1961e8dd0c70aaf9553094efd56d0237154921f853a4661
//! Source atom:    atom:code_member:39da1dca04d46642de517b0d
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `sync_directory`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_sync_directory(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "sync_directory";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_sync_directory",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:b410fa5bbc28c61dc1961e8dd0c70aaf9553094efd56d0237154921f853a4661",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_sync_directory",
        "sha256:b410fa5bbc28c61dc1961e8dd0c70aaf9553094efd56d0237154921f853a4661",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
