//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:c85a1f8e8dab79adbe098ef5
//! Content hash:   sha256:c85a1f8e8dab79adbe098ef57b67f4575c19c510c7f61805bfbc405438487c6b
//! Source atom:    atom:code_member:db11155a9aa601788bf777b0
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `apply`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_apply(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "apply";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_apply",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:c85a1f8e8dab79adbe098ef57b67f4575c19c510c7f61805bfbc405438487c6b",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_apply",
        "sha256:c85a1f8e8dab79adbe098ef57b67f4575c19c510c7f61805bfbc405438487c6b",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
    )
}
