//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:57c129aeed911c6d9f5284f8
//! Content hash:   sha256:57c129aeed911c6d9f5284f814c742b881813e798c7e8ca1076ab52cb6bc5a4c
//! Source atom:    atom:code_member:b2bd222c8aedb6e9b2c263ce
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `parse_ref`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_parse_ref_57c129ae(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "parse_ref";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_parse_ref_57c129ae",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:57c129aeed911c6d9f5284f814c742b881813e798c7e8ca1076ab52cb6bc5a4c",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:da5301b01417198329eba5e9d67767233084fa0c67eb5a7a8e5249b0fd19b881"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_parse_ref_57c129ae",
        "sha256:57c129aeed911c6d9f5284f814c742b881813e798c7e8ca1076ab52cb6bc5a4c",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:da5301b01417198329eba5e9d67767233084fa0c67eb5a7a8e5249b0fd19b881"],
    )
}
