//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:3b5de274b1d878a1c875cc17
//! Content hash:   sha256:3b5de274b1d878a1c875cc17fea8722dbdd7df0bc980ad6a907631a25c34d3e7
//! Source atom:    atom:code_member:d39056712ad89564771165f8
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `harness_run_detail`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_harness_run_detail_3b5de274(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "harness_run_detail";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_harness_run_detail_3b5de274",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:3b5de274b1d878a1c875cc17fea8722dbdd7df0bc980ad6a907631a25c34d3e7",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_harness_run_detail_3b5de274",
        "sha256:3b5de274b1d878a1c875cc17fea8722dbdd7df0bc980ad6a907631a25c34d3e7",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
    )
}
