//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:c3e775ba59381c7c805c18c1
//! Content hash:   sha256:c3e775ba59381c7c805c18c12d246b7ab706a9334f16bda9dac024a628638f77
//! Source atom:    atom:code_member:446ef0a61bac780a1b43f3bb
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `apply_all_code_actions`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_apply_all_code_actions(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "apply_all_code_actions";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_apply_all_code_actions",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:c3e775ba59381c7c805c18c12d246b7ab706a9334f16bda9dac024a628638f77",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ffcce5bb5e87b27e22c0657a32c7c74c14e77e11fd3a3f3c0ab561c4b56ff21d"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_apply_all_code_actions",
        "sha256:c3e775ba59381c7c805c18c12d246b7ab706a9334f16bda9dac024a628638f77",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ffcce5bb5e87b27e22c0657a32c7c74c14e77e11fd3a3f3c0ab561c4b56ff21d"],
    )
}
