//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:dea15d0d3fb0dd7199944eb1
//! Content hash:   sha256:dea15d0d3fb0dd7199944eb1eb8c19d7122b4405b5bd1e692a41f0efddfd13a2
//! Source atom:    atom:code_member:b8c7d439be2cf4a09a32d3ac
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `compute_content_hash`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_compute_content_hash(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "compute_content_hash";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_compute_content_hash",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:dea15d0d3fb0dd7199944eb1eb8c19d7122b4405b5bd1e692a41f0efddfd13a2",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4c6c2c52b32361a4f7b48b9fc00dade2972c7d07c14e33005d3dc251a4a30982"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_compute_content_hash",
        "sha256:dea15d0d3fb0dd7199944eb1eb8c19d7122b4405b5bd1e692a41f0efddfd13a2",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4c6c2c52b32361a4f7b48b9fc00dade2972c7d07c14e33005d3dc251a4a30982"],
    )
}
