//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:a5acdbe49b8298f4cdc70d6f
//! Content hash:   sha256:a5acdbe49b8298f4cdc70d6f3a59aa38bb51487b44f06a7723ce09689f724397
//! Source atom:    atom:code_member:b373e865b66c1b77b4d54e4b
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `auto_index_vectors`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_auto_index_vectors(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "auto_index_vectors";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_auto_index_vectors",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:a5acdbe49b8298f4cdc70d6f3a59aa38bb51487b44f06a7723ce09689f724397",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_auto_index_vectors",
        "sha256:a5acdbe49b8298f4cdc70d6f3a59aa38bb51487b44f06a7723ce09689f724397",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
