//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:446ae4f4f99db61658282ca8
//! Content hash:   sha256:446ae4f4f99db61658282ca82a4a1e9b17ef18035e41fbcfbf36417089225044
//! Source atom:    atom:code_member:05beb49346c4588ae0c61390
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `coerce_year`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_coerce_year(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "coerce_year";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_coerce_year",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:446ae4f4f99db61658282ca82a4a1e9b17ef18035e41fbcfbf36417089225044",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:a1d7dd75a929551b17bb81c596acec02c9ec83844a60bf016c5550a8268bedd6"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_coerce_year",
        "sha256:446ae4f4f99db61658282ca82a4a1e9b17ef18035e41fbcfbf36417089225044",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:a1d7dd75a929551b17bb81c596acec02c9ec83844a60bf016c5550a8268bedd6"],
    )
}
