//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:66d1ced883d112751115c4e5
//! Content hash:   sha256:66d1ced883d112751115c4e5e89ff0cf624e28a755a82754527852b4866eaff1
//! Source atom:    atom:code_test_body:0475b279db57883399a42bef
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `get_node_returns_none_for_expired_node`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_get_node_returns_none_for_expired_node(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "get_node_returns_none_for_expired_node";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_get_node_returns_none_for_expired_node",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:66d1ced883d112751115c4e5e89ff0cf624e28a755a82754527852b4866eaff1",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:d2e79f1cb1bfb684beeb1e4684fbfed406b187bfa88c3b29162eb81ec220b47d"],
        });
    }
    let expected_body_hash = "sha256:d2e79f1cb1bfb684beeb1e4684fbfed406b187bfa88c3b29162eb81ec220b47d";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_get_node_returns_none_for_expired_node",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:66d1ced883d112751115c4e5e89ff0cf624e28a755a82754527852b4866eaff1",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:d2e79f1cb1bfb684beeb1e4684fbfed406b187bfa88c3b29162eb81ec220b47d"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_get_node_returns_none_for_expired_node",
        "sha256:66d1ced883d112751115c4e5e89ff0cf624e28a755a82754527852b4866eaff1",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:d2e79f1cb1bfb684beeb1e4684fbfed406b187bfa88c3b29162eb81ec220b47d"],
    )
}
