//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:74a5c6f7ded5733393159e0e
//! Content hash:   sha256:74a5c6f7ded5733393159e0ea94aae44a7f73e013067d5fa05f9bcbd1c9985c7
//! Source atom:    atom:code_member:76397b042cc287b2007f42bc
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `optional_repository`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_optional_repository(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "optional_repository";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_optional_repository",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:74a5c6f7ded5733393159e0ea94aae44a7f73e013067d5fa05f9bcbd1c9985c7",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_optional_repository",
        "sha256:74a5c6f7ded5733393159e0ea94aae44a7f73e013067d5fa05f9bcbd1c9985c7",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
