//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:c16e394194e9fa16b8905171
//! Content hash:   sha256:c16e394194e9fa16b8905171bd8540ddc8c382a3bf42b6ce12239180d25da25e
//! Source atom:    atom:code_member:5a5a34bfca5ff3259a5ce0d9
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `skill_pack_query_nodes`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_skill_pack_query_nodes_c16e3941(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "skill_pack_query_nodes";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_skill_pack_query_nodes_c16e3941",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:c16e394194e9fa16b8905171bd8540ddc8c382a3bf42b6ce12239180d25da25e",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_skill_pack_query_nodes_c16e3941",
        "sha256:c16e394194e9fa16b8905171bd8540ddc8c382a3bf42b6ce12239180d25da25e",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a"],
    )
}
