//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:e76c282452e17ce480c722e2
//! Content hash:   sha256:e76c282452e17ce480c722e2d286edada881c66e50f3fdb1edb936325329e3b2
//! Source atom:    atom:code_member:97d62006f0546a0b5c343c58
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `ingesting_a_page_writes_page_link_and_snapshot_nodes_to_the_store`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_ingesting_a_page_writes_page_link_and_snapshot_nodes_to_the_store(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "ingesting_a_page_writes_page_link_and_snapshot_nodes_to_the_store";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_ingesting_a_page_writes_page_link_and_snapshot_nodes_to_the_store",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:e76c282452e17ce480c722e2d286edada881c66e50f3fdb1edb936325329e3b2",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_ingesting_a_page_writes_page_link_and_snapshot_nodes_to_the_store",
        "sha256:e76c282452e17ce480c722e2d286edada881c66e50f3fdb1edb936325329e3b2",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
    )
}
