//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:bf87fe1c77133a06ec0a4eab
//! Content hash:   sha256:bf87fe1c77133a06ec0a4eab6c8049ad433a933c0c13e22045467bc44a7e260c
//! Source atom:    atom:code_test_body:433940dc500eff2875fd6210
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `algorithm_pagerank_inline_returns_scores`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_algorithm_pagerank_inline_returns_scores(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "algorithm_pagerank_inline_returns_scores";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_algorithm_pagerank_inline_returns_scores",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:bf87fe1c77133a06ec0a4eab6c8049ad433a933c0c13e22045467bc44a7e260c",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f", "sha256:90c5ce345173547f28fff594b3e3b24903b31715d5be319c7e74d55c462125b1"],
        });
    }
    let expected_body_hash = "sha256:90c5ce345173547f28fff594b3e3b24903b31715d5be319c7e74d55c462125b1";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_algorithm_pagerank_inline_returns_scores",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:bf87fe1c77133a06ec0a4eab6c8049ad433a933c0c13e22045467bc44a7e260c",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f", "sha256:90c5ce345173547f28fff594b3e3b24903b31715d5be319c7e74d55c462125b1"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_algorithm_pagerank_inline_returns_scores",
        "sha256:bf87fe1c77133a06ec0a4eab6c8049ad433a933c0c13e22045467bc44a7e260c",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f", "sha256:90c5ce345173547f28fff594b3e3b24903b31715d5be319c7e74d55c462125b1"],
    )
}
