//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:d6ec100ff0e6b9ed10eaebf2
//! Content hash:   sha256:d6ec100ff0e6b9ed10eaebf2ae02c97f8f540f4a3ad935492fdf68a6d66de530
//! Source atom:    atom:code_member:c7549d332f03fdf3c2ffae9a
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `neighbors`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_neighbors_d6ec100f(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "neighbors";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_neighbors_d6ec100f",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:d6ec100ff0e6b9ed10eaebf2ae02c97f8f540f4a3ad935492fdf68a6d66de530",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_neighbors_d6ec100f",
        "sha256:d6ec100ff0e6b9ed10eaebf2ae02c97f8f540f4a3ad935492fdf68a6d66de530",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
