//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:b126812243adfd1030180e38
//! Content hash:   sha256:b126812243adfd1030180e3825b46316bb3ae09efbe2135ae7efea77dc2138e3
//! Source atom:    atom:code_test_body:e3a6c7cea1593969145a4fb6
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `get_node_returns_node_within_ttl_window`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_get_node_returns_node_within_ttl_window(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "get_node_returns_node_within_ttl_window";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_get_node_returns_node_within_ttl_window",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:b126812243adfd1030180e3825b46316bb3ae09efbe2135ae7efea77dc2138e3",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:6ad27a49cb14b2ba2acbb9ef5b4c6c2b3b9767fe80a28edda75e4a8d00242caa"],
        });
    }
    let expected_body_hash = "sha256:6ad27a49cb14b2ba2acbb9ef5b4c6c2b3b9767fe80a28edda75e4a8d00242caa";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_get_node_returns_node_within_ttl_window",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:b126812243adfd1030180e3825b46316bb3ae09efbe2135ae7efea77dc2138e3",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:6ad27a49cb14b2ba2acbb9ef5b4c6c2b3b9767fe80a28edda75e4a8d00242caa"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_get_node_returns_node_within_ttl_window",
        "sha256:b126812243adfd1030180e3825b46316bb3ae09efbe2135ae7efea77dc2138e3",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:6ad27a49cb14b2ba2acbb9ef5b4c6c2b3b9767fe80a28edda75e4a8d00242caa"],
    )
}
