//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:39d68be006c7f4505c79d897
//! Content hash:   sha256:39d68be006c7f4505c79d8970dc57bf807b2c87da9c1247475b8aa2a5492d69a
//! Source atom:    atom:code_test_body:62180e293ad56824c11ddc1f
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `replay_preserves_event_idempotency_key`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_replay_preserves_event_idempotency_key(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "replay_preserves_event_idempotency_key";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_replay_preserves_event_idempotency_key",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:39d68be006c7f4505c79d8970dc57bf807b2c87da9c1247475b8aa2a5492d69a",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:34a1172aed4a07e982db89abc4c48ff0e3572d5c15b26e91bb70e2ff32077886", "sha256:871b15672e6193e977be36c2410a5ae575bd9bf36c31bf07e6e50c07347c3c71"],
        });
    }
    let expected_body_hash = "sha256:871b15672e6193e977be36c2410a5ae575bd9bf36c31bf07e6e50c07347c3c71";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_replay_preserves_event_idempotency_key",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:39d68be006c7f4505c79d8970dc57bf807b2c87da9c1247475b8aa2a5492d69a",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:34a1172aed4a07e982db89abc4c48ff0e3572d5c15b26e91bb70e2ff32077886", "sha256:871b15672e6193e977be36c2410a5ae575bd9bf36c31bf07e6e50c07347c3c71"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_replay_preserves_event_idempotency_key",
        "sha256:39d68be006c7f4505c79d8970dc57bf807b2c87da9c1247475b8aa2a5492d69a",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:34a1172aed4a07e982db89abc4c48ff0e3572d5c15b26e91bb70e2ff32077886", "sha256:871b15672e6193e977be36c2410a5ae575bd9bf36c31bf07e6e50c07347c3c71"],
    )
}
