//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:42a21d596be3c720dafb54fd
//! Content hash:   sha256:42a21d596be3c720dafb54fd9ea0b6ab2b0ff36b878ddee0366a447c58dbcaac
//! Source atom:    atom:code_member:ea8347cbe8f77d783d43f44d
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `next`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_next_42a21d59(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "next";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_next_42a21d59",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:42a21d596be3c720dafb54fd9ea0b6ab2b0ff36b878ddee0366a447c58dbcaac",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:79c8dc0d0f77f874c44d2b5065c489aa304b5c9993a94c5307b30ee64d513c11"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_next_42a21d59",
        "sha256:42a21d596be3c720dafb54fd9ea0b6ab2b0ff36b878ddee0366a447c58dbcaac",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:79c8dc0d0f77f874c44d2b5065c489aa304b5c9993a94c5307b30ee64d513c11"],
    )
}
