//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:e694e5c83f7551dfaa89a99e
//! Content hash:   sha256:e694e5c83f7551dfaa89a99e17d8be8d2fd39730f8fcaa6dde057d570a7ddead
//! Source atom:    atom:code_member:3291f23768b8450f611eb446
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `rebuild_indexes`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_rebuild_indexes_e694e5c8(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "rebuild_indexes";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_rebuild_indexes_e694e5c8",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:e694e5c83f7551dfaa89a99e17d8be8d2fd39730f8fcaa6dde057d570a7ddead",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_rebuild_indexes_e694e5c8",
        "sha256:e694e5c83f7551dfaa89a99e17d8be8d2fd39730f8fcaa6dde057d570a7ddead",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
