//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:5856652f65633b1ef30ffce4
//! Content hash:   sha256:5856652f65633b1ef30ffce49cddb677ac85ed36c85bb5096cb429d7a79270e1
//! Source atom:    atom:code_member:5f32544ced37d6ecb7853413
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `notes_sync_fetch_does_not_import_authorship_notes`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_notes_sync_fetch_does_not_import_authorship_notes(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "notes_sync_fetch_does_not_import_authorship_notes";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_notes_sync_fetch_does_not_import_authorship_notes",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:5856652f65633b1ef30ffce49cddb677ac85ed36c85bb5096cb429d7a79270e1",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:12f3bf863dc332b8345329367277eacf7255ba1c83d92196fd9a101f0cf77cca"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_notes_sync_fetch_does_not_import_authorship_notes",
        "sha256:5856652f65633b1ef30ffce49cddb677ac85ed36c85bb5096cb429d7a79270e1",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:12f3bf863dc332b8345329367277eacf7255ba1c83d92196fd9a101f0cf77cca"],
    )
}
