//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:4024716829014a21909bea94
//! Content hash:   sha256:4024716829014a21909bea945297ef44bf25112fdab47b6e9750e7e3f2751ce0
//! Source atom:    atom:code_test_body:2cf35380b7954d97558722a7
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_commit_hunks_consecutive_same_attribution_merges`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_commit_hunks_consecutive_same_attribution_merges(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_commit_hunks_consecutive_same_attribution_merges";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_commit_hunks_consecutive_same_attribution_merges",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:4024716829014a21909bea945297ef44bf25112fdab47b6e9750e7e3f2751ce0",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4c6c2c52b32361a4f7b48b9fc00dade2972c7d07c14e33005d3dc251a4a30982", "sha256:740a99d46276d45ea5a5b84ee16119781105c264fa298209e8cdcbcf3dea7864"],
        });
    }
    let expected_body_hash = "sha256:740a99d46276d45ea5a5b84ee16119781105c264fa298209e8cdcbcf3dea7864";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_commit_hunks_consecutive_same_attribution_merges",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:4024716829014a21909bea945297ef44bf25112fdab47b6e9750e7e3f2751ce0",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4c6c2c52b32361a4f7b48b9fc00dade2972c7d07c14e33005d3dc251a4a30982", "sha256:740a99d46276d45ea5a5b84ee16119781105c264fa298209e8cdcbcf3dea7864"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_commit_hunks_consecutive_same_attribution_merges",
        "sha256:4024716829014a21909bea945297ef44bf25112fdab47b6e9750e7e3f2751ce0",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4c6c2c52b32361a4f7b48b9fc00dade2972c7d07c14e33005d3dc251a4a30982", "sha256:740a99d46276d45ea5a5b84ee16119781105c264fa298209e8cdcbcf3dea7864"],
    )
}
