//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:525db9b0d32e80ca776499e5
//! Content hash:   sha256:525db9b0d32e80ca776499e50eb75adbc538ceb115d2cef37e5da9f17967b9c5
//! Source atom:    atom:code_member:8c7242c87d0c95d70bcaf96a
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `query_nodes`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_query_nodes_525db9b0(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "query_nodes";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_query_nodes_525db9b0",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:525db9b0d32e80ca776499e50eb75adbc538ceb115d2cef37e5da9f17967b9c5",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_query_nodes_525db9b0",
        "sha256:525db9b0d32e80ca776499e50eb75adbc538ceb115d2cef37e5da9f17967b9c5",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
