//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:27d98b5d3db36d027f8b1624
//! Content hash:   sha256:27d98b5d3db36d027f8b1624fe99f709826443ef7536171e702787b71cb600b1
//! Source atom:    atom:code_member:27acb733d691cedd9f377c7b
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `invocation_receipt_node_id`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_invocation_receipt_node_id(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "invocation_receipt_node_id";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_invocation_receipt_node_id",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:27d98b5d3db36d027f8b1624fe99f709826443ef7536171e702787b71cb600b1",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:f3b00b3df4d2595831b3b2ee2ac79d62ad2d76ffdabbfe5e9f32aa1ced12c951"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_invocation_receipt_node_id",
        "sha256:27d98b5d3db36d027f8b1624fe99f709826443ef7536171e702787b71cb600b1",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:f3b00b3df4d2595831b3b2ee2ac79d62ad2d76ffdabbfe5e9f32aa1ced12c951"],
    )
}
