//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:03b04fa9f6938b727ff51dc8
//! Content hash:   sha256:03b04fa9f6938b727ff51dc83da60dd4d3bef6d8e33411655d369b60689e309e
//! Source atom:    atom:code_member:b3f4eb177b3c93e466029d28
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `get_edge`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_get_edge(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "get_edge";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_get_edge",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:03b04fa9f6938b727ff51dc83da60dd4d3bef6d8e33411655d369b60689e309e",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_get_edge",
        "sha256:03b04fa9f6938b727ff51dc83da60dd4d3bef6d8e33411655d369b60689e309e",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
