//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:609f6bb3876d17e5304f9f5d
//! Content hash:   sha256:609f6bb3876d17e5304f9f5dc406ee812b6c88836866f8f0653937e56670e704
//! Source atom:    atom:code_member:e4087bde93b4acaff89069ff
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `coordination_intent_node`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_coordination_intent_node(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "coordination_intent_node";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_coordination_intent_node",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:609f6bb3876d17e5304f9f5dc406ee812b6c88836866f8f0653937e56670e704",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_coordination_intent_node",
        "sha256:609f6bb3876d17e5304f9f5dc406ee812b6c88836866f8f0653937e56670e704",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
