//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:e1c9afc8023eb61b3bca220e
//! Content hash:   sha256:e1c9afc8023eb61b3bca220edd8a4d1edfe63baaa287c12fd3502d761260779b
//! Source atom:    atom:code_member:1231cb19981ad5ef6334d3d2
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `algo_communities`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_algo_communities(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "algo_communities";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_algo_communities",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:e1c9afc8023eb61b3bca220edd8a4d1edfe63baaa287c12fd3502d761260779b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_algo_communities",
        "sha256:e1c9afc8023eb61b3bca220edd8a4d1edfe63baaa287c12fd3502d761260779b",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
    )
}
