//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:ce6e588e94d046dc20a9a52c
//! Content hash:   sha256:ce6e588e94d046dc20a9a52c8f17a7be789be03c0cf1beeaaefb90beff023c89
//! Source atom:    atom:code_member:9a6358c46598c62671d56693
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `remove_edge_indexes`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_remove_edge_indexes(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "remove_edge_indexes";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_remove_edge_indexes",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:ce6e588e94d046dc20a9a52c8f17a7be789be03c0cf1beeaaefb90beff023c89",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_remove_edge_indexes",
        "sha256:ce6e588e94d046dc20a9a52c8f17a7be789be03c0cf1beeaaefb90beff023c89",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
