//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:f4ec4c0741506cac09fcd904
//! Content hash:   sha256:f4ec4c0741506cac09fcd9046fa3035db7fc87660bd0f942414d99cee7ff91d0
//! Source atom:    atom:code_member:00af56af3aa973fe81af760f
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `render_substrate_search_page`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_render_substrate_search_page(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "render_substrate_search_page";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_render_substrate_search_page",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:f4ec4c0741506cac09fcd9046fa3035db7fc87660bd0f942414d99cee7ff91d0",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_render_substrate_search_page",
        "sha256:f4ec4c0741506cac09fcd9046fa3035db7fc87660bd0f942414d99cee7ff91d0",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
    )
}
