//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:7c9e870e61db29229c613cfd
//! Content hash:   sha256:7c9e870e61db29229c613cfd46f7ce9e7eb9155377f676d84effef064782b8a9
//! Source atom:    atom:code_member:f03b91991bdd86c2ff9bf7d1
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `unique_test_dir`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_unique_test_dir(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "unique_test_dir";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_unique_test_dir",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:7c9e870e61db29229c613cfd46f7ce9e7eb9155377f676d84effef064782b8a9",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_unique_test_dir",
        "sha256:7c9e870e61db29229c613cfd46f7ce9e7eb9155377f676d84effef064782b8a9",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
