//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:385182a302ac7575d67802fe
//! Content hash:   sha256:385182a302ac7575d67802fe566cfe04b532cbb4a0ebaa605f932ca883451729
//! Source atom:    atom:code_member:0b97f8662e62c2e97e0fa37e
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `normalize_urgency`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_normalize_urgency(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "normalize_urgency";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_normalize_urgency",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:385182a302ac7575d67802fe566cfe04b532cbb4a0ebaa605f932ca883451729",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:891b9bc92554ee3451df4eac6c32a526ad6940f41e443c4ff0028b948571eb47"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_normalize_urgency",
        "sha256:385182a302ac7575d67802fe566cfe04b532cbb4a0ebaa605f932ca883451729",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:891b9bc92554ee3451df4eac6c32a526ad6940f41e443c4ff0028b948571eb47"],
    )
}
