//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:5ec63cc3bd0bc3d5408946be
//! Content hash:   sha256:5ec63cc3bd0bc3d5408946be59570bab324d330818a5abaf862c5b045b353616
//! Source atom:    atom:code_member:a5abfce1b4b60d13e2a3d2f7
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `redcore_manifest_records_format_kind_and_crate_version`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_redcore_manifest_records_format_kind_and_crate_version(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "redcore_manifest_records_format_kind_and_crate_version";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_redcore_manifest_records_format_kind_and_crate_version",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:5ec63cc3bd0bc3d5408946be59570bab324d330818a5abaf862c5b045b353616",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_redcore_manifest_records_format_kind_and_crate_version",
        "sha256:5ec63cc3bd0bc3d5408946be59570bab324d330818a5abaf862c5b045b353616",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
