//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:d2f55da5217fe87e679925b5
//! Content hash:   sha256:d2f55da5217fe87e679925b50e433c4d50dc48b87e4381e0cab9ac52f216d766
//! Source atom:    atom:code_member:1c51b4a398ea4f291410033a
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `validate_pack_state`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_validate_pack_state(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "validate_pack_state";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_validate_pack_state",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:d2f55da5217fe87e679925b50e433c4d50dc48b87e4381e0cab9ac52f216d766",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_validate_pack_state",
        "sha256:d2f55da5217fe87e679925b50e433c4d50dc48b87e4381e0cab9ac52f216d766",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a"],
    )
}
