//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:fc998e79eb135f7d11819a9f
//! Content hash:   sha256:fc998e79eb135f7d11819a9fc90ca1a529b5ffcf35a95385b5a8a2746a37c9b0
//! Source atom:    atom:code_member:db16ce51b9201193b2c8ff1c
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `redis_indexes`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_redis_indexes(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "redis_indexes";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_redis_indexes",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:fc998e79eb135f7d11819a9fc90ca1a529b5ffcf35a95385b5a8a2746a37c9b0",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_redis_indexes",
        "sha256:fc998e79eb135f7d11819a9fc90ca1a529b5ffcf35a95385b5a8a2746a37c9b0",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
