//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:6a54ff099792bd9daa0d728d
//! Content hash:   sha256:6a54ff099792bd9daa0d728dd315d0b6d1c684cfeeac92e0c123175e5765ac89
//! Source atom:    atom:code_member:9dc4934e061d1804eccc25d4
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `algo_components`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_algo_components(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "algo_components";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_algo_components",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:6a54ff099792bd9daa0d728dd315d0b6d1c684cfeeac92e0c123175e5765ac89",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_algo_components",
        "sha256:6a54ff099792bd9daa0d728dd315d0b6d1c684cfeeac92e0c123175e5765ac89",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
