//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:7a86ef747d9358b0a558b8bd
//! Content hash:   sha256:7a86ef747d9358b0a558b8bd7db509a3bf48b96f54a357f75afa92e166bc2a4b
//! Source atom:    atom:code_member:8e9e44f556b356f70d314b72
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `merged_metadata`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_merged_metadata(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "merged_metadata";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_merged_metadata",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:7a86ef747d9358b0a558b8bd7db509a3bf48b96f54a357f75afa92e166bc2a4b",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_merged_metadata",
        "sha256:7a86ef747d9358b0a558b8bd7db509a3bf48b96f54a357f75afa92e166bc2a4b",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a"],
    )
}
