//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:02d77d3f727f4f6b01ec6403
//! Content hash:   sha256:02d77d3f727f4f6b01ec640344357ad4ab23d3cd183980a2e2761c58634f1ef1
//! Source atom:    atom:code_member:3be9c9623880ec039305e60e
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `edge_types`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_edge_types(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "edge_types";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_edge_types",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:02d77d3f727f4f6b01ec640344357ad4ab23d3cd183980a2e2761c58634f1ef1",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_edge_types",
        "sha256:02d77d3f727f4f6b01ec640344357ad4ab23d3cd183980a2e2761c58634f1ef1",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
    )
}
