//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:9007207a986dd505788ce24f
//! Content hash:   sha256:9007207a986dd505788ce24f61bccdbb7a6b7f4a731627adbdf148dc680997f8
//! Source atom:    atom:code_member:fc8e0c0889e6c45a61a2fbca
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `edge_types`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_edge_types_9007207a(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "edge_types";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_edge_types_9007207a",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:9007207a986dd505788ce24f61bccdbb7a6b7f4a731627adbdf148dc680997f8",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_edge_types_9007207a",
        "sha256:9007207a986dd505788ce24f61bccdbb7a6b7f4a731627adbdf148dc680997f8",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
