//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:a30d32ee5ff4eacc8863e0d7
//! Content hash:   sha256:a30d32ee5ff4eacc8863e0d79a305f7f3207cb92db373e846cfa43ca1e4520c1
//! Source atom:    atom:code_member:03217656660c901cdc1ded5c
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `labels`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_labels_a30d32ee(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "labels";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_labels_a30d32ee",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:a30d32ee5ff4eacc8863e0d79a305f7f3207cb92db373e846cfa43ca1e4520c1",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_labels_a30d32ee",
        "sha256:a30d32ee5ff4eacc8863e0d79a305f7f3207cb92db373e846cfa43ca1e4520c1",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
    )
}
