//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:33e59ae450c9cad7b063ef07
//! Content hash:   sha256:33e59ae450c9cad7b063ef07f3219f60be05687a7d7219cb278c56866d044d16
//! Source atom:    atom:code_test_body:114bc242a97c7491536117de
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_simple_specific_lang`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_simple_specific_lang(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_simple_specific_lang";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_simple_specific_lang",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:33e59ae450c9cad7b063ef07f3219f60be05687a7d7219cb278c56866d044d16",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:520fa2c8c6ba5ab888283d307e90be058dcb963581483eadfa565e3923f8ab71", "sha256:eede6b96550f60b17fc883cc48369fc948526a014a282f8db2d60c9679c01fb3"],
        });
    }
    let expected_body_hash = "sha256:eede6b96550f60b17fc883cc48369fc948526a014a282f8db2d60c9679c01fb3";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_simple_specific_lang",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:33e59ae450c9cad7b063ef07f3219f60be05687a7d7219cb278c56866d044d16",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:520fa2c8c6ba5ab888283d307e90be058dcb963581483eadfa565e3923f8ab71", "sha256:eede6b96550f60b17fc883cc48369fc948526a014a282f8db2d60c9679c01fb3"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_simple_specific_lang",
        "sha256:33e59ae450c9cad7b063ef07f3219f60be05687a7d7219cb278c56866d044d16",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:520fa2c8c6ba5ab888283d307e90be058dcb963581483eadfa565e3923f8ab71", "sha256:eede6b96550f60b17fc883cc48369fc948526a014a282f8db2d60c9679c01fb3"],
    )
}
