//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:e2a75322a1616ab370f961ec
//! Content hash:   sha256:e2a75322a1616ab370f961eceea42f30d74851611e741257c9c7dd4a31522c21
//! Source atom:    atom:code_member:b3fb619c9e232f438e504d12
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `property_keys`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_property_keys_e2a75322(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "property_keys";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_property_keys_e2a75322",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:e2a75322a1616ab370f961eceea42f30d74851611e741257c9c7dd4a31522c21",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_property_keys_e2a75322",
        "sha256:e2a75322a1616ab370f961eceea42f30d74851611e741257c9c7dd4a31522c21",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
