//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:2cceb99f859e5ada2cce0aac
//! Content hash:   sha256:2cceb99f859e5ada2cce0aacbeb2aec58b3808f24fa024641e7d8523450c0136
//! Source atom:    atom:code_test_body:7fdd4c72355adf3da3fe1b92
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_yaml_sgconfig_extension`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_yaml_sgconfig_extension(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_yaml_sgconfig_extension";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_yaml_sgconfig_extension",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:2cceb99f859e5ada2cce0aacbeb2aec58b3808f24fa024641e7d8523450c0136",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:985023eb2ac50f80ce9515baad2e51322d4b1ee2a5bdbd57e11737c122822a83"],
        });
    }
    let expected_body_hash = "sha256:985023eb2ac50f80ce9515baad2e51322d4b1ee2a5bdbd57e11737c122822a83";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_yaml_sgconfig_extension",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:2cceb99f859e5ada2cce0aacbeb2aec58b3808f24fa024641e7d8523450c0136",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:985023eb2ac50f80ce9515baad2e51322d4b1ee2a5bdbd57e11737c122822a83"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_yaml_sgconfig_extension",
        "sha256:2cceb99f859e5ada2cce0aacbeb2aec58b3808f24fa024641e7d8523450c0136",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:985023eb2ac50f80ce9515baad2e51322d4b1ee2a5bdbd57e11737c122822a83"],
    )
}
