//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:b0c5310ca94dee9fd79d931d
//! Content hash:   sha256:b0c5310ca94dee9fd79d931db72ab2f5f9a8b403f09ce7d839f8a6cd161f7a3f
//! Source atom:    atom:code_member:3ba44f7397752c973668f2b6
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `try_default_run`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_try_default_run(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "try_default_run";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_try_default_run",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:b0c5310ca94dee9fd79d931db72ab2f5f9a8b403f09ce7d839f8a6cd161f7a3f",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c8586c1c6bb4e79dc234d4e2d670d537fb7cdba12d5c84b6c05a087b766f0af9"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_try_default_run",
        "sha256:b0c5310ca94dee9fd79d931db72ab2f5f9a8b403f09ce7d839f8a6cd161f7a3f",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c8586c1c6bb4e79dc234d4e2d670d537fb7cdba12d5c84b6c05a087b766f0af9"],
    )
}
