//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:8311c96f6a7e508f39e0bc05
//! Content hash:   sha256:8311c96f6a7e508f39e0bc0547c8cdced7834932c55e5624ef856668c46ba47b
//! Source atom:    atom:code_member:bde5c9e2bc56fa8cc6595c93
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `pack_query_nodes`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_pack_query_nodes_8311c96f(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "pack_query_nodes";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_pack_query_nodes_8311c96f",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:8311c96f6a7e508f39e0bc0547c8cdced7834932c55e5624ef856668c46ba47b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_pack_query_nodes_8311c96f",
        "sha256:8311c96f6a7e508f39e0bc0547c8cdced7834932c55e5624ef856668c46ba47b",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
    )
}
