//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:855face5828ecbcf9856a29c
//! Content hash:   sha256:855face5828ecbcf9856a29c30e5a54dd01aa6002bebdb73cfb46e0cb958f596
//! Source atom:    atom:code_test_body:2053cfb46998a1b6fe71ed3b
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `redcore_reopens_persisted_binding`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_redcore_reopens_persisted_binding(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "redcore_reopens_persisted_binding";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_redcore_reopens_persisted_binding",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:855face5828ecbcf9856a29c30e5a54dd01aa6002bebdb73cfb46e0cb958f596",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:064db319ed4a71ebc58a9c6c70ba5631747805bc2be65a75307b30112597b1a7", "sha256:bc78004a9dd3cc53ff44b4cfce5dd1db7ada09422acc476d2571ec878da80eac"],
        });
    }
    let expected_body_hash = "sha256:bc78004a9dd3cc53ff44b4cfce5dd1db7ada09422acc476d2571ec878da80eac";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_redcore_reopens_persisted_binding",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:855face5828ecbcf9856a29c30e5a54dd01aa6002bebdb73cfb46e0cb958f596",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:064db319ed4a71ebc58a9c6c70ba5631747805bc2be65a75307b30112597b1a7", "sha256:bc78004a9dd3cc53ff44b4cfce5dd1db7ada09422acc476d2571ec878da80eac"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_redcore_reopens_persisted_binding",
        "sha256:855face5828ecbcf9856a29c30e5a54dd01aa6002bebdb73cfb46e0cb958f596",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:064db319ed4a71ebc58a9c6c70ba5631747805bc2be65a75307b30112597b1a7", "sha256:bc78004a9dd3cc53ff44b4cfce5dd1db7ada09422acc476d2571ec878da80eac"],
    )
}
