//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:5ad796580feed3e6e221d0c5
//! Content hash:   sha256:5ad796580feed3e6e221d0c509b268d9b84d181ee007645b0f272a31ea7928ee
//! Source atom:    atom:code_member:ce5d5e08a4c95b05c4196ca2
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `normalize_coordination_record_type`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_normalize_coordination_record_type(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "normalize_coordination_record_type";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_normalize_coordination_record_type",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:5ad796580feed3e6e221d0c509b268d9b84d181ee007645b0f272a31ea7928ee",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_normalize_coordination_record_type",
        "sha256:5ad796580feed3e6e221d0c509b268d9b84d181ee007645b0f272a31ea7928ee",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
