//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:a0c6e4f163e5e62eee56e127
//! Content hash:   sha256:a0c6e4f163e5e62eee56e12711da270cf64ce9150b6dac5586a5c0ad93aa0e5b
//! Source atom:    atom:code_member:3038091bcc9dcbb5b880997d
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `search_substrate`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_search_substrate(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "search_substrate";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_search_substrate",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:a0c6e4f163e5e62eee56e12711da270cf64ce9150b6dac5586a5c0ad93aa0e5b",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_search_substrate",
        "sha256:a0c6e4f163e5e62eee56e12711da270cf64ce9150b6dac5586a5c0ad93aa0e5b",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
    )
}
