//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:d0ad3e7684994f7c32e40f02
//! Content hash:   sha256:d0ad3e7684994f7c32e40f02fbef942cd6299f5461a94fb9da9a35b2bb426d30
//! Source atom:    atom:code_test_body:47afefbbd98cdd3c8e7555ef
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `theseus_app_affordance_invocations_record_receipts`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_theseus_app_affordance_invocations_record_receipts(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "theseus_app_affordance_invocations_record_receipts";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_theseus_app_affordance_invocations_record_receipts",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:d0ad3e7684994f7c32e40f02fbef942cd6299f5461a94fb9da9a35b2bb426d30",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:3669177d5e500b0af0cdb0ba36616b2d6481f82b561d3c558b95e6722bfc9f96", "sha256:8cc5b7804ecdbdae3f862aa4f7e98b4b156be44f720400f38de58fd085f36037"],
        });
    }
    let expected_body_hash = "sha256:8cc5b7804ecdbdae3f862aa4f7e98b4b156be44f720400f38de58fd085f36037";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_theseus_app_affordance_invocations_record_receipts",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:d0ad3e7684994f7c32e40f02fbef942cd6299f5461a94fb9da9a35b2bb426d30",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:3669177d5e500b0af0cdb0ba36616b2d6481f82b561d3c558b95e6722bfc9f96", "sha256:8cc5b7804ecdbdae3f862aa4f7e98b4b156be44f720400f38de58fd085f36037"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_theseus_app_affordance_invocations_record_receipts",
        "sha256:d0ad3e7684994f7c32e40f02fbef942cd6299f5461a94fb9da9a35b2bb426d30",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:3669177d5e500b0af0cdb0ba36616b2d6481f82b561d3c558b95e6722bfc9f96", "sha256:8cc5b7804ecdbdae3f862aa4f7e98b4b156be44f720400f38de58fd085f36037"],
    )
}
