//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:ca196c0e4a31558f69deb953
//! Content hash:   sha256:ca196c0e4a31558f69deb953592099afd66f637c6ed7696ed6f25cbc1a2b2397
//! Source atom:    atom:code_member:5f2c56a402c8b21fe2e973ff
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `upsert_edge`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_upsert_edge_ca196c0e(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "upsert_edge";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_upsert_edge_ca196c0e",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:ca196c0e4a31558f69deb953592099afd66f637c6ed7696ed6f25cbc1a2b2397",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_upsert_edge_ca196c0e",
        "sha256:ca196c0e4a31558f69deb953592099afd66f637c6ed7696ed6f25cbc1a2b2397",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
