//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:5856128feb5d24438a6b757f
//! Content hash:   sha256:5856128feb5d24438a6b757f3d9861ea828e29556d2c12712d65de5da084ba71
//! Source atom:    atom:code_member:fbdefceb36d029510995684f
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `algorithm_communities_inline_payload`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_algorithm_communities_inline_payload(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "algorithm_communities_inline_payload";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_algorithm_communities_inline_payload",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:5856128feb5d24438a6b757f3d9861ea828e29556d2c12712d65de5da084ba71",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_algorithm_communities_inline_payload",
        "sha256:5856128feb5d24438a6b757f3d9861ea828e29556d2c12712d65de5da084ba71",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
