//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:13fd035bcdb5de2d23d2d0f8
//! Content hash:   sha256:13fd035bcdb5de2d23d2d0f81f4b7bcc4b426e9140fe44c12804b47930f172bf
//! Source atom:    atom:code_test_body:a5f2c09860d3812d4813f1c8
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `redcore_persists_vector_designation_through_reopen`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_redcore_persists_vector_designation_through_reopen(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "redcore_persists_vector_designation_through_reopen";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_redcore_persists_vector_designation_through_reopen",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:13fd035bcdb5de2d23d2d0f81f4b7bcc4b426e9140fe44c12804b47930f172bf",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:374feea06719488f86400dd65524e0aa78c535a7ae52bd7c0790bf986d5bb2a4"],
        });
    }
    let expected_body_hash = "sha256:374feea06719488f86400dd65524e0aa78c535a7ae52bd7c0790bf986d5bb2a4";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_redcore_persists_vector_designation_through_reopen",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:13fd035bcdb5de2d23d2d0f81f4b7bcc4b426e9140fe44c12804b47930f172bf",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:374feea06719488f86400dd65524e0aa78c535a7ae52bd7c0790bf986d5bb2a4"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_redcore_persists_vector_designation_through_reopen",
        "sha256:13fd035bcdb5de2d23d2d0f81f4b7bcc4b426e9140fe44c12804b47930f172bf",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:374feea06719488f86400dd65524e0aa78c535a7ae52bd7c0790bf986d5bb2a4"],
    )
}
