//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:40f6b28972d413d8ad1ca73e
//! Content hash:   sha256:40f6b28972d413d8ad1ca73ed6b3983a84b87a435011b79066cc7018502f578e
//! Source atom:    atom:code_test_body:e1dd829f0feb0a9b26600a5b
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `relate_walks_memory_edges`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_relate_walks_memory_edges(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "relate_walks_memory_edges";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_relate_walks_memory_edges",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:40f6b28972d413d8ad1ca73ed6b3983a84b87a435011b79066cc7018502f578e",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c068a3ad3c6eeb3bcb8521ab44bc0cdbb9c7a770c6011a4079a4d3aab8f025fa", "sha256:ed3ef1435efcf9d8abb18f25a7fb13bcd82483fe26ac0656e5fa0e8384e67bea"],
        });
    }
    let expected_body_hash = "sha256:ed3ef1435efcf9d8abb18f25a7fb13bcd82483fe26ac0656e5fa0e8384e67bea";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_relate_walks_memory_edges",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:40f6b28972d413d8ad1ca73ed6b3983a84b87a435011b79066cc7018502f578e",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c068a3ad3c6eeb3bcb8521ab44bc0cdbb9c7a770c6011a4079a4d3aab8f025fa", "sha256:ed3ef1435efcf9d8abb18f25a7fb13bcd82483fe26ac0656e5fa0e8384e67bea"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_relate_walks_memory_edges",
        "sha256:40f6b28972d413d8ad1ca73ed6b3983a84b87a435011b79066cc7018502f578e",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c068a3ad3c6eeb3bcb8521ab44bc0cdbb9c7a770c6011a4079a4d3aab8f025fa", "sha256:ed3ef1435efcf9d8abb18f25a7fb13bcd82483fe26ac0656e5fa0e8384e67bea"],
    )
}
