//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:e44da45305c2a0a25034eb00
//! Content hash:   sha256:e44da45305c2a0a25034eb0019b8b4d1324a7cafdd9e98926f41ef4766bbd1d0
//! Source atom:    atom:code_member:d7d315ebc495f301223945e5
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `upsert_node`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_upsert_node_e44da453(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "upsert_node";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_upsert_node_e44da453",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:e44da45305c2a0a25034eb0019b8b4d1324a7cafdd9e98926f41ef4766bbd1d0",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:f3b00b3df4d2595831b3b2ee2ac79d62ad2d76ffdabbfe5e9f32aa1ced12c951"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_upsert_node_e44da453",
        "sha256:e44da45305c2a0a25034eb0019b8b4d1324a7cafdd9e98926f41ef4766bbd1d0",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:f3b00b3df4d2595831b3b2ee2ac79d62ad2d76ffdabbfe5e9f32aa1ced12c951"],
    )
}
