//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:31a09e502c495de81159d4d0
//! Content hash:   sha256:31a09e502c495de81159d4d0e9353cad9a237f69dce46bbdb1f4598385ce525f
//! Source atom:    atom:code_member:4e91dd1dfb0c1b03297ab448
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `labels`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_labels_31a09e50(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "labels";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_labels_31a09e50",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:31a09e502c495de81159d4d0e9353cad9a237f69dce46bbdb1f4598385ce525f",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_labels_31a09e50",
        "sha256:31a09e502c495de81159d4d0e9353cad9a237f69dce46bbdb1f4598385ce525f",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
