//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:ca2a395e91b78bd67adf519d
//! Content hash:   sha256:ca2a395e91b78bd67adf519dd425a6a30d6ed454ad5442fb93dea74d90162fbb
//! Source atom:    atom:code_member:9a5a68e1884073884c7c9e13
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `browser_session_can_fetch_open_web_page_and_ingest_it`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_browser_session_can_fetch_open_web_page_and_ingest_it(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "browser_session_can_fetch_open_web_page_and_ingest_it";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_browser_session_can_fetch_open_web_page_and_ingest_it",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:ca2a395e91b78bd67adf519dd425a6a30d6ed454ad5442fb93dea74d90162fbb",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_browser_session_can_fetch_open_web_page_and_ingest_it",
        "sha256:ca2a395e91b78bd67adf519dd425a6a30d6ed454ad5442fb93dea74d90162fbb",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
    )
}
