//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:2bea8bdd7e23f7b5c2cf7447
//! Content hash:   sha256:2bea8bdd7e23f7b5c2cf7447469372f9c3c273b8dd438c79432abe23399aee7c
//! Source atom:    atom:code_member:5fd445072ef9d5511945548c
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `validate_binding`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_validate_binding(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "validate_binding";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_validate_binding",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:2bea8bdd7e23f7b5c2cf7447469372f9c3c273b8dd438c79432abe23399aee7c",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_validate_binding",
        "sha256:2bea8bdd7e23f7b5c2cf7447469372f9c3c273b8dd438c79432abe23399aee7c",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
    )
}
