//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:8f98b9e0a082299861edfd1a
//! Content hash:   sha256:8f98b9e0a082299861edfd1ad9d80363daa979efb69946c2a9f7fdcd73f0c973
//! Source atom:    atom:code_test_body:a4577c0eee69fd3e73e049a4
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_fields_on_unit_struct`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_fields_on_unit_struct(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_fields_on_unit_struct";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_fields_on_unit_struct",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:8f98b9e0a082299861edfd1ad9d80363daa979efb69946c2a9f7fdcd73f0c973",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c8f5dbac6482dadd0fab30d0b1fe3254869256c48ea68ea484cad7f7406c8568", "sha256:8ff08aec49d759a45d6924007f6c9f0e73ec72bc29f898864b8cf6650d0300aa"],
        });
    }
    let expected_body_hash = "sha256:8ff08aec49d759a45d6924007f6c9f0e73ec72bc29f898864b8cf6650d0300aa";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_fields_on_unit_struct",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:8f98b9e0a082299861edfd1ad9d80363daa979efb69946c2a9f7fdcd73f0c973",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c8f5dbac6482dadd0fab30d0b1fe3254869256c48ea68ea484cad7f7406c8568", "sha256:8ff08aec49d759a45d6924007f6c9f0e73ec72bc29f898864b8cf6650d0300aa"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_fields_on_unit_struct",
        "sha256:8f98b9e0a082299861edfd1ad9d80363daa979efb69946c2a9f7fdcd73f0c973",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c8f5dbac6482dadd0fab30d0b1fe3254869256c48ea68ea484cad7f7406c8568", "sha256:8ff08aec49d759a45d6924007f6c9f0e73ec72bc29f898864b8cf6650d0300aa"],
    )
}
