//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:ddab0df00ac2cb141dd55fac
//! Content hash:   sha256:ddab0df00ac2cb141dd55fac32445b811ba6a6af5a486583d78c61d35b6665f4
//! Source atom:    atom:code_test_body:e25c8c7657fdaac05c33a10a
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `capability_scope_can_select_theseus_app_families`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_capability_scope_can_select_theseus_app_families(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "capability_scope_can_select_theseus_app_families";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_capability_scope_can_select_theseus_app_families",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:ddab0df00ac2cb141dd55fac32445b811ba6a6af5a486583d78c61d35b6665f4",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:460927bdfa22279f0b1bee69638c2c0319d8228a806f016a2844d67809566711", "sha256:c29a241c8a41038c1ce6c706de1449eff5d19e10a1e5d1a4f34bd902c3f22fec"],
        });
    }
    let expected_body_hash = "sha256:c29a241c8a41038c1ce6c706de1449eff5d19e10a1e5d1a4f34bd902c3f22fec";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_capability_scope_can_select_theseus_app_families",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:ddab0df00ac2cb141dd55fac32445b811ba6a6af5a486583d78c61d35b6665f4",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:460927bdfa22279f0b1bee69638c2c0319d8228a806f016a2844d67809566711", "sha256:c29a241c8a41038c1ce6c706de1449eff5d19e10a1e5d1a4f34bd902c3f22fec"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_capability_scope_can_select_theseus_app_families",
        "sha256:ddab0df00ac2cb141dd55fac32445b811ba6a6af5a486583d78c61d35b6665f4",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:460927bdfa22279f0b1bee69638c2c0319d8228a806f016a2844d67809566711", "sha256:c29a241c8a41038c1ce6c706de1449eff5d19e10a1e5d1a4f34bd902c3f22fec"],
    )
}
