//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:a1572faf832fbaed3fa733de
//! Content hash:   sha256:a1572faf832fbaed3fa733de1b26613d9f7cd5b4b9676057c39e929e7a02896c
//! Source atom:    atom:code_test_body:01d1d3399061a9c351cebf3b
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_commit_hunks_multiple_files`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_commit_hunks_multiple_files(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_commit_hunks_multiple_files";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_commit_hunks_multiple_files",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:a1572faf832fbaed3fa733de1b26613d9f7cd5b4b9676057c39e929e7a02896c",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4c6c2c52b32361a4f7b48b9fc00dade2972c7d07c14e33005d3dc251a4a30982", "sha256:be6dd11e0c4358581d7d29e87727b627509cfbbd8bbf5fb9a3af932b425a9db6"],
        });
    }
    let expected_body_hash = "sha256:be6dd11e0c4358581d7d29e87727b627509cfbbd8bbf5fb9a3af932b425a9db6";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_commit_hunks_multiple_files",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:a1572faf832fbaed3fa733de1b26613d9f7cd5b4b9676057c39e929e7a02896c",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4c6c2c52b32361a4f7b48b9fc00dade2972c7d07c14e33005d3dc251a4a30982", "sha256:be6dd11e0c4358581d7d29e87727b627509cfbbd8bbf5fb9a3af932b425a9db6"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_commit_hunks_multiple_files",
        "sha256:a1572faf832fbaed3fa733de1b26613d9f7cd5b4b9676057c39e929e7a02896c",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4c6c2c52b32361a4f7b48b9fc00dade2972c7d07c14e33005d3dc251a4a30982", "sha256:be6dd11e0c4358581d7d29e87727b627509cfbbd8bbf5fb9a3af932b425a9db6"],
    )
}
