//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:4daafcb1c7c901d99fad52ff
//! Content hash:   sha256:4daafcb1c7c901d99fad52ffeefaf70d74970991c6f5c2f64c2ef3036c3f4c8b
//! Source atom:    atom:code_member:394bdde290f9ee007cf0fc42
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `get_node`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_get_node_4daafcb1(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "get_node";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_get_node_4daafcb1",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:4daafcb1c7c901d99fad52ffeefaf70d74970991c6f5c2f64c2ef3036c3f4c8b",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_get_node_4daafcb1",
        "sha256:4daafcb1c7c901d99fad52ffeefaf70d74970991c6f5c2f64c2ef3036c3f4c8b",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
