//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:52d834241c30ef3d47317633
//! Content hash:   sha256:52d834241c30ef3d473176331b2afe6b2c76eecf37bc9ebdee4229c017170fa6
//! Source atom:    atom:code_test_body:010b0aee3a67067107850017
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_graphite_style_multi_commit_single_update_ref`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_graphite_style_multi_commit_single_update_ref(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_graphite_style_multi_commit_single_update_ref";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_graphite_style_multi_commit_single_update_ref",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:52d834241c30ef3d473176331b2afe6b2c76eecf37bc9ebdee4229c017170fa6",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:f039f7c363724edaca627846d718dc11de796deb7f09d980e270758e87ce1f69", "sha256:a2ab0f3d27595a402baee8d6bf3df26c69e308650a662e956aeb369409509d5a"],
        });
    }
    let expected_body_hash = "sha256:a2ab0f3d27595a402baee8d6bf3df26c69e308650a662e956aeb369409509d5a";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_graphite_style_multi_commit_single_update_ref",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:52d834241c30ef3d473176331b2afe6b2c76eecf37bc9ebdee4229c017170fa6",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:f039f7c363724edaca627846d718dc11de796deb7f09d980e270758e87ce1f69", "sha256:a2ab0f3d27595a402baee8d6bf3df26c69e308650a662e956aeb369409509d5a"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_graphite_style_multi_commit_single_update_ref",
        "sha256:52d834241c30ef3d473176331b2afe6b2c76eecf37bc9ebdee4229c017170fa6",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:f039f7c363724edaca627846d718dc11de796deb7f09d980e270758e87ce1f69", "sha256:a2ab0f3d27595a402baee8d6bf3df26c69e308650a662e956aeb369409509d5a"],
    )
}
