//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:339575ffb11bfa8aa46b2766
//! Content hash:   sha256:339575ffb11bfa8aa46b2766024c392a92cf6a6b3501a01a61aa8405758fbfad
//! Source atom:    atom:code_member:302683b71f6658b2cc82c457
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `snapshot`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_snapshot(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "snapshot";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_snapshot",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:339575ffb11bfa8aa46b2766024c392a92cf6a6b3501a01a61aa8405758fbfad",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_snapshot",
        "sha256:339575ffb11bfa8aa46b2766024c392a92cf6a6b3501a01a61aa8405758fbfad",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
