//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:116bc0adefcc6832aeb977dd
//! Content hash:   sha256:116bc0adefcc6832aeb977dd4a4bbcc2d396b7f9ed2a9298ae05365a497f218b
//! Source atom:    atom:code_test_body:6609fdd264c81c2c20deeb71
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `algorithm_ppr_tenant_backed_response_shape_unchanged`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_algorithm_ppr_tenant_backed_response_shape_unchanged(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "algorithm_ppr_tenant_backed_response_shape_unchanged";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_algorithm_ppr_tenant_backed_response_shape_unchanged",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:116bc0adefcc6832aeb977dd4a4bbcc2d396b7f9ed2a9298ae05365a497f218b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba", "sha256:f2546e2fbee571812cf4b350425e211d62b8f8c9768fdf333deeba01e51dd68e"],
        });
    }
    let expected_body_hash = "sha256:f2546e2fbee571812cf4b350425e211d62b8f8c9768fdf333deeba01e51dd68e";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_algorithm_ppr_tenant_backed_response_shape_unchanged",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:116bc0adefcc6832aeb977dd4a4bbcc2d396b7f9ed2a9298ae05365a497f218b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba", "sha256:f2546e2fbee571812cf4b350425e211d62b8f8c9768fdf333deeba01e51dd68e"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_algorithm_ppr_tenant_backed_response_shape_unchanged",
        "sha256:116bc0adefcc6832aeb977dd4a4bbcc2d396b7f9ed2a9298ae05365a497f218b",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba", "sha256:f2546e2fbee571812cf4b350425e211d62b8f8c9768fdf333deeba01e51dd68e"],
    )
}
