//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:cf4a5d361789ea5af66fda55
//! Content hash:   sha256:cf4a5d361789ea5af66fda55e316e7459d2879251066772dffacabf9a84e10f3
//! Source atom:    atom:code_test_body:1032e29ccc98b59b68a7b54f
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `charter_enumerates_all_builtin_reasoning_affordances`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_charter_enumerates_all_builtin_reasoning_affordances(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "charter_enumerates_all_builtin_reasoning_affordances";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_charter_enumerates_all_builtin_reasoning_affordances",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:cf4a5d361789ea5af66fda55e316e7459d2879251066772dffacabf9a84e10f3",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:4617d80776d50b49a4b9fa94b5970e7c808b10bda3c2a319c282afabc31eea12", "sha256:aae8ab193fb282d26c2bb67d77580fcb1f7e6880992ab6da1111dd7cf80c7050"],
        });
    }
    let expected_body_hash = "sha256:aae8ab193fb282d26c2bb67d77580fcb1f7e6880992ab6da1111dd7cf80c7050";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_charter_enumerates_all_builtin_reasoning_affordances",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:cf4a5d361789ea5af66fda55e316e7459d2879251066772dffacabf9a84e10f3",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:4617d80776d50b49a4b9fa94b5970e7c808b10bda3c2a319c282afabc31eea12", "sha256:aae8ab193fb282d26c2bb67d77580fcb1f7e6880992ab6da1111dd7cf80c7050"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_charter_enumerates_all_builtin_reasoning_affordances",
        "sha256:cf4a5d361789ea5af66fda55e316e7459d2879251066772dffacabf9a84e10f3",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:4617d80776d50b49a4b9fa94b5970e7c808b10bda3c2a319c282afabc31eea12", "sha256:aae8ab193fb282d26c2bb67d77580fcb1f7e6880992ab6da1111dd7cf80c7050"],
    )
}
