//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:19afc55c3b0b39ee3be2673b
//! Content hash:   sha256:19afc55c3b0b39ee3be2673b9e38374c7319ad3004e2d8736ae6040f612fdce5
//! Source atom:    atom:code_member:fb822b67e8d5189f4b2fc454
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `vector_designations`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_vector_designations(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "vector_designations";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_vector_designations",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:19afc55c3b0b39ee3be2673b9e38374c7319ad3004e2d8736ae6040f612fdce5",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_vector_designations",
        "sha256:19afc55c3b0b39ee3be2673b9e38374c7319ad3004e2d8736ae6040f612fdce5",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
