//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:d1be02d1aef357c686f4015b
//! Content hash:   sha256:d1be02d1aef357c686f4015bb0a2b2dbc09c6a6916d863fe85e4a5ff98f30a51
//! Source atom:    atom:code_member:4816d36b98f5d2157d596526
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `hash_agent_binding`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_hash_agent_binding(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "hash_agent_binding";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_hash_agent_binding",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:d1be02d1aef357c686f4015bb0a2b2dbc09c6a6916d863fe85e4a5ff98f30a51",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_hash_agent_binding",
        "sha256:d1be02d1aef357c686f4015bb0a2b2dbc09c6a6916d863fe85e4a5ff98f30a51",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
    )
}
