//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:bf37ca2b6af8d7e93bd9f3c7
//! Content hash:   sha256:bf37ca2b6af8d7e93bd9f3c70ea9fb915a41cd170734b50042cb7d3c3859ee03
//! Source atom:    atom:code_member:067ba2a5a773503814ec637e
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `apply_recovered_node`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_apply_recovered_node(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "apply_recovered_node";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_apply_recovered_node",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:bf37ca2b6af8d7e93bd9f3c70ea9fb915a41cd170734b50042cb7d3c3859ee03",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_apply_recovered_node",
        "sha256:bf37ca2b6af8d7e93bd9f3c70ea9fb915a41cd170734b50042cb7d3c3859ee03",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
