//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:532f54c7e0df8b649d92b332
//! Content hash:   sha256:532f54c7e0df8b649d92b332b381f8917bb4c67407741cfadd5f295ce7be6321
//! Source atom:    atom:code_test_body:3c64d698566f650f0f0109fe
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `detects_duplicate_end`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_detects_duplicate_end(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "detects_duplicate_end";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_detects_duplicate_end",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:532f54c7e0df8b649d92b332b381f8917bb4c67407741cfadd5f295ce7be6321",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:57cf6ed52bbab967a400e4a13937f53fd61255d91d838433b4801f5938f3d471", "sha256:bfadeb3a4f6ce07fda53d54267e6caac843f14eef20c5a6bd033c87b56555715"],
        });
    }
    let expected_body_hash = "sha256:bfadeb3a4f6ce07fda53d54267e6caac843f14eef20c5a6bd033c87b56555715";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_detects_duplicate_end",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:532f54c7e0df8b649d92b332b381f8917bb4c67407741cfadd5f295ce7be6321",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:57cf6ed52bbab967a400e4a13937f53fd61255d91d838433b4801f5938f3d471", "sha256:bfadeb3a4f6ce07fda53d54267e6caac843f14eef20c5a6bd033c87b56555715"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_detects_duplicate_end",
        "sha256:532f54c7e0df8b649d92b332b381f8917bb4c67407741cfadd5f295ce7be6321",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:57cf6ed52bbab967a400e4a13937f53fd61255d91d838433b4801f5938f3d471", "sha256:bfadeb3a4f6ce07fda53d54267e6caac843f14eef20c5a6bd033c87b56555715"],
    )
}
