//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:435063a88d057ccc6cedfcbe
//! Content hash:   sha256:435063a88d057ccc6cedfcbeda924cceb23a80fb6ed224e5e7ba98ae43469ad6
//! Source atom:    atom:code_member:29b0a782bb436a27f4756515
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `verify`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_verify_435063a8(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "verify";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_verify_435063a8",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:435063a88d057ccc6cedfcbeda924cceb23a80fb6ed224e5e7ba98ae43469ad6",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_verify_435063a8",
        "sha256:435063a88d057ccc6cedfcbeda924cceb23a80fb6ed224e5e7ba98ae43469ad6",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
