//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:53b420cfe0eb33200452026a
//! Content hash:   sha256:53b420cfe0eb33200452026a8f980188488f6ca9cf31ff65c03aaa8cc4efee3e
//! Source atom:    atom:code_member:4f3e5c930e43f2b8323adef4
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `should_snapshot_for`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_should_snapshot_for(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "should_snapshot_for";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_should_snapshot_for",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:53b420cfe0eb33200452026a8f980188488f6ca9cf31ff65c03aaa8cc4efee3e",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_should_snapshot_for",
        "sha256:53b420cfe0eb33200452026a8f980188488f6ca9cf31ff65c03aaa8cc4efee3e",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
