//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:840feb992c65e6e07617a684
//! Content hash:   sha256:840feb992c65e6e07617a68482731e8163f8c9563b5288df36ca97acbc4c703b
//! Source atom:    atom:code_test_body:51f7372c4df7924c507ec966
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_outer_attr`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_outer_attr(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_outer_attr";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_outer_attr",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:840feb992c65e6e07617a68482731e8163f8c9563b5288df36ca97acbc4c703b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:023d6b57ba5ba199a04d9757e3b1464c2bc09579b035ea82c047e08d89d19226", "sha256:82c1dbd46c7d8d3eaf493d2a0b5d23efec500656003f51004f0415349a2aae83"],
        });
    }
    let expected_body_hash = "sha256:82c1dbd46c7d8d3eaf493d2a0b5d23efec500656003f51004f0415349a2aae83";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_outer_attr",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:840feb992c65e6e07617a68482731e8163f8c9563b5288df36ca97acbc4c703b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:023d6b57ba5ba199a04d9757e3b1464c2bc09579b035ea82c047e08d89d19226", "sha256:82c1dbd46c7d8d3eaf493d2a0b5d23efec500656003f51004f0415349a2aae83"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_outer_attr",
        "sha256:840feb992c65e6e07617a68482731e8163f8c9563b5288df36ca97acbc4c703b",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:023d6b57ba5ba199a04d9757e3b1464c2bc09579b035ea82c047e08d89d19226", "sha256:82c1dbd46c7d8d3eaf493d2a0b5d23efec500656003f51004f0415349a2aae83"],
    )
}
