//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:447fb98042eaa1e36838352b
//! Content hash:   sha256:447fb98042eaa1e36838352b8e60bc98e96a0189368a4f8aab1a64db5398778a
//! Source atom:    atom:code_test_body:cd566321f1a8eca2d0ec4f92
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `tools_list_exposes_read_only_graph_tools`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_tools_list_exposes_read_only_graph_tools(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "tools_list_exposes_read_only_graph_tools";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_tools_list_exposes_read_only_graph_tools",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:447fb98042eaa1e36838352b8e60bc98e96a0189368a4f8aab1a64db5398778a",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f", "sha256:f11a7927808652a29c36cf13c40c313cd688faa2dcc661472b76f11e22b2caa7"],
        });
    }
    let expected_body_hash = "sha256:f11a7927808652a29c36cf13c40c313cd688faa2dcc661472b76f11e22b2caa7";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_tools_list_exposes_read_only_graph_tools",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:447fb98042eaa1e36838352b8e60bc98e96a0189368a4f8aab1a64db5398778a",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f", "sha256:f11a7927808652a29c36cf13c40c313cd688faa2dcc661472b76f11e22b2caa7"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_tools_list_exposes_read_only_graph_tools",
        "sha256:447fb98042eaa1e36838352b8e60bc98e96a0189368a4f8aab1a64db5398778a",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f", "sha256:f11a7927808652a29c36cf13c40c313cd688faa2dcc661472b76f11e22b2caa7"],
    )
}
