//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:efe48e9b599e79db12f37228
//! Content hash:   sha256:efe48e9b599e79db12f3722809839030c31217f1b81de009a5b4e30aeec0171f
//! Source atom:    atom:code_member:0174ef8a1b82e61affdd06ac
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `upsert_edge`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_upsert_edge_efe48e9b(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "upsert_edge";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_upsert_edge_efe48e9b",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:efe48e9b599e79db12f3722809839030c31217f1b81de009a5b4e30aeec0171f",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:f3b00b3df4d2595831b3b2ee2ac79d62ad2d76ffdabbfe5e9f32aa1ced12c951"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_upsert_edge_efe48e9b",
        "sha256:efe48e9b599e79db12f3722809839030c31217f1b81de009a5b4e30aeec0171f",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:f3b00b3df4d2595831b3b2ee2ac79d62ad2d76ffdabbfe5e9f32aa1ced12c951"],
    )
}
