//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:4c9b5bdb2d721d36d2f29a99
//! Content hash:   sha256:4c9b5bdb2d721d36d2f29a9998aa8258a116048c1c923addab0c2897997ec307
//! Source atom:    atom:code_test_body:ecd45f4e64e817ac2efe5980
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `encode_engine_slice_error_when_buffer_too_small`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_encode_engine_slice_error_when_buffer_too_small(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "encode_engine_slice_error_when_buffer_too_small";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_encode_engine_slice_error_when_buffer_too_small",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:4c9b5bdb2d721d36d2f29a9998aa8258a116048c1c923addab0c2897997ec307",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:78efcf0dc4bb6ae52f7a91fcad89e44e4dce578224c36b4e6c1c306459be8500", "sha256:a370f7c1c5e3dd48c8903eae1ad9a79578895762b117169b7dbdc59e95fef839"],
        });
    }
    let expected_body_hash = "sha256:a370f7c1c5e3dd48c8903eae1ad9a79578895762b117169b7dbdc59e95fef839";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_encode_engine_slice_error_when_buffer_too_small",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:4c9b5bdb2d721d36d2f29a9998aa8258a116048c1c923addab0c2897997ec307",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:78efcf0dc4bb6ae52f7a91fcad89e44e4dce578224c36b4e6c1c306459be8500", "sha256:a370f7c1c5e3dd48c8903eae1ad9a79578895762b117169b7dbdc59e95fef839"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_encode_engine_slice_error_when_buffer_too_small",
        "sha256:4c9b5bdb2d721d36d2f29a9998aa8258a116048c1c923addab0c2897997ec307",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:78efcf0dc4bb6ae52f7a91fcad89e44e4dce578224c36b4e6c1c306459be8500", "sha256:a370f7c1c5e3dd48c8903eae1ad9a79578895762b117169b7dbdc59e95fef839"],
    )
}
