//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:e5a0fd29596d9b531ef2b6fc
//! Content hash:   sha256:e5a0fd29596d9b531ef2b6fca58cb654e9a863b74c723e86c41fc61977d1c298
//! Source atom:    atom:code_test_body:1d58223cac0655c0e6541c68
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_reset_keep_rewrite_preserves_authorship_notes_on_current_branch`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_reset_keep_rewrite_preserves_authorship_notes_on_current_branch(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_reset_keep_rewrite_preserves_authorship_notes_on_current_branch";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_reset_keep_rewrite_preserves_authorship_notes_on_current_branch",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:e5a0fd29596d9b531ef2b6fca58cb654e9a863b74c723e86c41fc61977d1c298",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:f039f7c363724edaca627846d718dc11de796deb7f09d980e270758e87ce1f69", "sha256:13539f8df57843eea7c6be011e77caf56233e04d5a3612739bd386e9a95e9f53"],
        });
    }
    let expected_body_hash = "sha256:13539f8df57843eea7c6be011e77caf56233e04d5a3612739bd386e9a95e9f53";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_reset_keep_rewrite_preserves_authorship_notes_on_current_branch",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:e5a0fd29596d9b531ef2b6fca58cb654e9a863b74c723e86c41fc61977d1c298",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:f039f7c363724edaca627846d718dc11de796deb7f09d980e270758e87ce1f69", "sha256:13539f8df57843eea7c6be011e77caf56233e04d5a3612739bd386e9a95e9f53"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_reset_keep_rewrite_preserves_authorship_notes_on_current_branch",
        "sha256:e5a0fd29596d9b531ef2b6fca58cb654e9a863b74c723e86c41fc61977d1c298",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:f039f7c363724edaca627846d718dc11de796deb7f09d980e270758e87ce1f69", "sha256:13539f8df57843eea7c6be011e77caf56233e04d5a3612739bd386e9a95e9f53"],
    )
}
