//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:a768aff03e35c21de646bd25
//! Content hash:   sha256:a768aff03e35c21de646bd252c7f239b1d7eb602bb56282f9d905a06da2b3649
//! Source atom:    atom:code_member:246450892df2f07ee00359ad
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `preserve_previous_snapshot`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_preserve_previous_snapshot(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "preserve_previous_snapshot";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_preserve_previous_snapshot",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:a768aff03e35c21de646bd252c7f239b1d7eb602bb56282f9d905a06da2b3649",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_preserve_previous_snapshot",
        "sha256:a768aff03e35c21de646bd252c7f239b1d7eb602bb56282f9d905a06da2b3649",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
