//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:431f8c8fc0050e8b7bcee5d4
//! Content hash:   sha256:431f8c8fc0050e8b7bcee5d407c76df28c3e28d1d76e6f50f54e4a32f85fd19b
//! Source atom:    atom:code_test_body:b488f6775bf550d2f9b3ff96
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_meta_item_bool_value`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_meta_item_bool_value(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_meta_item_bool_value";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_meta_item_bool_value",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:431f8c8fc0050e8b7bcee5d407c76df28c3e28d1d76e6f50f54e4a32f85fd19b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:8a4429b7cfe2360bb73beae54a62ae3255ebbd5181467a8608d6f858c2711728", "sha256:b6b10d065cd1126c28ee17d2d683a68ef4832fa073ea7f59692d061a8ea24dd7"],
        });
    }
    let expected_body_hash = "sha256:b6b10d065cd1126c28ee17d2d683a68ef4832fa073ea7f59692d061a8ea24dd7";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_meta_item_bool_value",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:431f8c8fc0050e8b7bcee5d407c76df28c3e28d1d76e6f50f54e4a32f85fd19b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:8a4429b7cfe2360bb73beae54a62ae3255ebbd5181467a8608d6f858c2711728", "sha256:b6b10d065cd1126c28ee17d2d683a68ef4832fa073ea7f59692d061a8ea24dd7"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_meta_item_bool_value",
        "sha256:431f8c8fc0050e8b7bcee5d407c76df28c3e28d1d76e6f50f54e4a32f85fd19b",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:8a4429b7cfe2360bb73beae54a62ae3255ebbd5181467a8608d6f858c2711728", "sha256:b6b10d065cd1126c28ee17d2d683a68ef4832fa073ea7f59692d061a8ea24dd7"],
    )
}
