//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:a3e00a4d01f9133b497b0571
//! Content hash:   sha256:a3e00a4d01f9133b497b0571727e761a73f276811a27b95c349236acb170bef8
//! Source atom:    atom:code_member:5ed5ddfcbd2b7cce695bf927
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `parse_f32_array`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_parse_f32_array(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "parse_f32_array";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_parse_f32_array",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:a3e00a4d01f9133b497b0571727e761a73f276811a27b95c349236acb170bef8",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_parse_f32_array",
        "sha256:a3e00a4d01f9133b497b0571727e761a73f276811a27b95c349236acb170bef8",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
