//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:d948cc927dcbee0da639284e
//! Content hash:   sha256:d948cc927dcbee0da639284e2d36032f1d6c2c01af77b51ecb171a86e0a6592c
//! Source atom:    atom:code_test_body:86f4308de48e4ed1661f139a
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_scan_multi_rule_file_with_explicit_ids`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_scan_multi_rule_file_with_explicit_ids(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_scan_multi_rule_file_with_explicit_ids";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_scan_multi_rule_file_with_explicit_ids",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:d948cc927dcbee0da639284e2d36032f1d6c2c01af77b51ecb171a86e0a6592c",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:f2c66ff1de41c2821e274c68d3f45f26788b3317a0d95ad0f1230aa071f92536"],
        });
    }
    let expected_body_hash = "sha256:f2c66ff1de41c2821e274c68d3f45f26788b3317a0d95ad0f1230aa071f92536";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_scan_multi_rule_file_with_explicit_ids",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:d948cc927dcbee0da639284e2d36032f1d6c2c01af77b51ecb171a86e0a6592c",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:f2c66ff1de41c2821e274c68d3f45f26788b3317a0d95ad0f1230aa071f92536"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_scan_multi_rule_file_with_explicit_ids",
        "sha256:d948cc927dcbee0da639284e2d36032f1d6c2c01af77b51ecb171a86e0a6592c",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:f2c66ff1de41c2821e274c68d3f45f26788b3317a0d95ad0f1230aa071f92536"],
    )
}
