//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:48747b977a4bad4236d42826
//! Content hash:   sha256:48747b977a4bad4236d428262dc282a2362c8a71e12d053a9ccadf562db0abce
//! Source atom:    atom:code_member:e3a25fe6db5c9a1c23cae404
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `index_status_payload`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_index_status_payload(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "index_status_payload";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_index_status_payload",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:48747b977a4bad4236d428262dc282a2362c8a71e12d053a9ccadf562db0abce",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_index_status_payload",
        "sha256:48747b977a4bad4236d428262dc282a2362c8a71e12d053a9ccadf562db0abce",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
