//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:7ee128a1ba897ff643f47c42
//! Content hash:   sha256:7ee128a1ba897ff643f47c42078c913e0f4866127ef199cf2e23e2e5df739186
//! Source atom:    atom:code_test_body:97c8fdb9664e9031af4eabc5
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `redis_keyspace_normalizes_tenants_and_encodes_dynamic_key_segments`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_redis_keyspace_normalizes_tenants_and_encodes_dynamic_key_segments(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "redis_keyspace_normalizes_tenants_and_encodes_dynamic_key_segments";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_redis_keyspace_normalizes_tenants_and_encodes_dynamic_key_segments",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:7ee128a1ba897ff643f47c42078c913e0f4866127ef199cf2e23e2e5df739186",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:0f97e0ac608b2179b01c8d05e7b2d0ebff7e4d07dcc90a723f9518c212a81f99"],
        });
    }
    let expected_body_hash = "sha256:0f97e0ac608b2179b01c8d05e7b2d0ebff7e4d07dcc90a723f9518c212a81f99";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_redis_keyspace_normalizes_tenants_and_encodes_dynamic_key_segments",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:7ee128a1ba897ff643f47c42078c913e0f4866127ef199cf2e23e2e5df739186",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:0f97e0ac608b2179b01c8d05e7b2d0ebff7e4d07dcc90a723f9518c212a81f99"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_redis_keyspace_normalizes_tenants_and_encodes_dynamic_key_segments",
        "sha256:7ee128a1ba897ff643f47c42078c913e0f4866127ef199cf2e23e2e5df739186",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:0f97e0ac608b2179b01c8d05e7b2d0ebff7e4d07dcc90a723f9518c212a81f99"],
    )
}
