//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:da272ed5d107845b627167ec
//! Content hash:   sha256:da272ed5d107845b627167ecbe54c363df19b204e40b27b9d64e0b3920fa6855
//! Source atom:    atom:code_member:047a3c7d182fce296038acb9
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `embedding_from_properties`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_embedding_from_properties(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "embedding_from_properties";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_embedding_from_properties",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:da272ed5d107845b627167ecbe54c363df19b204e40b27b9d64e0b3920fa6855",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:f3b00b3df4d2595831b3b2ee2ac79d62ad2d76ffdabbfe5e9f32aa1ced12c951"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_embedding_from_properties",
        "sha256:da272ed5d107845b627167ecbe54c363df19b204e40b27b9d64e0b3920fa6855",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:f3b00b3df4d2595831b3b2ee2ac79d62ad2d76ffdabbfe5e9f32aa1ced12c951"],
    )
}
