//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:f19df6d0a62cfa30a55d579a
//! Content hash:   sha256:f19df6d0a62cfa30a55d579aeef7c81e88ff88956edbf19c5cf7c6bff31c06b2
//! Source atom:    atom:code_member:01277489a701db861c7ef999
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `neighbors`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_neighbors_f19df6d0(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "neighbors";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_neighbors_f19df6d0",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:f19df6d0a62cfa30a55d579aeef7c81e88ff88956edbf19c5cf7c6bff31c06b2",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_neighbors_f19df6d0",
        "sha256:f19df6d0a62cfa30a55d579aeef7c81e88ff88956edbf19c5cf7c6bff31c06b2",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
