//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:7a46b75fdf44b622edc2a913
//! Content hash:   sha256:7a46b75fdf44b622edc2a913689a60253729309683b9c33b4a3b8414e26a6a7b
//! Source atom:    atom:code_member:817dd467953469919b046ac5
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `upsert_edge`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_upsert_edge_7a46b75f(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "upsert_edge";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_upsert_edge_7a46b75f",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:7a46b75fdf44b622edc2a913689a60253729309683b9c33b4a3b8414e26a6a7b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_upsert_edge_7a46b75f",
        "sha256:7a46b75fdf44b622edc2a913689a60253729309683b9c33b4a3b8414e26a6a7b",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
