//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:e6781d55cfcb8a593757ae65
//! Content hash:   sha256:e6781d55cfcb8a593757ae652705361380aa5ddaa5ca9f96b2567eebee907f5a
//! Source atom:    atom:code_test_body:bbd1277f9c3ccb9b82bf71e6
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `apply_skill_pack_runs_native_code_member_artifact_validator`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_apply_skill_pack_runs_native_code_member_artifact_validator(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "apply_skill_pack_runs_native_code_member_artifact_validator";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_apply_skill_pack_runs_native_code_member_artifact_validator",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:e6781d55cfcb8a593757ae652705361380aa5ddaa5ca9f96b2567eebee907f5a",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a", "sha256:efb4feb58b858040b0d0aaa96a55aed947068fa2e50ce85fe035db6041401a4b"],
        });
    }
    let expected_body_hash = "sha256:efb4feb58b858040b0d0aaa96a55aed947068fa2e50ce85fe035db6041401a4b";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_apply_skill_pack_runs_native_code_member_artifact_validator",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:e6781d55cfcb8a593757ae652705361380aa5ddaa5ca9f96b2567eebee907f5a",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a", "sha256:efb4feb58b858040b0d0aaa96a55aed947068fa2e50ce85fe035db6041401a4b"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_apply_skill_pack_runs_native_code_member_artifact_validator",
        "sha256:e6781d55cfcb8a593757ae652705361380aa5ddaa5ca9f96b2567eebee907f5a",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a", "sha256:efb4feb58b858040b0d0aaa96a55aed947068fa2e50ce85fe035db6041401a4b"],
    )
}
