//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:ab4cdb14675c9fc49961cf3c
//! Content hash:   sha256:ab4cdb14675c9fc49961cf3c4b732b1cdbe2852d51997597a09d7763aa85896e
//! Source atom:    atom:code_test_body:5ea93c138e3d47576223ede2
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `select_from_store_gathers_then_selects`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_select_from_store_gathers_then_selects(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "select_from_store_gathers_then_selects";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_select_from_store_gathers_then_selects",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:ab4cdb14675c9fc49961cf3c4b732b1cdbe2852d51997597a09d7763aa85896e",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:4b153355a0f20ec3efa2052db88524e7422fec4061f1c7ab4e85e5588a19dbec", "sha256:1e8e1c6cdca83f083e932b6f85814a343324cb95d3087b5fcf5f2868edbb777c"],
        });
    }
    let expected_body_hash = "sha256:1e8e1c6cdca83f083e932b6f85814a343324cb95d3087b5fcf5f2868edbb777c";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_select_from_store_gathers_then_selects",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:ab4cdb14675c9fc49961cf3c4b732b1cdbe2852d51997597a09d7763aa85896e",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:4b153355a0f20ec3efa2052db88524e7422fec4061f1c7ab4e85e5588a19dbec", "sha256:1e8e1c6cdca83f083e932b6f85814a343324cb95d3087b5fcf5f2868edbb777c"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_select_from_store_gathers_then_selects",
        "sha256:ab4cdb14675c9fc49961cf3c4b732b1cdbe2852d51997597a09d7763aa85896e",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:4b153355a0f20ec3efa2052db88524e7422fec4061f1c7ab4e85e5588a19dbec", "sha256:1e8e1c6cdca83f083e932b6f85814a343324cb95d3087b5fcf5f2868edbb777c"],
    )
}
