//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:2645b521c6aa0d9c47a63cd0
//! Content hash:   sha256:2645b521c6aa0d9c47a63cd0ca9c3b4682579bb6d17bd6e1414d2973b4ba1fe5
//! Source atom:    atom:code_member:20aa232c9c639b14d6d86cd5
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `vector_designations`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_vector_designations_2645b521(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "vector_designations";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_vector_designations_2645b521",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:2645b521c6aa0d9c47a63cd0ca9c3b4682579bb6d17bd6e1414d2973b4ba1fe5",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_vector_designations_2645b521",
        "sha256:2645b521c6aa0d9c47a63cd0ca9c3b4682579bb6d17bd6e1414d2973b4ba1fe5",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
