//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:01a1a279f8800670aa1b5c1d
//! Content hash:   sha256:01a1a279f8800670aa1b5c1da999c1e8e78ea896b524f6a2788ec73d998e6dd2
//! Source atom:    atom:code_member:2a41393a99b1356d3155ffe3
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `fmt`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_fmt(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "fmt";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_fmt",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:01a1a279f8800670aa1b5c1da999c1e8e78ea896b524f6a2788ec73d998e6dd2",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_fmt",
        "sha256:01a1a279f8800670aa1b5c1da999c1e8e78ea896b524f6a2788ec73d998e6dd2",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
