//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:d2c7485310168a8315c973d4
//! Content hash:   sha256:d2c7485310168a8315c973d4abc6e7257c638f458d1566b5e36f93a9846cfc7b
//! Source atom:    atom:code_member:488811ad15420646c752f5cb
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `resolved_coordination_room_id`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_resolved_coordination_room_id(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "resolved_coordination_room_id";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_resolved_coordination_room_id",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:d2c7485310168a8315c973d4abc6e7257c638f458d1566b5e36f93a9846cfc7b",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_resolved_coordination_room_id",
        "sha256:d2c7485310168a8315c973d4abc6e7257c638f458d1566b5e36f93a9846cfc7b",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
