//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:36073abba277df2679e69740
//! Content hash:   sha256:36073abba277df2679e69740cfe639b34a25b64ff223bd3913bcddebc6e15b9a
//! Source atom:    atom:code_member:7c2925d71af8874e78a8058b
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `mcp_harness_runtime_error`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_mcp_harness_runtime_error(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "mcp_harness_runtime_error";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_mcp_harness_runtime_error",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:36073abba277df2679e69740cfe639b34a25b64ff223bd3913bcddebc6e15b9a",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_mcp_harness_runtime_error",
        "sha256:36073abba277df2679e69740cfe639b34a25b64ff223bd3913bcddebc6e15b9a",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
