//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:fd427db6f3a5a9f8c4951498
//! Content hash:   sha256:fd427db6f3a5a9f8c49514982070550c8393370e6c8d0d76b5287141892ec26c
//! Source atom:    atom:code_member:7a58beb3bfc8980764c97dd0
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `memory_upsert_node`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_memory_upsert_node_fd427db6(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "memory_upsert_node";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_memory_upsert_node_fd427db6",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:fd427db6f3a5a9f8c49514982070550c8393370e6c8d0d76b5287141892ec26c",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_memory_upsert_node_fd427db6",
        "sha256:fd427db6f3a5a9f8c49514982070550c8393370e6c8d0d76b5287141892ec26c",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
