//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:839430fb10c176fec4e8b244
//! Content hash:   sha256:839430fb10c176fec4e8b244940a1b029bcce86d6eeb618ed6a59ed6bd759431
//! Source atom:    atom:code_member:180dc4dd3a57fd7156ebc076
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `native_memory_tools_round_trip_through_mcp`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_native_memory_tools_round_trip_through_mcp(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "native_memory_tools_round_trip_through_mcp";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_native_memory_tools_round_trip_through_mcp",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:839430fb10c176fec4e8b244940a1b029bcce86d6eeb618ed6a59ed6bd759431",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_native_memory_tools_round_trip_through_mcp",
        "sha256:839430fb10c176fec4e8b244940a1b029bcce86d6eeb618ed6a59ed6bd759431",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
