//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:8054ee32d43597869b0416d0
//! Content hash:   sha256:8054ee32d43597869b0416d030ed269d7d1c70edd99755ddb0e43677d0a11def
//! Source atom:    atom:code_member:6432a126ffaf309ec0a4ed8b
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `loaded_page_maps_status_and_content_type`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_loaded_page_maps_status_and_content_type(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "loaded_page_maps_status_and_content_type";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_loaded_page_maps_status_and_content_type",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:8054ee32d43597869b0416d030ed269d7d1c70edd99755ddb0e43677d0a11def",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_loaded_page_maps_status_and_content_type",
        "sha256:8054ee32d43597869b0416d030ed269d7d1c70edd99755ddb0e43677d0a11def",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
    )
}
