//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:044a89cdde38be27febb12c8
//! Content hash:   sha256:044a89cdde38be27febb12c8a6f86ee0f4d59b2c8e1a0baa4cecff5b459092fb
//! Source atom:    atom:code_member:3713849e5cb663926efc4b0c
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `expiration_index_updates_on_set_node_ttl`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_expiration_index_updates_on_set_node_ttl(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "expiration_index_updates_on_set_node_ttl";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_expiration_index_updates_on_set_node_ttl",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:044a89cdde38be27febb12c8a6f86ee0f4d59b2c8e1a0baa4cecff5b459092fb",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_expiration_index_updates_on_set_node_ttl",
        "sha256:044a89cdde38be27febb12c8a6f86ee0f4d59b2c8e1a0baa4cecff5b459092fb",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
