//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:eaae9064d56d3dd9d5d1b8b4
//! Content hash:   sha256:eaae9064d56d3dd9d5d1b8b468ad6428e48703571f1f036836b2cac9d6912259
//! Source atom:    atom:code_member:d57356045f98bdd7ffc93b93
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `parse_ref`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_parse_ref_eaae9064(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "parse_ref";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_parse_ref_eaae9064",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:eaae9064d56d3dd9d5d1b8b468ad6428e48703571f1f036836b2cac9d6912259",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:da5301b01417198329eba5e9d67767233084fa0c67eb5a7a8e5249b0fd19b881"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_parse_ref_eaae9064",
        "sha256:eaae9064d56d3dd9d5d1b8b468ad6428e48703571f1f036836b2cac9d6912259",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:da5301b01417198329eba5e9d67767233084fa0c67eb5a7a8e5249b0fd19b881"],
    )
}
