//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:29102a34d3b0ea77817b47a4
//! Content hash:   sha256:29102a34d3b0ea77817b47a42d0d3ef252d80d53788b11dd1856c3d12f127014
//! Source atom:    atom:code_member:985fa2edc436dab86e8ce431
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `exact_search`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_exact_search(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "exact_search";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_exact_search",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:29102a34d3b0ea77817b47a42d0d3ef252d80d53788b11dd1856c3d12f127014",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_exact_search",
        "sha256:29102a34d3b0ea77817b47a42d0d3ef252d80d53788b11dd1856c3d12f127014",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
