//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:f1fbb7a493c4dcbfca6367d1
//! Content hash:   sha256:f1fbb7a493c4dcbfca6367d108cc502a0e2788b1a79fcb2702337be83272f04a
//! Source atom:    atom:code_member:41bf55be284b88e1f65a5321
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `memory_upsert_edge`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_memory_upsert_edge_f1fbb7a4(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "memory_upsert_edge";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_memory_upsert_edge_f1fbb7a4",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:f1fbb7a493c4dcbfca6367d108cc502a0e2788b1a79fcb2702337be83272f04a",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c068a3ad3c6eeb3bcb8521ab44bc0cdbb9c7a770c6011a4079a4d3aab8f025fa"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_memory_upsert_edge_f1fbb7a4",
        "sha256:f1fbb7a493c4dcbfca6367d108cc502a0e2788b1a79fcb2702337be83272f04a",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c068a3ad3c6eeb3bcb8521ab44bc0cdbb9c7a770c6011a4079a4d3aab8f025fa"],
    )
}
