//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:af44073e9a6fe6c069013870
//! Content hash:   sha256:af44073e9a6fe6c069013870d0be969618d1f9d3b9d02f3419fc6a2f8972c673
//! Source atom:    atom:code_test_body:f822ccbb4ed1595d6171efc8
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `redcore_purge_batched_when_multiple_expire_at_once`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_redcore_purge_batched_when_multiple_expire_at_once(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "redcore_purge_batched_when_multiple_expire_at_once";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_redcore_purge_batched_when_multiple_expire_at_once",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:af44073e9a6fe6c069013870d0be969618d1f9d3b9d02f3419fc6a2f8972c673",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:50d3bce145f9423324e485e9521c4f1177399eacf07f3a1ba354bf51de55c64f"],
        });
    }
    let expected_body_hash = "sha256:50d3bce145f9423324e485e9521c4f1177399eacf07f3a1ba354bf51de55c64f";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_redcore_purge_batched_when_multiple_expire_at_once",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:af44073e9a6fe6c069013870d0be969618d1f9d3b9d02f3419fc6a2f8972c673",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:50d3bce145f9423324e485e9521c4f1177399eacf07f3a1ba354bf51de55c64f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_redcore_purge_batched_when_multiple_expire_at_once",
        "sha256:af44073e9a6fe6c069013870d0be969618d1f9d3b9d02f3419fc6a2f8972c673",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:50d3bce145f9423324e485e9521c4f1177399eacf07f3a1ba354bf51de55c64f"],
    )
}
