//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:09e326b681bd75199a657c15
//! Content hash:   sha256:09e326b681bd75199a657c151525626b487fc3821d5e9567ef38a66f0e31688d
//! Source atom:    atom:code_test_body:fddad12be97b602b22377a71
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_list_episodes_tool_schema_includes_filters`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_list_episodes_tool_schema_includes_filters(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_list_episodes_tool_schema_includes_filters";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_list_episodes_tool_schema_includes_filters",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:09e326b681bd75199a657c151525626b487fc3821d5e9567ef38a66f0e31688d",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:db8adc2c50cd1c8c843a0feed22e168969a6ddfd4a0e08522d554fcd2809a060", "sha256:67d39f8cb6e6a3badcef695c44e5c9e338d2f46a57ddc5cba70a1be299739eef"],
        });
    }
    let expected_body_hash = "sha256:67d39f8cb6e6a3badcef695c44e5c9e338d2f46a57ddc5cba70a1be299739eef";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_list_episodes_tool_schema_includes_filters",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:09e326b681bd75199a657c151525626b487fc3821d5e9567ef38a66f0e31688d",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:db8adc2c50cd1c8c843a0feed22e168969a6ddfd4a0e08522d554fcd2809a060", "sha256:67d39f8cb6e6a3badcef695c44e5c9e338d2f46a57ddc5cba70a1be299739eef"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_list_episodes_tool_schema_includes_filters",
        "sha256:09e326b681bd75199a657c151525626b487fc3821d5e9567ef38a66f0e31688d",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:db8adc2c50cd1c8c843a0feed22e168969a6ddfd4a0e08522d554fcd2809a060", "sha256:67d39f8cb6e6a3badcef695c44e5c9e338d2f46a57ddc5cba70a1be299739eef"],
    )
}
