//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:d01a662628ebb9447bf4cd8b
//! Content hash:   sha256:d01a662628ebb9447bf4cd8b843d06aae497449c6292521b0cdcd62a909e7ae8
//! Source atom:    atom:code_member:d1c88a157d4348c43e553070
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `get_node`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_get_node_d01a6626(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "get_node";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_get_node_d01a6626",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:d01a662628ebb9447bf4cd8b843d06aae497449c6292521b0cdcd62a909e7ae8",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_get_node_d01a6626",
        "sha256:d01a662628ebb9447bf4cd8b843d06aae497449c6292521b0cdcd62a909e7ae8",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
