//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:6c3d9b95ac045803f89463ae
//! Content hash:   sha256:6c3d9b95ac045803f89463aeab745f998e0e23407c12b3b3b77e2d92ea5092c8
//! Source atom:    atom:code_member:caaa8c5734eef82998b80f65
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `notes_sync_clone_absolute_target_from_non_repo_cwd_fetches_authorship_notes`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_notes_sync_clone_absolute_target_from_non_repo_cwd_fetches_authorship_notes(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "notes_sync_clone_absolute_target_from_non_repo_cwd_fetches_authorship_notes";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_notes_sync_clone_absolute_target_from_non_repo_cwd_fetches_authorship_notes",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:6c3d9b95ac045803f89463aeab745f998e0e23407c12b3b3b77e2d92ea5092c8",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:12f3bf863dc332b8345329367277eacf7255ba1c83d92196fd9a101f0cf77cca"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_notes_sync_clone_absolute_target_from_non_repo_cwd_fetches_authorship_notes",
        "sha256:6c3d9b95ac045803f89463aeab745f998e0e23407c12b3b3b77e2d92ea5092c8",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:12f3bf863dc332b8345329367277eacf7255ba1c83d92196fd9a101f0cf77cca"],
    )
}
