//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:d38790c82e726d2748008390
//! Content hash:   sha256:d38790c82e726d2748008390791b51bacbd17bd2734f47623a4c313927193b37
//! Source atom:    atom:code_member:f158984e15c0b2f19c6023bb
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `neighbors`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_neighbors_d38790c8(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "neighbors";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_neighbors_d38790c8",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:d38790c82e726d2748008390791b51bacbd17bd2734f47623a4c313927193b37",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_neighbors_d38790c8",
        "sha256:d38790c82e726d2748008390791b51bacbd17bd2734f47623a4c313927193b37",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
    )
}
