//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:c6c5bbf3467e6c18d7b27397
//! Content hash:   sha256:c6c5bbf3467e6c18d7b27397fecd77ee5cd40b0d5fe279ab0efba6cf4a3e5f73
//! Source atom:    atom:code_member:670f518f439af050f2134940
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `payload_bool`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_payload_bool(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "payload_bool";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_payload_bool",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:c6c5bbf3467e6c18d7b27397fecd77ee5cd40b0d5fe279ab0efba6cf4a3e5f73",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_payload_bool",
        "sha256:c6c5bbf3467e6c18d7b27397fecd77ee5cd40b0d5fe279ab0efba6cf4a3e5f73",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
    )
}
