//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:7f26ec1457ee342d53855610
//! Content hash:   sha256:7f26ec1457ee342d53855610f8866b91ee1786cef20e78c7642a027b56369303
//! Source atom:    atom:code_member:a4f45fd9506eab5a6d39055d
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `crawl_receipt_id`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_crawl_receipt_id(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "crawl_receipt_id";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_crawl_receipt_id",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:7f26ec1457ee342d53855610f8866b91ee1786cef20e78c7642a027b56369303",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:322f31931b4c2312910c384bd46c422e866dea03bb6024f98fa90fb68ef58cd0"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_crawl_receipt_id",
        "sha256:7f26ec1457ee342d53855610f8866b91ee1786cef20e78c7642a027b56369303",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:322f31931b4c2312910c384bd46c422e866dea03bb6024f98fa90fb68ef58cd0"],
    )
}
