//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:44549abba026fa6687a6de2b
//! Content hash:   sha256:44549abba026fa6687a6de2b6d4850ef26f57ef700e326950780d84e9f459b7e
//! Source atom:    atom:code_member:2eb1170e150db648f62610aa
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `harness_run_detail`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_harness_run_detail_44549abb(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "harness_run_detail";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_harness_run_detail_44549abb",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:44549abba026fa6687a6de2b6d4850ef26f57ef700e326950780d84e9f459b7e",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_harness_run_detail_44549abb",
        "sha256:44549abba026fa6687a6de2b6d4850ef26f57ef700e326950780d84e9f459b7e",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
