//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:54b728c3a8337dbb48b8dbda
//! Content hash:   sha256:54b728c3a8337dbb48b8dbda23e8d56fe3cf7a0993c6141a900995e009d537ab
//! Source atom:    atom:code_test_body:c112b256a7c4170fe6203a65
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `query_nodes_includes_expired_when_flag_set`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_query_nodes_includes_expired_when_flag_set(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "query_nodes_includes_expired_when_flag_set";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_query_nodes_includes_expired_when_flag_set",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:54b728c3a8337dbb48b8dbda23e8d56fe3cf7a0993c6141a900995e009d537ab",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:64b76d3d707c1e0dc90ab65ed058da9afba4293d614c607c45bf3f274b1e1696"],
        });
    }
    let expected_body_hash = "sha256:64b76d3d707c1e0dc90ab65ed058da9afba4293d614c607c45bf3f274b1e1696";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_query_nodes_includes_expired_when_flag_set",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:54b728c3a8337dbb48b8dbda23e8d56fe3cf7a0993c6141a900995e009d537ab",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:64b76d3d707c1e0dc90ab65ed058da9afba4293d614c607c45bf3f274b1e1696"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_query_nodes_includes_expired_when_flag_set",
        "sha256:54b728c3a8337dbb48b8dbda23e8d56fe3cf7a0993c6141a900995e009d537ab",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:64b76d3d707c1e0dc90ab65ed058da9afba4293d614c607c45bf3f274b1e1696"],
    )
}
