//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:e4eb4b316cc48b1e6d0d3e6e
//! Content hash:   sha256:e4eb4b316cc48b1e6d0d3e6e4125d21b02535b205fd3fc3f96580c83147528ce
//! Source atom:    atom:code_member:de1c0c5abb5602e41dec4f83
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `upsert_edge`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_upsert_edge_e4eb4b31(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "upsert_edge";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_upsert_edge_e4eb4b31",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:e4eb4b316cc48b1e6d0d3e6e4125d21b02535b205fd3fc3f96580c83147528ce",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_upsert_edge_e4eb4b31",
        "sha256:e4eb4b316cc48b1e6d0d3e6e4125d21b02535b205fd3fc3f96580c83147528ce",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
    )
}
