//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:263586948fd3e01ffc6af211
//! Content hash:   sha256:263586948fd3e01ffc6af211145450af2b73978069648cbf2264e388b6639ccd
//! Source atom:    atom:code_member:30d03e946fe6e3ef402f6959
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `rebuild_indexes`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_rebuild_indexes_26358694(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "rebuild_indexes";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_rebuild_indexes_26358694",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:263586948fd3e01ffc6af211145450af2b73978069648cbf2264e388b6639ccd",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_rebuild_indexes_26358694",
        "sha256:263586948fd3e01ffc6af211145450af2b73978069648cbf2264e388b6639ccd",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
