//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:b16e0f76bd9f70131e5d4743
//! Content hash:   sha256:b16e0f76bd9f70131e5d4743881697492040d210095e07264110a64b5917345e
//! Source atom:    atom:code_member:e6d07b9007545824a4b7d04b
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `parse_ref`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_parse_ref_b16e0f76(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "parse_ref";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_parse_ref_b16e0f76",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:b16e0f76bd9f70131e5d4743881697492040d210095e07264110a64b5917345e",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:da5301b01417198329eba5e9d67767233084fa0c67eb5a7a8e5249b0fd19b881"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_parse_ref_b16e0f76",
        "sha256:b16e0f76bd9f70131e5d4743881697492040d210095e07264110a64b5917345e",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:da5301b01417198329eba5e9d67767233084fa0c67eb5a7a8e5249b0fd19b881"],
    )
}
