//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:224c1757ddd8349d07f369d0
//! Content hash:   sha256:224c1757ddd8349d07f369d05b489c42eecc8e0a834994209a5ed93cc741d516
//! Source atom:    atom:code_test_body:b7d11fe085476ba8db2b6bba
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_fancy_repetition`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_fancy_repetition(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_fancy_repetition";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_fancy_repetition",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:224c1757ddd8349d07f369d05b489c42eecc8e0a834994209a5ed93cc741d516",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:023d6b57ba5ba199a04d9757e3b1464c2bc09579b035ea82c047e08d89d19226", "sha256:157caea790c4487fa1c0456dfe9efd9b3c58d24b3a1b22e37b3e185fd7ec4df5"],
        });
    }
    let expected_body_hash = "sha256:157caea790c4487fa1c0456dfe9efd9b3c58d24b3a1b22e37b3e185fd7ec4df5";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_fancy_repetition",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:224c1757ddd8349d07f369d05b489c42eecc8e0a834994209a5ed93cc741d516",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:023d6b57ba5ba199a04d9757e3b1464c2bc09579b035ea82c047e08d89d19226", "sha256:157caea790c4487fa1c0456dfe9efd9b3c58d24b3a1b22e37b3e185fd7ec4df5"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_fancy_repetition",
        "sha256:224c1757ddd8349d07f369d05b489c42eecc8e0a834994209a5ed93cc741d516",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:023d6b57ba5ba199a04d9757e3b1464c2bc09579b035ea82c047e08d89d19226", "sha256:157caea790c4487fa1c0456dfe9efd9b3c58d24b3a1b22e37b3e185fd7ec4df5"],
    )
}
