//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:f1fa93eee67b0ccaa59b16c8
//! Content hash:   sha256:f1fa93eee67b0ccaa59b16c879ef8dc89c267d01d7b0685e10bd1759e68b5464
//! Source atom:    atom:code_member:0c0d42d652a3f2a463187153
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `memory_browser_session`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_memory_browser_session(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "memory_browser_session";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_memory_browser_session",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:f1fa93eee67b0ccaa59b16c879ef8dc89c267d01d7b0685e10bd1759e68b5464",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_memory_browser_session",
        "sha256:f1fa93eee67b0ccaa59b16c879ef8dc89c267d01d7b0685e10bd1759e68b5464",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
    )
}
