//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:e8b5b84348ac999dd71acf9e
//! Content hash:   sha256:e8b5b84348ac999dd71acf9e9bcac5a97ea083eeadfdf861327740ae66fc39a2
//! Source atom:    atom:code_test_body:17287edfdfee08048211f769
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `daemon_telemetry_and_cas_over_persistent_connection`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_daemon_telemetry_and_cas_over_persistent_connection(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "daemon_telemetry_and_cas_over_persistent_connection";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_daemon_telemetry_and_cas_over_persistent_connection",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:e8b5b84348ac999dd71acf9e9bcac5a97ea083eeadfdf861327740ae66fc39a2",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:70bd9a60bff7cd7c4a2639f33cd29eb3a9a34ea9a0e08a28a451f0421772becb", "sha256:4275591355e8d2c7df136f7f0295eda30324900a06710036f01c7c29e6c912df"],
        });
    }
    let expected_body_hash = "sha256:4275591355e8d2c7df136f7f0295eda30324900a06710036f01c7c29e6c912df";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_daemon_telemetry_and_cas_over_persistent_connection",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:e8b5b84348ac999dd71acf9e9bcac5a97ea083eeadfdf861327740ae66fc39a2",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:70bd9a60bff7cd7c4a2639f33cd29eb3a9a34ea9a0e08a28a451f0421772becb", "sha256:4275591355e8d2c7df136f7f0295eda30324900a06710036f01c7c29e6c912df"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_daemon_telemetry_and_cas_over_persistent_connection",
        "sha256:e8b5b84348ac999dd71acf9e9bcac5a97ea083eeadfdf861327740ae66fc39a2",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:70bd9a60bff7cd7c4a2639f33cd29eb3a9a34ea9a0e08a28a451f0421772becb", "sha256:4275591355e8d2c7df136f7f0295eda30324900a06710036f01c7c29e6c912df"],
    )
}
