//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:63bf4e0031f5cf1d7f9d53b0
//! Content hash:   sha256:63bf4e0031f5cf1d7f9d53b0a3b74a8a4a5f10d086e213c173b95dbf52d2314e
//! Source atom:    atom:code_test_body:a1f2f068840ef8ded8011ee3
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `native_coordination_tools_round_trip_through_mcp`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_native_coordination_tools_round_trip_through_mcp(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "native_coordination_tools_round_trip_through_mcp";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_native_coordination_tools_round_trip_through_mcp",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:63bf4e0031f5cf1d7f9d53b0a3b74a8a4a5f10d086e213c173b95dbf52d2314e",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f", "sha256:6ac8fa82c8e002e370df1a60227129ab525a2ceef95cd7791b7ffb9b023d8807"],
        });
    }
    let expected_body_hash = "sha256:6ac8fa82c8e002e370df1a60227129ab525a2ceef95cd7791b7ffb9b023d8807";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_native_coordination_tools_round_trip_through_mcp",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:63bf4e0031f5cf1d7f9d53b0a3b74a8a4a5f10d086e213c173b95dbf52d2314e",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f", "sha256:6ac8fa82c8e002e370df1a60227129ab525a2ceef95cd7791b7ffb9b023d8807"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_native_coordination_tools_round_trip_through_mcp",
        "sha256:63bf4e0031f5cf1d7f9d53b0a3b74a8a4a5f10d086e213c173b95dbf52d2314e",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f", "sha256:6ac8fa82c8e002e370df1a60227129ab525a2ceef95cd7791b7ffb9b023d8807"],
    )
}
