//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:8123290661ca610e3f29c440
//! Content hash:   sha256:8123290661ca610e3f29c4404da8c4d6858188fb2de64453f9ee500f0dd8f5d6
//! Source atom:    atom:code_member:a856f152d78f6295d9bea6b5
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `rebuild_indexes`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_rebuild_indexes_81232906(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "rebuild_indexes";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_rebuild_indexes_81232906",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:8123290661ca610e3f29c4404da8c4d6858188fb2de64453f9ee500f0dd8f5d6",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_rebuild_indexes_81232906",
        "sha256:8123290661ca610e3f29c4404da8c4d6858188fb2de64453f9ee500f0dd8f5d6",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
