//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:44fc83b2537783bac3638f9d
//! Content hash:   sha256:44fc83b2537783bac3638f9df327c8cb2580ea5da8afc7c58bb12d2bb2a97f72
//! Source atom:    atom:code_member:a98e6fea2879771cfb968da7
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `binding_event_node`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_binding_event_node(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "binding_event_node";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_binding_event_node",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:44fc83b2537783bac3638f9df327c8cb2580ea5da8afc7c58bb12d2bb2a97f72",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:064db319ed4a71ebc58a9c6c70ba5631747805bc2be65a75307b30112597b1a7"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_binding_event_node",
        "sha256:44fc83b2537783bac3638f9df327c8cb2580ea5da8afc7c58bb12d2bb2a97f72",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:064db319ed4a71ebc58a9c6c70ba5631747805bc2be65a75307b30112597b1a7"],
    )
}
