//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:a533a8b4b2a593e779baaf22
//! Content hash:   sha256:a533a8b4b2a593e779baaf22b864a6b9d4b98eee871398e7c60af1eceab05213
//! Source atom:    atom:code_member:ef3b0611928173aef88c9305
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `timestamp_or_now`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_timestamp_or_now_a533a8b4(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "timestamp_or_now";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_timestamp_or_now_a533a8b4",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:a533a8b4b2a593e779baaf22b864a6b9d4b98eee871398e7c60af1eceab05213",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_timestamp_or_now_a533a8b4",
        "sha256:a533a8b4b2a593e779baaf22b864a6b9d4b98eee871398e7c60af1eceab05213",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a"],
    )
}
