//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:0e27f1c087149f98b06b0eff
//! Content hash:   sha256:0e27f1c087149f98b06b0eff601e7c76b313b2cdf2b5f9232e82bbb61e46f825
//! Source atom:    atom:code_member:97fe9276f4588675325ca497
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `ingested_page_count`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_ingested_page_count(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "ingested_page_count";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_ingested_page_count",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:0e27f1c087149f98b06b0eff601e7c76b313b2cdf2b5f9232e82bbb61e46f825",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_ingested_page_count",
        "sha256:0e27f1c087149f98b06b0eff601e7c76b313b2cdf2b5f9232e82bbb61e46f825",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
    )
}
