//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:bb2b56a6ec94dbd1291e6cfd
//! Content hash:   sha256:bb2b56a6ec94dbd1291e6cfd595b3bcbec8691638364adf0334fe44161752c6c
//! Source atom:    atom:code_test_body:705bfa7aa06cf9d3f8913639
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `expiration_index_updates_on_upsert`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_expiration_index_updates_on_upsert(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "expiration_index_updates_on_upsert";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_expiration_index_updates_on_upsert",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:bb2b56a6ec94dbd1291e6cfd595b3bcbec8691638364adf0334fe44161752c6c",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:91279144c43a426c0b9700504e736f6d7ec49ffd7b9676122b04a3e06fece0f7"],
        });
    }
    let expected_body_hash = "sha256:91279144c43a426c0b9700504e736f6d7ec49ffd7b9676122b04a3e06fece0f7";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_expiration_index_updates_on_upsert",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:bb2b56a6ec94dbd1291e6cfd595b3bcbec8691638364adf0334fe44161752c6c",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:91279144c43a426c0b9700504e736f6d7ec49ffd7b9676122b04a3e06fece0f7"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_expiration_index_updates_on_upsert",
        "sha256:bb2b56a6ec94dbd1291e6cfd595b3bcbec8691638364adf0334fe44161752c6c",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:91279144c43a426c0b9700504e736f6d7ec49ffd7b9676122b04a3e06fece0f7"],
    )
}
