//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:707ed2bbbf9b5a26ce923672
//! Content hash:   sha256:707ed2bbbf9b5a26ce923672024f4432309767178e6e0b1ebcf82caa4104100b
//! Source atom:    atom:code_test_body:6718745052cdd99323173c89
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_static_bitmap_32_last_1`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_static_bitmap_32_last_1(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_static_bitmap_32_last_1";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_static_bitmap_32_last_1",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:707ed2bbbf9b5a26ce923672024f4432309767178e6e0b1ebcf82caa4104100b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4157af7bf01e779a6a54b09142f4b500de6ebbfff162bc8145c13cc3f61cc901", "sha256:341e1367a5b84d3ed0b1f8145fbb3f6e0165ba8721112b28685bee0007d14126"],
        });
    }
    let expected_body_hash = "sha256:341e1367a5b84d3ed0b1f8145fbb3f6e0165ba8721112b28685bee0007d14126";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_static_bitmap_32_last_1",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:707ed2bbbf9b5a26ce923672024f4432309767178e6e0b1ebcf82caa4104100b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4157af7bf01e779a6a54b09142f4b500de6ebbfff162bc8145c13cc3f61cc901", "sha256:341e1367a5b84d3ed0b1f8145fbb3f6e0165ba8721112b28685bee0007d14126"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_static_bitmap_32_last_1",
        "sha256:707ed2bbbf9b5a26ce923672024f4432309767178e6e0b1ebcf82caa4104100b",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4157af7bf01e779a6a54b09142f4b500de6ebbfff162bc8145c13cc3f61cc901", "sha256:341e1367a5b84d3ed0b1f8145fbb3f6e0165ba8721112b28685bee0007d14126"],
    )
}
