//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:b27ece43e1416b6d1f8a7571
//! Content hash:   sha256:b27ece43e1416b6d1f8a7571921600fcd39b714a5c59883ae91015877058d379
//! Source atom:    atom:code_member:666d6e99d350771cfaa90b2c
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `skill_pack_use_receipt_node_id`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_skill_pack_use_receipt_node_id(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "skill_pack_use_receipt_node_id";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_skill_pack_use_receipt_node_id",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:b27ece43e1416b6d1f8a7571921600fcd39b714a5c59883ae91015877058d379",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_skill_pack_use_receipt_node_id",
        "sha256:b27ece43e1416b6d1f8a7571921600fcd39b714a5c59883ae91015877058d379",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:2c66ade2df9a45240da21876fd32c894c1d692a230cfc8a611bf6c5ab1fd471a"],
    )
}
