//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:e963cb8525199123bf87c533
//! Content hash:   sha256:e963cb8525199123bf87c533c30fd943324cedd76e3f8d8213472a0e144df06e
//! Source atom:    atom:code_test_body:941373abd7699ad5619c9264
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_wrong_usage`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_wrong_usage(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_wrong_usage";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_wrong_usage",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:e963cb8525199123bf87c533c30fd943324cedd76e3f8d8213472a0e144df06e",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c8586c1c6bb4e79dc234d4e2d670d537fb7cdba12d5c84b6c05a087b766f0af9", "sha256:c5c77495ada0d8ad2b8b71bd3ffe452735e4fc8e039e06a5d8e9a9276049d110"],
        });
    }
    let expected_body_hash = "sha256:c5c77495ada0d8ad2b8b71bd3ffe452735e4fc8e039e06a5d8e9a9276049d110";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_wrong_usage",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:e963cb8525199123bf87c533c30fd943324cedd76e3f8d8213472a0e144df06e",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c8586c1c6bb4e79dc234d4e2d670d537fb7cdba12d5c84b6c05a087b766f0af9", "sha256:c5c77495ada0d8ad2b8b71bd3ffe452735e4fc8e039e06a5d8e9a9276049d110"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_wrong_usage",
        "sha256:e963cb8525199123bf87c533c30fd943324cedd76e3f8d8213472a0e144df06e",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:c8586c1c6bb4e79dc234d4e2d670d537fb7cdba12d5c84b6c05a087b766f0af9", "sha256:c5c77495ada0d8ad2b8b71bd3ffe452735e4fc8e039e06a5d8e9a9276049d110"],
    )
}
