//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:307026c1e9632e8ffd688672
//! Content hash:   sha256:307026c1e9632e8ffd688672ca0192d888b1f607fd7775ed47b241619a5a8643
//! Source atom:    atom:code_test_body:86544fd8e5f5e04763c428d8
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `vector_auto_index_on_upsert`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_vector_auto_index_on_upsert(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "vector_auto_index_on_upsert";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_vector_auto_index_on_upsert",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:307026c1e9632e8ffd688672ca0192d888b1f607fd7775ed47b241619a5a8643",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:2406ee85272dedda983bd64ae42414999257fb426fa5e6044763ac08911f46db"],
        });
    }
    let expected_body_hash = "sha256:2406ee85272dedda983bd64ae42414999257fb426fa5e6044763ac08911f46db";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_vector_auto_index_on_upsert",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:307026c1e9632e8ffd688672ca0192d888b1f607fd7775ed47b241619a5a8643",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:2406ee85272dedda983bd64ae42414999257fb426fa5e6044763ac08911f46db"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_vector_auto_index_on_upsert",
        "sha256:307026c1e9632e8ffd688672ca0192d888b1f607fd7775ed47b241619a5a8643",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:2406ee85272dedda983bd64ae42414999257fb426fa5e6044763ac08911f46db"],
    )
}
