//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:6a0ec2c001cfa0ec3b4d2f4c
//! Content hash:   sha256:6a0ec2c001cfa0ec3b4d2f4ce1be17a34e548aa9ba53086090bfccf8bba98e63
//! Source atom:    atom:code_member:4a45f58098de7cab31f0f065
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `nodes`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_nodes(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "nodes";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_nodes",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:6a0ec2c001cfa0ec3b4d2f4ce1be17a34e548aa9ba53086090bfccf8bba98e63",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_nodes",
        "sha256:6a0ec2c001cfa0ec3b4d2f4ce1be17a34e548aa9ba53086090bfccf8bba98e63",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
