//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:ffc10bc591ae28bb82d4a52f
//! Content hash:   sha256:ffc10bc591ae28bb82d4a52f1d3475d62d128eaffc633b0d32c1ea288bbded32
//! Source atom:    atom:code_test_body:c4350c21ff133843ccfcfceb
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `symbolic_probabilistic_tools_return_receipts`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_symbolic_probabilistic_tools_return_receipts(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "symbolic_probabilistic_tools_return_receipts";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_symbolic_probabilistic_tools_return_receipts",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:ffc10bc591ae28bb82d4a52f1d3475d62d128eaffc633b0d32c1ea288bbded32",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f", "sha256:dd3b88e643cfb0e04c247e901c507564f46d5f3063625ffc675be1b36b99e505"],
        });
    }
    let expected_body_hash = "sha256:dd3b88e643cfb0e04c247e901c507564f46d5f3063625ffc675be1b36b99e505";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_symbolic_probabilistic_tools_return_receipts",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:ffc10bc591ae28bb82d4a52f1d3475d62d128eaffc633b0d32c1ea288bbded32",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f", "sha256:dd3b88e643cfb0e04c247e901c507564f46d5f3063625ffc675be1b36b99e505"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_symbolic_probabilistic_tools_return_receipts",
        "sha256:ffc10bc591ae28bb82d4a52f1d3475d62d128eaffc633b0d32c1ea288bbded32",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f", "sha256:dd3b88e643cfb0e04c247e901c507564f46d5f3063625ffc675be1b36b99e505"],
    )
}
