//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:aeb4644922d6da11de256e2f
//! Content hash:   sha256:aeb4644922d6da11de256e2f503441592adc2a6ee5176bb75888942aba110c40
//! Source atom:    atom:code_member:62b43fc7a820d84eeffaa300
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `render_search_page`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_render_search_page(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "render_search_page";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_render_search_page",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:aeb4644922d6da11de256e2f503441592adc2a6ee5176bb75888942aba110c40",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_render_search_page",
        "sha256:aeb4644922d6da11de256e2f503441592adc2a6ee5176bb75888942aba110c40",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:2527425c7f005c232eeedf149b4a193b5a6f842f4a94fca88e43c222edc4d4de"],
    )
}
