//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:1ada86a70ffaff4cb6ec7a64
//! Content hash:   sha256:1ada86a70ffaff4cb6ec7a647261aa6966dcfcef7b4a3b92617d1d68fa3f606c
//! Source atom:    atom:code_member:b19bc2609dcda81481574a10
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `signing_bytes`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_signing_bytes(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "signing_bytes";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_signing_bytes",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:1ada86a70ffaff4cb6ec7a647261aa6966dcfcef7b4a3b92617d1d68fa3f606c",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:322f31931b4c2312910c384bd46c422e866dea03bb6024f98fa90fb68ef58cd0"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_signing_bytes",
        "sha256:1ada86a70ffaff4cb6ec7a647261aa6966dcfcef7b4a3b92617d1d68fa3f606c",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:322f31931b4c2312910c384bd46c422e866dea03bb6024f98fa90fb68ef58cd0"],
    )
}
