//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:087c6aaa576b2545a6f37705
//! Content hash:   sha256:087c6aaa576b2545a6f37705f17f85f23247a9de48b54e8c0c7ef049bdfc0617
//! Source atom:    atom:code_test_body:d2d11e560daa022e12ab277e
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `roundtrip_random_config_long`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_roundtrip_random_config_long(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "roundtrip_random_config_long";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_roundtrip_random_config_long",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:087c6aaa576b2545a6f37705f17f85f23247a9de48b54e8c0c7ef049bdfc0617",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:90cb9f8a1ccb7c4ddc4f8618208e0031fc97e0df0e5aa466d6a5cf45d25967d8", "sha256:f3f4cbdc8d6a45d818680f99aa72c5d01191359db70ce974629210e16a28ede5"],
        });
    }
    let expected_body_hash = "sha256:f3f4cbdc8d6a45d818680f99aa72c5d01191359db70ce974629210e16a28ede5";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_roundtrip_random_config_long",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:087c6aaa576b2545a6f37705f17f85f23247a9de48b54e8c0c7ef049bdfc0617",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:90cb9f8a1ccb7c4ddc4f8618208e0031fc97e0df0e5aa466d6a5cf45d25967d8", "sha256:f3f4cbdc8d6a45d818680f99aa72c5d01191359db70ce974629210e16a28ede5"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_roundtrip_random_config_long",
        "sha256:087c6aaa576b2545a6f37705f17f85f23247a9de48b54e8c0c7ef049bdfc0617",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:90cb9f8a1ccb7c4ddc4f8618208e0031fc97e0df0e5aa466d6a5cf45d25967d8", "sha256:f3f4cbdc8d6a45d818680f99aa72c5d01191359db70ce974629210e16a28ede5"],
    )
}
