//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:0f86bbfc35ed53f188e81acd
//! Content hash:   sha256:0f86bbfc35ed53f188e81acd81209438290f2a419bb4c7b66436bcca70e25a2a
//! Source atom:    atom:code_test_body:651e693adb6b513b7ddd9aef
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_static_bitmap_32_middle_1`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_static_bitmap_32_middle_1(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_static_bitmap_32_middle_1";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_static_bitmap_32_middle_1",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:0f86bbfc35ed53f188e81acd81209438290f2a419bb4c7b66436bcca70e25a2a",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4157af7bf01e779a6a54b09142f4b500de6ebbfff162bc8145c13cc3f61cc901", "sha256:1d3c8cd3d903706153af9cda7c553c36bbf9845f6b5b982ff578dd496df36cea"],
        });
    }
    let expected_body_hash = "sha256:1d3c8cd3d903706153af9cda7c553c36bbf9845f6b5b982ff578dd496df36cea";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_static_bitmap_32_middle_1",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:0f86bbfc35ed53f188e81acd81209438290f2a419bb4c7b66436bcca70e25a2a",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4157af7bf01e779a6a54b09142f4b500de6ebbfff162bc8145c13cc3f61cc901", "sha256:1d3c8cd3d903706153af9cda7c553c36bbf9845f6b5b982ff578dd496df36cea"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_static_bitmap_32_middle_1",
        "sha256:0f86bbfc35ed53f188e81acd81209438290f2a419bb4c7b66436bcca70e25a2a",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:4157af7bf01e779a6a54b09142f4b500de6ebbfff162bc8145c13cc3f61cc901", "sha256:1d3c8cd3d903706153af9cda7c553c36bbf9845f6b5b982ff578dd496df36cea"],
    )
}
