//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:7967d2a6506d916748193ffa
//! Content hash:   sha256:7967d2a6506d916748193ffab85d771bd7620dbabfffef31a812bd238142503b
//! Source atom:    atom:code_member:a3968d099d080a4266e11bcd
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `rebuild_indexes`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_rebuild_indexes_7967d2a6(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "rebuild_indexes";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_rebuild_indexes_7967d2a6",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:7967d2a6506d916748193ffab85d771bd7620dbabfffef31a812bd238142503b",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_rebuild_indexes_7967d2a6",
        "sha256:7967d2a6506d916748193ffab85d771bd7620dbabfffef31a812bd238142503b",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
