//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:f49e8f53f20d8d3e295f33de
//! Content hash:   sha256:f49e8f53f20d8d3e295f33de740efa324d8f54dfd9d038880f0902dda0812f12
//! Source atom:    atom:code_member:08a35d8c69d5f4e0b158c533
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `manifest_version_compatible`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_manifest_version_compatible(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "manifest_version_compatible";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_manifest_version_compatible",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:f49e8f53f20d8d3e295f33de740efa324d8f54dfd9d038880f0902dda0812f12",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_manifest_version_compatible",
        "sha256:f49e8f53f20d8d3e295f33de740efa324d8f54dfd9d038880f0902dda0812f12",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
