//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:5f3123f888353bd902c177ae
//! Content hash:   sha256:5f3123f888353bd902c177ae3943a47d39070626576b47eea3e17779166d4950
//! Source atom:    atom:code_member:c51f345a105f0674d4b8c90f
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `skill_pack_upsert_node`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_skill_pack_upsert_node_5f3123f8(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "skill_pack_upsert_node";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_skill_pack_upsert_node_5f3123f8",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:5f3123f888353bd902c177ae3943a47d39070626576b47eea3e17779166d4950",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_skill_pack_upsert_node_5f3123f8",
        "sha256:5f3123f888353bd902c177ae3943a47d39070626576b47eea3e17779166d4950",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
