//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:874bbca8cea868c675237b13
//! Content hash:   sha256:874bbca8cea868c675237b13e5a8da7033ccd50815d31c4cd5a0ef9494dab40e
//! Source atom:    atom:code_test_body:d5111b143d7488fa8710e066
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `vector_auto_index_on_upsert`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_vector_auto_index_on_upsert(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "vector_auto_index_on_upsert";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_vector_auto_index_on_upsert",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:874bbca8cea868c675237b13e5a8da7033ccd50815d31c4cd5a0ef9494dab40e",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:2406ee85272dedda983bd64ae42414999257fb426fa5e6044763ac08911f46db"],
        });
    }
    let expected_body_hash = "sha256:2406ee85272dedda983bd64ae42414999257fb426fa5e6044763ac08911f46db";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_vector_auto_index_on_upsert",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:874bbca8cea868c675237b13e5a8da7033ccd50815d31c4cd5a0ef9494dab40e",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:2406ee85272dedda983bd64ae42414999257fb426fa5e6044763ac08911f46db"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_vector_auto_index_on_upsert",
        "sha256:874bbca8cea868c675237b13e5a8da7033ccd50815d31c4cd5a0ef9494dab40e",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:2406ee85272dedda983bd64ae42414999257fb426fa5e6044763ac08911f46db"],
    )
}
