//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:0999ac42c4a0a568b8c4c176
//! Content hash:   sha256:0999ac42c4a0a568b8c4c17640b0d15ed74f3daf22c51a8e2d96ec491908ba6c
//! Source atom:    atom:code_test_body:3376fd9fa50f3fc55f9fab6b
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `redcore_set_node_ttl_persists_through_aof_replay`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_redcore_set_node_ttl_persists_through_aof_replay(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "redcore_set_node_ttl_persists_through_aof_replay";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_redcore_set_node_ttl_persists_through_aof_replay",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:0999ac42c4a0a568b8c4c17640b0d15ed74f3daf22c51a8e2d96ec491908ba6c",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:5c1bcc20c9058ca0e13084ba1278e8aaab241f6864dcacc1647642a4198654be"],
        });
    }
    let expected_body_hash = "sha256:5c1bcc20c9058ca0e13084ba1278e8aaab241f6864dcacc1647642a4198654be";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_redcore_set_node_ttl_persists_through_aof_replay",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:0999ac42c4a0a568b8c4c17640b0d15ed74f3daf22c51a8e2d96ec491908ba6c",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:5c1bcc20c9058ca0e13084ba1278e8aaab241f6864dcacc1647642a4198654be"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_redcore_set_node_ttl_persists_through_aof_replay",
        "sha256:0999ac42c4a0a568b8c4c17640b0d15ed74f3daf22c51a8e2d96ec491908ba6c",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f", "sha256:5c1bcc20c9058ca0e13084ba1278e8aaab241f6864dcacc1647642a4198654be"],
    )
}
