//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:07a73361a0fcb1a4d429ba49
//! Content hash:   sha256:07a73361a0fcb1a4d429ba498199daec2757ebf686715c72885c91efb0e4905f
//! Source atom:    atom:code_member:3acbf44e1ec3d9301886d1b1
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `redcore_failed_snapshot_write_does_not_publish_staged_mutation`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_redcore_failed_snapshot_write_does_not_publish_staged_mutation(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "redcore_failed_snapshot_write_does_not_publish_staged_mutation";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_redcore_failed_snapshot_write_does_not_publish_staged_mutation",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:07a73361a0fcb1a4d429ba498199daec2757ebf686715c72885c91efb0e4905f",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_redcore_failed_snapshot_write_does_not_publish_staged_mutation",
        "sha256:07a73361a0fcb1a4d429ba498199daec2757ebf686715c72885c91efb0e4905f",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
