//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:07cb0bb2a4266bfd78d162ab
//! Content hash:   sha256:07cb0bb2a4266bfd78d162ab86fdefa738a3a9e9f36db3ae9723c5836e7fcc4b
//! Source atom:    atom:code_member:0a15ecbef38bab0cd9073c90
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `ready_for_publication`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_ready_for_publication(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "ready_for_publication";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_ready_for_publication",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:07cb0bb2a4266bfd78d162ab86fdefa738a3a9e9f36db3ae9723c5836e7fcc4b",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_ready_for_publication",
        "sha256:07cb0bb2a4266bfd78d162ab86fdefa738a3a9e9f36db3ae9723c5836e7fcc4b",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
    )
}
