//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:c08b7f7110259ef10d46e37a
//! Content hash:   sha256:c08b7f7110259ef10d46e37ad39689ae212c1c9ec3e5bd441ad9fb32ba5ad104
//! Source atom:    atom:code_member:e92086e83e43935d4aff745d
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `add_edge_indexes`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_add_edge_indexes(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "add_edge_indexes";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_add_edge_indexes",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:c08b7f7110259ef10d46e37ad39689ae212c1c9ec3e5bd441ad9fb32ba5ad104",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_add_edge_indexes",
        "sha256:c08b7f7110259ef10d46e37ad39689ae212c1c9ec3e5bd441ad9fb32ba5ad104",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
