//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:290408e4e29040ca11f1fa59
//! Content hash:   sha256:290408e4e29040ca11f1fa599ac494e720ce6568b10dd2a1c168386f3dd6afbd
//! Source atom:    atom:code_member:3cbd4d25abf4dab4cb645885
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `default_hybrid_edge_type_weights`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_default_hybrid_edge_type_weights(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "default_hybrid_edge_type_weights";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_default_hybrid_edge_type_weights",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:290408e4e29040ca11f1fa599ac494e720ce6568b10dd2a1c168386f3dd6afbd",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_default_hybrid_edge_type_weights",
        "sha256:290408e4e29040ca11f1fa599ac494e720ce6568b10dd2a1c168386f3dd6afbd",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
