//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:b2f7ee44725c224515a84165
//! Content hash:   sha256:b2f7ee44725c224515a841658ef08058840f18b59c0b29a158b74f4b84abf911
//! Source atom:    atom:code_member:7f9a497ef6dec470ce6edf56
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `upsert_node`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_upsert_node_b2f7ee44(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "upsert_node";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_upsert_node_b2f7ee44",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:b2f7ee44725c224515a841658ef08058840f18b59c0b29a158b74f4b84abf911",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_upsert_node_b2f7ee44",
        "sha256:b2f7ee44725c224515a841658ef08058840f18b59c0b29a158b74f4b84abf911",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:ce130bb612146f07681f25d0100a294b7099133fc7f4b87501d31f65b4cb5b7f"],
    )
}
