//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:c7999d5007445964197eadea
//! Content hash:   sha256:c7999d5007445964197eadea5b628d45ae2dfbd2417877109b5a3e75b3c638a9
//! Source atom:    atom:code_member:298f800e6e8efd6b55906ad4
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `vector_designations`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_vector_designations_c7999d50(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "vector_designations";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_vector_designations_c7999d50",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:c7999d5007445964197eadea5b628d45ae2dfbd2417877109b5a3e75b3c638a9",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_vector_designations_c7999d50",
        "sha256:c7999d5007445964197eadea5b628d45ae2dfbd2417877109b5a3e75b3c638a9",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
