//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:c2873c6f16915715425ba92f
//! Content hash:   sha256:c2873c6f16915715425ba92f2c7dbe8e337ecf9b9238f755b9d6e8dc9cfa6735
//! Source atom:    atom:code_test_body:d6a6e5cc99b3c69fbea1e6fd
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_file`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_file(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_file";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_file",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:c2873c6f16915715425ba92f2c7dbe8e337ecf9b9238f755b9d6e8dc9cfa6735",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:3f751b8073c67725b0c19fc9206ce4aff2e8efef7d63354794d4903fa1c1a4cf"],
        });
    }
    let expected_body_hash = "sha256:3f751b8073c67725b0c19fc9206ce4aff2e8efef7d63354794d4903fa1c1a4cf";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_file",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:c2873c6f16915715425ba92f2c7dbe8e337ecf9b9238f755b9d6e8dc9cfa6735",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:3f751b8073c67725b0c19fc9206ce4aff2e8efef7d63354794d4903fa1c1a4cf"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_file",
        "sha256:c2873c6f16915715425ba92f2c7dbe8e337ecf9b9238f755b9d6e8dc9cfa6735",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:3f751b8073c67725b0c19fc9206ce4aff2e8efef7d63354794d4903fa1c1a4cf"],
    )
}
