//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:5ccc80701cce8e5bafc44f75
//! Content hash:   sha256:5ccc80701cce8e5bafc44f75314609d66dc8ea9cf12860dffeb533ee4c1ed03f
//! Source atom:    atom:code_member:573d3f1f006e05ee84b285e7
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `for_agent`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_for_agent_5ccc8070(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "for_agent";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_for_agent_5ccc8070",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:5ccc80701cce8e5bafc44f75314609d66dc8ea9cf12860dffeb533ee4c1ed03f",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_for_agent_5ccc8070",
        "sha256:5ccc80701cce8e5bafc44f75314609d66dc8ea9cf12860dffeb533ee4c1ed03f",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707"],
    )
}
