//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:c62362bad22ec707d8734355
//! Content hash:   sha256:c62362bad22ec707d8734355a0b88f9226b99356da06328e356b5b76ccc3e9f0
//! Source atom:    atom:code_test_body:5a0eba6b65cee4c943befcc4
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_scan_unused_suppression`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_scan_unused_suppression(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_scan_unused_suppression";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_scan_unused_suppression",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:c62362bad22ec707d8734355a0b88f9226b99356da06328e356b5b76ccc3e9f0",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:169b4a5d771cac52803725b2110aeca0ac9945985b3b2d16b6444c846b8f0419"],
        });
    }
    let expected_body_hash = "sha256:169b4a5d771cac52803725b2110aeca0ac9945985b3b2d16b6444c846b8f0419";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_scan_unused_suppression",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:c62362bad22ec707d8734355a0b88f9226b99356da06328e356b5b76ccc3e9f0",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:169b4a5d771cac52803725b2110aeca0ac9945985b3b2d16b6444c846b8f0419"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_scan_unused_suppression",
        "sha256:c62362bad22ec707d8734355a0b88f9226b99356da06328e356b5b76ccc3e9f0",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:169b4a5d771cac52803725b2110aeca0ac9945985b3b2d16b6444c846b8f0419"],
    )
}
