//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:1f4eea88aa3ae71535b0b4e5
//! Content hash:   sha256:1f4eea88aa3ae71535b0b4e5e8119fa981db2d0c06bf9b6b91ac0531fd3eee92
//! Source atom:    atom:code_test_body:226305f0488bf5f29e80f116
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_duplicate`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_duplicate(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_duplicate";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_duplicate",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:1f4eea88aa3ae71535b0b4e5e8119fa981db2d0c06bf9b6b91ac0531fd3eee92",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:023d6b57ba5ba199a04d9757e3b1464c2bc09579b035ea82c047e08d89d19226", "sha256:545d517a353e5ff68982ce0d80a43863d39d59e78e8f3121c23cff8b7757f4c7"],
        });
    }
    let expected_body_hash = "sha256:545d517a353e5ff68982ce0d80a43863d39d59e78e8f3121c23cff8b7757f4c7";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_duplicate",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:1f4eea88aa3ae71535b0b4e5e8119fa981db2d0c06bf9b6b91ac0531fd3eee92",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:023d6b57ba5ba199a04d9757e3b1464c2bc09579b035ea82c047e08d89d19226", "sha256:545d517a353e5ff68982ce0d80a43863d39d59e78e8f3121c23cff8b7757f4c7"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_duplicate",
        "sha256:1f4eea88aa3ae71535b0b4e5e8119fa981db2d0c06bf9b6b91ac0531fd3eee92",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:023d6b57ba5ba199a04d9757e3b1464c2bc09579b035ea82c047e08d89d19226", "sha256:545d517a353e5ff68982ce0d80a43863d39d59e78e8f3121c23cff8b7757f4c7"],
    )
}
