//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:e6f36cd16a34922ea48588a7
//! Content hash:   sha256:e6f36cd16a34922ea48588a7621824eaa0c71bbbd754dd9bdad22125b67ae8b5
//! Source atom:    atom:code_member:ae5f78b76edef56f1bf2363b
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `labels`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_labels_e6f36cd1(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "labels";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_labels_e6f36cd1",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:e6f36cd16a34922ea48588a7621824eaa0c71bbbd754dd9bdad22125b67ae8b5",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_labels_e6f36cd1",
        "sha256:e6f36cd16a34922ea48588a7621824eaa0c71bbbd754dd9bdad22125b67ae8b5",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:1fe65b3260a8bd4efe2249d6ffc6247869578de7422dc1818be9f1572b000aba"],
    )
}
