//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:5f7a17fab52492b275a80f01
//! Content hash:   sha256:5f7a17fab52492b275a80f0117e2ea27e060d8d2669478c1f2f9b6b4b00eae2c
//! Source atom:    atom:code_test_body:0dc26db866ad62da053642db
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `reasoning_core_appends_versioned_scratchpad_revision`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_reasoning_core_appends_versioned_scratchpad_revision(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "reasoning_core_appends_versioned_scratchpad_revision";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_reasoning_core_appends_versioned_scratchpad_revision",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:5f7a17fab52492b275a80f0117e2ea27e060d8d2669478c1f2f9b6b4b00eae2c",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707", "sha256:8a2ed1ff6f778cb8ac7caaf19fb9af27c5c6d6f91fd842a7bf62d1fb70267580"],
        });
    }
    let expected_body_hash = "sha256:8a2ed1ff6f778cb8ac7caaf19fb9af27c5c6d6f91fd842a7bf62d1fb70267580";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_reasoning_core_appends_versioned_scratchpad_revision",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:5f7a17fab52492b275a80f0117e2ea27e060d8d2669478c1f2f9b6b4b00eae2c",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707", "sha256:8a2ed1ff6f778cb8ac7caaf19fb9af27c5c6d6f91fd842a7bf62d1fb70267580"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_reasoning_core_appends_versioned_scratchpad_revision",
        "sha256:5f7a17fab52492b275a80f0117e2ea27e060d8d2669478c1f2f9b6b4b00eae2c",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:6794be62a8937f8b521f8b5c2628924a02ddae362b8f8044e98b043945d41707", "sha256:8a2ed1ff6f778cb8ac7caaf19fb9af27c5c6d6f91fd842a7bf62d1fb70267580"],
    )
}
