//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:50c341f1beea33309e25bc02
//! Content hash:   sha256:50c341f1beea33309e25bc0290fe36129dc4906d986455fb5acaa8b648b7a1a9
//! Source atom:    atom:code_member:fdfbc718620c280316bd8027
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `parse_spanned`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_parse_spanned(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "parse_spanned";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_parse_spanned",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:50c341f1beea33309e25bc0290fe36129dc4906d986455fb5acaa8b648b7a1a9",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:fdb7986b31141627408b51381607f66ef4b69dd81b080c2f6489da267e96b2ba"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_parse_spanned",
        "sha256:50c341f1beea33309e25bc0290fe36129dc4906d986455fb5acaa8b648b7a1a9",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:fdb7986b31141627408b51381607f66ef4b69dd81b080c2f6489da267e96b2ba"],
    )
}
