//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:5dff136a7ce36e449cc35e7a
//! Content hash:   sha256:5dff136a7ce36e449cc35e7a99b2a2db7aa9c7bb6cdf51cab8d12b36cceb5898
//! Source atom:    atom:code_member:bbdea4b234a5a8620bfac6bb
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `allows`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_allows(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "allows";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_allows",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:5dff136a7ce36e449cc35e7a99b2a2db7aa9c7bb6cdf51cab8d12b36cceb5898",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_allows",
        "sha256:5dff136a7ce36e449cc35e7a99b2a2db7aa9c7bb6cdf51cab8d12b36cceb5898",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
