//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:b53e1b9640aa87d675b0cc25
//! Content hash:   sha256:b53e1b9640aa87d675b0cc253ab1b7534354409a031fb4a3642a1b9bf5a73f29
//! Source atom:    atom:code_test_body:583c33f34ce5f55f755ba2bb
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `cascade_stays_http2_only_without_optional_escalators`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_cascade_stays_http2_only_without_optional_escalators(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "cascade_stays_http2_only_without_optional_escalators";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_cascade_stays_http2_only_without_optional_escalators",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:b53e1b9640aa87d675b0cc253ab1b7534354409a031fb4a3642a1b9bf5a73f29",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:79c8dc0d0f77f874c44d2b5065c489aa304b5c9993a94c5307b30ee64d513c11", "sha256:f4b5117a7b3109e688b996f297e324f2f2d36b7582546c3e636592ff78701473"],
        });
    }
    let expected_body_hash = "sha256:f4b5117a7b3109e688b996f297e324f2f2d36b7582546c3e636592ff78701473";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_cascade_stays_http2_only_without_optional_escalators",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:b53e1b9640aa87d675b0cc253ab1b7534354409a031fb4a3642a1b9bf5a73f29",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:79c8dc0d0f77f874c44d2b5065c489aa304b5c9993a94c5307b30ee64d513c11", "sha256:f4b5117a7b3109e688b996f297e324f2f2d36b7582546c3e636592ff78701473"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_cascade_stays_http2_only_without_optional_escalators",
        "sha256:b53e1b9640aa87d675b0cc253ab1b7534354409a031fb4a3642a1b9bf5a73f29",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:79c8dc0d0f77f874c44d2b5065c489aa304b5c9993a94c5307b30ee64d513c11", "sha256:f4b5117a7b3109e688b996f297e324f2f2d36b7582546c3e636592ff78701473"],
    )
}
