//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:7cebc00ca9dca86bde147be9
//! Content hash:   sha256:7cebc00ca9dca86bde147be971e5c80b59ee501a31f129cd29e9d5cd65287f70
//! Source atom:    atom:code_member:acb1f9da3363d64d35cca55d
//! Source dialect: callable_signature_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `graph_snapshot`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_graph_snapshot_7cebc00c(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "graph_snapshot";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_graph_snapshot_7cebc00c",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:7cebc00ca9dca86bde147be971e5c80b59ee501a31f129cd29e9d5cd65287f70",
            parent_hashes: &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_graph_snapshot_7cebc00c",
        "sha256:7cebc00ca9dca86bde147be971e5c80b59ee501a31f129cd29e9d5cd65287f70",
        &["sha256:fda037bfe51f515d3cabfebf0e74524063eb4dee7750f0cfe0af82bce6938889", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
