//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:de079cd5f728ee0044419053
//! Content hash:   sha256:de079cd5f728ee0044419053cf9e25a121bbcffb18690957c4d98c05d7e78c6d
//! Source atom:    atom:code_member:7043679ce60c4b7b58ea8814
//! Source dialect: semantic_callable_view
//! Target:         validator_contract

#![allow(dead_code)]

use crate::common::{CodeMemberSignature, ValidatorFailure, ValidatorReceipt};

/// Generated validator for `schema_payload`.
///
/// Returns `Ok(())` when the candidate's signature matches the lowered
/// `code_member` view this validator was compiled from. The validator is
/// advisory: pack promotion still requires the benchmark gate to clear.
pub fn validates_schema_payload(candidate: &CodeMemberSignature) -> ValidatorReceipt {
    let expected_name = "schema_payload";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_schema_payload",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:de079cd5f728ee0044419053cf9e25a121bbcffb18690957c4d98c05d7e78c6d",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_schema_payload",
        "sha256:de079cd5f728ee0044419053cf9e25a121bbcffb18690957c4d98c05d7e78c6d",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:048906e4a3588930ca09c2aef0fa07bf024999a249efe5cd377237b944005f3f"],
    )
}
