//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:698ed1eec4f52f52ff8ad2f6
//! Content hash:   sha256:698ed1eec4f52f52ff8ad2f6da2606f086a727f301bcee5e62634533b5363b81
//! Source atom:    atom:code_test_body:ee0e34de5f0ec0cd3325402a
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `test_status_code_success_with_no_match`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_test_status_code_success_with_no_match(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "test_status_code_success_with_no_match";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_status_code_success_with_no_match",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:698ed1eec4f52f52ff8ad2f6da2606f086a727f301bcee5e62634533b5363b81",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:01302ae7855838f4dd563b4a981e2607ab7e589475426cfea4645483341ca193"],
        });
    }
    let expected_body_hash = "sha256:01302ae7855838f4dd563b4a981e2607ab7e589475426cfea4645483341ca193";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_test_status_code_success_with_no_match",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:698ed1eec4f52f52ff8ad2f6da2606f086a727f301bcee5e62634533b5363b81",
            parent_hashes: &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:01302ae7855838f4dd563b4a981e2607ab7e589475426cfea4645483341ca193"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_test_status_code_success_with_no_match",
        "sha256:698ed1eec4f52f52ff8ad2f6da2606f086a727f301bcee5e62634533b5363b81",
        &["sha256:683af3877bc763fb5202ed7c0d6303b47685214408973c468a77af87c1019f96", "sha256:211133d5ff109b385ad8c1acf739399c3e7a03e7f580f23a38174015d58a02e3", "sha256:01302ae7855838f4dd563b4a981e2607ab7e589475426cfea4645483341ca193"],
    )
}
