//! Generated by Theseus Skill Encoder
//! Do not hand-edit. Regenerate via `code_compile_pack` MCP verb.
//!
//! Artifact:       artifact:9d31c030247d5d66e88ce57a
//! Content hash:   sha256:9d31c030247d5d66e88ce57af125fa84501a9114ccb7cf13a1e8aebfb4066cc2
//! Source atom:    atom:code_test_body:1cba4c099c482bb55d7a59bc
//! Source dialect: rust_test_body_view
//! Target:         validator_contract
//! Checker:        cargo_test

#![allow(dead_code)]

use crate::common::{RustTestBodyCandidate, ValidatorFailure, ValidatorReceipt};

/// Generated validator for lifted Rust test `decision_is_deterministic_and_content_addressable`.
///
/// This validator checks that the host supplied the exact lifted test body
/// selected by the encoder. Running that body under `cargo test` is the
/// checker-engine step; this function preserves the content-addressed contract
/// that tells the harness which test was lifted.
pub fn validates_decision_is_deterministic_and_content_addressable(candidate: &RustTestBodyCandidate) -> ValidatorReceipt {
    let expected_name = "decision_is_deterministic_and_content_addressable";
    if candidate.name != expected_name {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_decision_is_deterministic_and_content_addressable",
            expected: expected_name.to_string(),
            actual: candidate.name.clone(),
            artifact_content_hash: "sha256:9d31c030247d5d66e88ce57af125fa84501a9114ccb7cf13a1e8aebfb4066cc2",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:4b153355a0f20ec3efa2052db88524e7422fec4061f1c7ab4e85e5588a19dbec", "sha256:4e6ae5862f13b96820944ce4b8280e0d1985fc57873e62abd7f8a394ecf5c731"],
        });
    }
    let expected_body_hash = "sha256:4e6ae5862f13b96820944ce4b8280e0d1985fc57873e62abd7f8a394ecf5c731";
    if candidate.body_hash != expected_body_hash {
        return ValidatorReceipt::failed(ValidatorFailure {
            validator_id: "skill_encoder::validates_decision_is_deterministic_and_content_addressable",
            expected: expected_body_hash.to_string(),
            actual: candidate.body_hash.clone(),
            artifact_content_hash: "sha256:9d31c030247d5d66e88ce57af125fa84501a9114ccb7cf13a1e8aebfb4066cc2",
            parent_hashes: &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:4b153355a0f20ec3efa2052db88524e7422fec4061f1c7ab4e85e5588a19dbec", "sha256:4e6ae5862f13b96820944ce4b8280e0d1985fc57873e62abd7f8a394ecf5c731"],
        });
    }
    ValidatorReceipt::passed(
        "skill_encoder::validates_decision_is_deterministic_and_content_addressable",
        "sha256:9d31c030247d5d66e88ce57af125fa84501a9114ccb7cf13a1e8aebfb4066cc2",
        &["sha256:4c8f06571b49170d725a11897df6d45ca6af088ef15fea216ca6100960033a8e", "sha256:4b153355a0f20ec3efa2052db88524e7422fec4061f1c7ab4e85e5588a19dbec", "sha256:4e6ae5862f13b96820944ce4b8280e0d1985fc57873e62abd7f8a394ecf5c731"],
    )
}
