#!/usr/bin/env bash
# Regenerate the live tool-surface snapshot used as a drift gate.
#
# SCOPE. Capability *teaching* is owned by capabilities/families.json and the
# generated family catalogs (see references/CAPABILITY_CATALOG.generated.md);
# retired names are owned by references/COMPATIBILITY.generated.md. This script
# does not compete with either and never writes a skill. It produces one thing:
#
#   - references/TOOL_SURFACE.md   raw live-server tool surface, drift evidence
#
# WHY IT EXISTS. The committed capability projections are pinned to a source
# catalog snapshot, so they cannot tell you the *running* node drifted from
# what the plugin teaches. This script asks the live server directly. Running
# it against a live node and a source dump on the same day surfaced a genuine
# six-tool skew, which is exactly the signal it is here to catch.
#
# Sources (first match wins):
#   --from-file <catalog.json>   a dump from the harness-capability-source-catalog bin
#   --cargo <theorem-repo>       run the dump bin from a Theorem checkout
#   --url <mcp-url>              JSON-RPC tools/list against a live server
#                                (token from --token or $THEOREM_HARNESS_API_TOKEN)
# Modes:
#   --check                      regenerate to temp and fail on drift (exit 1)
#
# Wire this into the version-bump checklist: a bump must not ship with drift.

set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SURFACE_FILE="$PLUGIN_ROOT/references/TOOL_SURFACE.md"

FROM_FILE="" CARGO_REPO="" URL="" TOKEN="${THEOREM_HARNESS_API_TOKEN:-}" CHECK=0
while [ $# -gt 0 ]; do
  case "$1" in
    --from-file) FROM_FILE="$2"; shift 2 ;;
    --cargo) CARGO_REPO="$2"; shift 2 ;;
    --url) URL="$2"; shift 2 ;;
    --token) TOKEN="$2"; shift 2 ;;
    --check) CHECK=1; shift ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

command -v jq >/dev/null || { echo "jq is required" >&2; exit 2; }

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT
catalog="$workdir/catalog.json"

if [ -n "$FROM_FILE" ]; then
  cp "$FROM_FILE" "$catalog"
elif [ -n "$CARGO_REPO" ]; then
  (cd "$CARGO_REPO" && cargo run -q -p rustyred-thg-mcp --bin harness-capability-source-catalog) > "$catalog"
elif [ -n "$URL" ]; then
  # Synthesize a catalog-shaped object from a live tools/list. Narrower than the
  # source catalog (no SDL/registry) but carries the same flat_mcp surface.
  auth=()
  [ -n "$TOKEN" ] && auth=(-H "Authorization: Bearer $TOKEN")
  # ${arr[@]+...} guards empty-array expansion under set -u on bash 3.2 (macOS).
  curl -fsS ${auth[@]+"${auth[@]}"} -H 'Content-Type: application/json' \
    -d '{"jsonrpc":"2.0","id":"regen","method":"tools/list"}' "$URL" \
    | jq '{server_version: "live", flat_mcp: (.result.tools // .tools)}' > "$catalog"
else
  echo "one of --from-file, --cargo, or --url is required" >&2
  exit 2
fi

jq -e '.flat_mcp | length > 0' "$catalog" >/dev/null \
  || { echo "catalog has no flat_mcp tools" >&2; exit 1; }

# Deterministic digest over sorted (name, description) pairs; no timestamps so
# regeneration is reproducible and drift means real change.
digest="$(jq -S '[.flat_mcp[] | {name, description}] | sort_by(.name)' "$catalog" | shasum -a 256 | cut -c1-16)"
server_version="$(jq -r '.server_version // "unknown"' "$catalog")"
count="$(jq -r '.flat_mcp | length' "$catalog")"

# Family grouping: longest prefix first; presentation only, names come from the
# catalog untouched.
family_jq='
  def family:
    . as $n
    | ["rustyred_thg_graph_version", "rustyred_thg_algorithm", "rustyred_thg_symbolic",
       "rustyred_thg_spatial", "rustyred_thg", "reverse_engineer", "typed_commitment",
       "identity_binding", "data_registry", "coordination", "verification", "multihead",
       "epistemic", "practice", "harness_kg", "harness", "stream", "design", "ensemble",
       "memory", "skill", "job", "code", "self", "graphql", "resolve", "web", "read",
       "tool", "context"]
    | map(select(. as $p | $n == $p or ($n | startswith($p + "_")))) | first // "core";
'

{
  echo "# Live tool surface snapshot (generated)"
  echo
  echo "Generated by \`scripts/regen-routing.sh\`. Do not hand-edit; rerun the"
  echo "script instead. \`--check\` fails on drift."
  echo
  echo "This is drift evidence, not a teaching catalog. Capability teaching"
  echo "lives in \`capabilities/families.json\` and the generated family"
  echo "catalogs; retired names live in \`COMPATIBILITY.generated.md\`. This file"
  echo "only records which tools the server actually advertised, so a running"
  echo "node that has drifted from what the plugin teaches is detectable."
  echo
  echo "- server_version: \`$server_version\`"
  echo "- tools: $count"
  echo "- digest: \`$digest\`"
  echo
  jq -r "$family_jq"'
    [.flat_mcp[] | {name, description: (.description // "" | gsub("\\s+"; " "))}]
    | sort_by(.name) | group_by(.name | family) | sort_by(.[0].name | family)
    | .[]
    | "## " + (.[0].name | family) + "\n\n| Tool | Purpose |\n|---|---|\n"
      + (map("| `" + .name + "` | " + .description + " |") | join("\n"))
      + "\n"
  ' "$catalog"
} > "$workdir/TOOL_SURFACE.md"

if [ "$CHECK" = 1 ]; then
  if diff -u "$SURFACE_FILE" "$workdir/TOOL_SURFACE.md"; then
    echo "tool surface is in sync (digest $digest, $count tools)"
  else
    echo "DRIFT: regenerate with scripts/regen-routing.sh before shipping" >&2
    exit 1
  fi
else
  cp "$workdir/TOOL_SURFACE.md" "$SURFACE_FILE"
  echo "regenerated: $SURFACE_FILE (digest $digest, $count tools)"
fi
